jpmorganchase/salt-ds

- .vscode/settings.json
Update deprecated settings
https://github.com/jest-community/vscode-jest/blob/c48f6e921c33cfdf6643f6526daef78e8f7228d3/CHANGELOG.md#400-alpha3
> Update deprecated jest vscode command setting

- .github/workflows/chromatic.yml
- .storybook/main.ts
- package.json
- yarn.lock
I've created a project on chromatic and added the repo secret token as CHROMATIC_PROJECT_TOKEN
> add preparation for chromatic deployment

- packages/lab/src/__tests__/__e2e__/layout/Flex.cy.tsx
- packages/lab/src/__tests__/__e2e__/layout/Flow.cy.tsx
- packages/lab/src/__tests__/__e2e__/layout/Grid.cy.tsx
- packages/lab/src/__tests__/__e2e__/layout/ParentChild.cy.tsx
- packages/lab/src/__tests__/__e2e__/layout/Split.cy.tsx
- packages/lab/src/__tests__/__e2e__/layout/Stack.cy.tsx
- packages/lab/src/layout/FlexLayout/FlexLayout.css
- packages/lab/src/layout/FlexLayout/FlexLayout.tsx
- packages/lab/src/layout/GridLayout/GridLayout.css
After a conversation with Darrin and Ben, we are using 3x as a default for every density but TD where the default will be 2x
> update gap defaults

- .changeset/four-waves-rest.md
- .github/workflows/test.yml
- packages/core/src/utils/useResponsiveProp.ts
- packages/lab/src/content-status/ContentStatus.tsx
- packages/lab/src/content-status/internal/getDeterminateLoadingComponent.tsx
- packages/lab/src/content-status/internal/getIndeterminateLoadingComponent.tsx
- packages/lab/src/metric/MetricContent.tsx
- packages/lab/src/metric/MetricHeader.tsx
- packages/lab/src/typography/useTruncation.tsx
We don't want core to reference lab, or package reference themselves
Fix existing errors, see "Test / dependency-check (push) " step
Example failure: https://github.com/jpmorganchase/uitk/runs/6688417907?check_suite_focus=true
> Add build dependency check

- .changeset/slimy-geese-unite.md
- packages/core/src/__tests__/__e2e__/layout/Grid.cy.tsx
- packages/core/stories/layout/flex-layout.stories.tsx
- packages/core/stories/layout/flow-layout.stories.tsx
- packages/core/stories/layout/grid-layout.stories.tsx
- packages/core/stories/layout/stack-layout.stories.tsx
- packages/core/stories/layout/styles.css
- packages/lab/src/__tests__/__e2e__/layout/Border.cy.tsx
- packages/lab/src/layout/SplitLayout/SplitLayout.tsx
- packages/lab/stories/layout/border-layout.stories.tsx
- packages/lab/stories/layout/parent-child-layout.stories.tsx
- packages/lab/stories/layout/split-layout.stories.tsx
- packages/lab/stories/layout/styles.css
WIP examples for layout components. Will be adding more soon but it will be good to start getting these merged in to avoid merge conflicts
> Layout storybook examples

- .changeset/dry-snakes-talk.md
- packages/core/src/layout/FlexLayout/FlexLayout.css
- packages/core/src/layout/FlexLayout/FlexLayout.tsx
- packages/core/src/layout/GridLayout/GridLayout.css
- packages/core/src/layout/GridLayout/GridLayout.tsx
- packages/core/stories/layout/grid-layout.stories.tsx
- packages/lab/stories/layout/border-item.stories.tsx
we are using 3 as the default gap multiplier, however users should be able to modify it by intervals of size unit (1) rather than the default multiplier
> fix gap multiplier

- .github/workflows/test.yml
Test actions are triggered twice in PR & push
> Test action push trigger to only run on main

- .changeset/rich-roses-rest.md
- packages/core/src/utils/useId.ts
- packages/lab/src/__tests__/__e2e__/contact-details/ContactDetails.accessibility.cy.tsx
> Refactor useId to use React's implementation when using React 18

- packages/ag-grid-theme/css/_uitk-ag-theme-mixin.scss
- packages/ag-grid-theme/stories/ag-grid.stories.tsx
Fixed a warning wen building ag-grid-theme
Fixed select-all cell
Moved ag-grid-theme stories from root to Grid
Fixed a couple of typos in css vars names
> Ag-grid-theme-update

- .changeset/little-rabbits-exercise.md
- package.json
- packages/lab/src/__tests__/__e2e__/calendar/Calendar.cy.tsx
- packages/lab/src/calendar/Calendar.tsx
- packages/lab/src/calendar/internal/CalendarCarousel.tsx
- packages/lab/src/calendar/internal/CalendarDay.css
- packages/lab/src/calendar/internal/CalendarDay.tsx
- packages/lab/src/calendar/internal/CalendarMonth.tsx
- packages/lab/src/calendar/internal/CalendarNavigation.tsx
- packages/lab/src/calendar/internal/CalendarWeekHeader.css
- packages/lab/src/calendar/internal/CalendarWeekHeader.tsx
- packages/lab/src/calendar/useCalendar.ts
- packages/lab/src/calendar/useCalendarDay.ts
- packages/lab/stories/calendar.stories.tsx
- yarn.lock
- Update the Calendar stories
- Change the unselectable high emphasis to medium
- Add tooltip to previous and next month buttons
- Prevent a month only calendar wrapping to the next or previous year
> Calendar updates

- .changeset/cuddly-falcons-doubt.md
- packages/core/src/tooltip/Tooltip.css
- packages/core/stories/Card.stories.newapp-card.css
- packages/core/stories/Tooltip.stories.newapp-tooltip.css
- packages/core/stories/tooltip.doc.stories.mdx
- packages/core/stories/tooltip.stories.tsx
- tooling/css-variable-docgen-components/src/CharacteristicUsage.tsx
- tooling/css-variable-docgen-components/src/CharacteristicUsageRow.tsx
Tooltip characteristics, docs, custom styling (#219 dupe due to chromatic history mismatch)
> Tooltip characteristic usage

- .changeset/wild-chefs-sparkle.md
- packages/lab/src/buttonbar/ButtonBar.css
- packages/lab/src/buttonbar/OrderedButton.css
> Fix OrderedButton applying a right margin incorrectly

- .changeset/moody-moose-smash.md
- packages/core/src/form-field/FormField.css
- packages/core/src/form-field/FormHelperText.css
- packages/core/src/form-field/FormLabel.css
- packages/core/src/pill/Pill.css
- packages/lab/src/badge/Badge.css
- packages/lab/src/calendar/internal/CalendarWeekHeader.css
- packages/lab/src/contact-details/ContactDetails.css
- packages/lab/src/slider/Slider.css
- packages/lab/src/typography/Text.css
- packages/theme/css/characteristics/text.css
- tooling/stylelint/custom-property-no-foundation-color/index.js
Changes to text characteristic fontSize tokens
TD:
H1 36px -> 42px
H2 28px -> 32px
H3 18px -> 24px
Caption 12px -> 14px
Help 12px -> 14px
LD:
Caption 11px -> 12px
Help 11px -> 12px
> Characteristics: text font size token updates

- .changeset/fresh-maps-beam.md
- packages/grid/src/grid/components/Grid.css
- packages/lab/src/toggle-button/ToggleButton.css
- packages/lab/src/toggle-button/ToggleButton.tsx
- packages/lab/src/toggle-button/ToggleButtonGroup.css
- packages/lab/stories/toggle-button.stories.tsx
- Part of CSS clean up and standardisation: ToggleButton using characteristics: not 100% polished, but ensures lab package passes linting
ToggleButton currently completely overrides characteristics to get styles; this PR uses local custom properties as well as the component API's of e.g. Button
Note: This is not 100% perfection of ToggleButton styling, but is better than the current implementation
> ToggleButton characteristics

- .changeset/seven-shirts-swim.md
- packages/lab/src/progress/CircularProgress.css
- packages/lab/src/spinner/Spinner.css
- packages/lab/stories/progress.stories.tsx
- packages/lab/stories/spinner.stories.tsx
- packages/theme/css/characteristics/measured.css
- packages/theme/css/foundations/fade.css
- packages/theme/css/foundations/palette.css
Gradient from palette and measured characteristic fill values replaced with solid blue color in line with design change; backwards compatibility classes added to CircularProgress and Spinner
> Measured characteristic fill value change

- .changeset/calm-forks-live.md
- packages/core/src/checkbox/CheckboxGroup.css
> Fix Checkbox horizontal group spacing 

- packages/core/stories/button.doc.stories.mdx
Text updated based on doc template.
> Update Button docs

- .changeset/poor-chicken-add.md
- packages/lab/src/tabs/Tab.css
- packages/lab/src/tabs/TabActivationIndicator.css
Tabs focus (and transition, minor) broken in #380 
We don't want to provide an API directly in the characteristics; instead where needed, (like for Tabs- this PR), provide higher specificity on component with uitkFocusVisible class.
> Fix Tabs focus and animation

- .changeset/tender-books-cheer.md
- packages/core/src/pill/ClosablePill.tsx
- packages/core/src/pill/Pill.tsx
- packages/core/src/pill/PillBase.tsx
- packages/core/src/pill/SelectablePill.tsx
- packages/core/src/radio-button/RadioButton.tsx
- packages/core/src/radio-button/RadioButtonBase.css
- packages/core/src/radio-button/RadioButtonBase.tsx
- packages/core/src/radio-button/RadioButtonGroup.tsx
- packages/core/src/radio-button/RadioButtonIcon.css
- packages/core/src/radio-button/RadioButtonIcon.tsx
- packages/core/src/radio-button/index.ts
- packages/grid/src/grid/column-types/row-selection-radio/RowSelectionRadioCellValue.tsx
- packages/grid/src/grid/components/Grid.css
PillBase moved to root folder of Pill;
RadioButton subcomponents to begin with component name:
Radio -> RadioButtonBase
RadioIcon -> RadioButtonIcon
> Move PillBase to root folder; Rename RadioButton components to begin with component name

- .changeset/two-crabs-knock.md
- packages/core/src/card/Card.css
- packages/core/stories/card.stories.tsx
Fixes #401 
Adds active styling (focus ring) and interactable disabled styling (interactable styling would previously override disabled - this is fixed)
> Card styling fixes

- package.json
- packages/ag-grid-theme/scripts/build.js
- yarn.lock
Removes merge which removes https://github.com/advisories/GHSA-7wpw-2hjm-89gp
> Replace watch with chokidar

- .changeset/custom-kathan-changeset.md
- packages/core/src/toolkit-provider/ToolkitProvider.tsx
> Ensure breakpoints are always set

- packages/core/src/button/Button.css
- packages/core/src/form-field/FormField.css
See https://github.com/jpmorganchase/uitk/issues/455 regarding :not usage
> Remove :not usage on Button and FormField

- .eslintrc.js
- .yarn/patches/modular-scripts-npm-3.4.0-8cdb747f13.patch
- package.json
- yarn.lock
Signed-off-by: Josh Wooding <12938082+joshwooding@users.noreply.github.com>
> Update modular to v3.4.0

- packages/core/stories/aria-announcer.doc.stories.mdx
Signed-off-by: Josh Wooding <12938082+joshwooding@users.noreply.github.com>
> AriaAnnouncer docs update

- .changeset/violet-waves-carry.md
- packages/lab/src/banner/Banner.css
- packages/lab/src/content-status/ContentStatus.css
- packages/lab/src/dropdown/DropdownButton.css
- packages/lab/src/list/Highlighter.css
- packages/lab/src/list/ListItem.css
- packages/theme/css/characteristics/actionable.css
- packages/theme/css/characteristics/measured.css
- packages/theme/css/characteristics/navigable.css
- packages/theme/css/characteristics/text.css
- packages/theme/css/foundations/typography.css
- packages/theme/stories/foundations/foundations.stories.mdx
- packages/theme/stories/foundations/typography.stories.mdx
- packages/theme/stories/introduction.stories.mdx
- playground/theme-editor-electron/src/app/themeEditorStyles.css
- playground/theme-editor-showcase/src/themeEditorStyles.css
Change -typography-weight tokens to -typography-fontWeight to align with -text-fontWeight choice in characteristic tokens
> Change -typography-weight tokens to -typography-fontWeight

- .changeset/loud-sloths-think.md
- packages/lab/src/tabs/Tabstrip.css
- packages/theme/css/characteristics/text.css
- packages/theme/css/foundations/typography.css
Remove old typography sizes from theme; move base line height to foundation
> Remove old typography sizes from theme and move base line height to foundation

- .changeset/odd-ligers-notice.md
- packages/lab/src/dropdown/Dropdown.tsx
- packages/lab/src/dropdown/useDropdown.ts
- packages/lab/stories/dropdown.stories.tsx
If user passes controlled or default props for highlightedindex to Dropdown, via the LIstProps, Dropdown should honour those props.
> Allow dropdown highlighting  to be controlled

- .changeset/curly-cows-buy.md
- packages/theme/css/characteristics/accent.css
- packages/theme/css/characteristics/actionable.css
- packages/theme/css/characteristics/container.css
- packages/theme/css/characteristics/draggable.css
- packages/theme/css/characteristics/droptarget.css
- packages/theme/css/characteristics/editable.css
- packages/theme/css/characteristics/focused.css
- packages/theme/css/characteristics/navigable.css
- packages/theme/css/characteristics/ratable.css
- packages/theme/css/characteristics/selectable.css
- packages/theme/css/characteristics/separable.css
- packages/theme/css/foundations/palette.css
- packages/theme/stories/characteristics/accent.stories.mdx
- packages/theme/stories/characteristics/actionable.stories.mdx
- packages/theme/stories/characteristics/container.stories.mdx
- packages/theme/stories/characteristics/navigable.stories.mdx
Sync up with Figma - update or add any missing tokens
> Alignment with Figma characteristics

- .changeset/nice-students-grow.md
- packages/theme/css/foundations/size.css
- packages/theme/stories/foundations/size.stories.mdx
--uitk-size-detail from size work
> Add size-detail token

- packages/core/stories/aria-announcer.doc.stories.mdx
Updates AriaAnnouncer docs to be more consistent with TookitProvider's
> Update AriaAnnouncer docs

- .changeset/hungry-napkins-fight.md
- packages/core/src/layout/LayerLayout/LayerLayout.css
- packages/core/src/scrim/Scrim.css
- packages/core/src/tooltip/Tooltip.css
- packages/lab/src/combo-box-deprecated/ComboBox.css
- packages/lab/src/dropdown/Dropdown.css
- packages/lab/src/overlay/Overlay.css
- packages/theme/css/foundations/zindex.css
- packages/theme/stories/foundations/zindex.stories.mdx
- packages/theme/stories/introduction.stories.mdx
Update zIndex tokens - use camel case and rename tooltip to flyover
> Update zIndex tokens

- .changeset/ruby-cousins-laugh.md
- packages/theme/css/characteristics/status.css
- packages/theme/css/foundations/palette.css
- packages/theme/stories/foundations/palette.stories.mdx
- packages/theme/stories/introduction.stories.mdx
Change palette -icon tokens to -foreground
> Change palette -icon tokens to -foreground

- .changeset/beautiful-camels-sing.md
- packages/theme/css/characteristics/text.css
Correct line height values in text characteristic
> Correct line height values in text characteristic

- .changeset/healthy-chefs-hear.md
- packages/theme/css/characteristics/focused.css
- packages/theme/css/foundations/palette.css
- packages/theme/stories/foundations/palette.stories.mdx
New palette interact outline token used in focused characteristic
> New palette interact outline token

- .github/ISSUE_TEMPLATE/config.yml
* Enabled blank issues (sorry - I hadn't meant to disable them before)
* Reworded feedback link to be more consistent with others on issue chooser screen
> Tweaked issue chooser config

- packages/theme/css/characteristics/text.css
Fixes unintended change in https://github.com/jpmorganchase/uitk/pull/736
cc @libertymayc
> Fix unintended change to strong font weights

- packages/theme/css/characteristics/separable.css
Border token was removed in #769 and added back in #674
> Fix unintended change to separable.css

- .changeset/unlucky-bears-sing.md
- packages/grid/src/BaseCell.css
- packages/grid/src/BaseCell.tsx
- packages/grid/src/Grid.css
- packages/grid/src/Grid.tsx
- packages/grid/src/GroupHeaderCell.css
- packages/grid/src/GroupHeaderCell.tsx
- packages/grid/src/HeaderCell.css
- packages/grid/src/HeaderCell.tsx
- packages/grid/src/__tests__/__e2e__/Grid.cy.tsx
- packages/grid/src/internal/CellMeasure.tsx
- packages/grid/src/internal/FakeCell.css
- packages/grid/src/internal/LeftPart.css
- packages/grid/src/internal/LeftPart.tsx
- packages/grid/src/internal/RightPart.css
- packages/grid/src/internal/RightPart.tsx
- packages/grid/src/internal/TableBody.tsx
- packages/grid/src/internal/TableRow.css
- packages/grid/src/internal/TableRow.tsx
- packages/grid/src/internal/TopLeftPart.css
- packages/grid/src/internal/TopLeftPart.tsx
- packages/grid/src/internal/TopPart.css
- packages/grid/src/internal/TopPart.tsx
- packages/grid/src/internal/TopRightPart.css
- packages/grid/src/internal/TopRightPart.tsx
- packages/grid/src/internal/gridHooks.tsx
- packages/grid/stories/grid-cssVariables.stories.tsx
- packages/grid/stories/grid.stories.tsx
1) Additional separators (pinned column separators) added (optional, enabled by default)
2) Pinned/unpinned column separator replaces the regular column separator and column header separator (rendered on the same place)
3) Shadows have no gaps between the header and table body
4) Header has a shadow when scrollTop is not zero
> Grid shadows and borders

- packages/theme/css/foundations/palette.css
These were flipped in Figma and have now been corrected
> Fix --uitk-palette-navigate-foreground hover and active tokens

- tooling/css-variable-docgen-plugin/src/index.ts
Closes https://github.com/jpmorganchase/uitk/issues/300
> Fix css-variable-docgen-plugin

- site/src/pages/index.module.css
- site/src/pages/index.tsx
- Remove button from homepage and style link instead
- Add `main` to homepage
> Site a11y bugs

- site/docs/components/_index/components-list.tsx
- site/docs/getting-started/develop.mdx
> Updated code and NPM package mentions

- site/docusaurus.config.js
- site/src/components/accordion/info/homepage.tsx
- site/src/pages/index.tsx
Minor copy updates on the homepage based on Mitch's feedback.
> Site: homepage copy updates

- .changeset/early-items-smash.md
- packages/grid/src/BaseCell.css
- packages/grid/src/BaseCell.tsx
- packages/grid/stories/grid-variants.stories.tsx
- packages/grid/stories/grid.stories.css
"Grid variants" story has a new checkbox that enables "compact" (ultra high density) look. Available only in high density.
> Grid compact variant added

- site/docs/getting-started/IconsTable.module.css
- site/docs/getting-started/designing.mdx
- site/src/components/card/Card.module.css
- site/src/css/custom.css
- site/src/pages/_index/accordion/Accordion.module.css
- site/src/pages/_index/features/Features.module.css
- site/src/pages/index.module.css
fix height in pages, add max content width so pages don't go overly wide and fix a few margins and copy.
> few fixes to site

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> Update wording on issue forms

- site/docs/components/_index/components-list.tsx
- site/docusaurus.config.js
Updates some links and config on the site so that they all use the `saltdesignsystem.com` domain
> Update links on site

- package.json
- packages/grid/stories/grid.doc.stories.mdx
- site/docs/components/_index/components-list.tsx
Links to DataGrid stories in grid.doc.stories.mdx fixed
> Links to data-grid stories fixed

- packages/ag-grid-theme/stories/ag-grid.doc.stories.mdx
uitk #582 
---
- remove stories no longer in use
- update docs 
- fix story links
> Update/tidy up AG Grid Theme docs

- .changeset/flat-points-perform.md
- packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
- packages/ag-grid-theme/css/_uitk-ag-theme-mixin.scss
> Fix header focus outline in ag-grid theme

- packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
- packages/ag-grid-theme/stories/dependencies/dataGridExampleColumnsColoration.ts
- updating to v28 broke selected row hover border color
- fix numeric alignment in one outstanding story
> [ag-grid-theme] QA fixes

- .changeset/tall-paws-judge.md
> Add changeset for #1017

- .changeset/wise-pumas-travel.md
- packages/grid/src/__tests__/__e2e__/Grid.cy.tsx
- packages/grid/src/internal/TableRow.tsx
This used to be on the grid but was accidentally deleted at some point, probably in a conflict resolution. 
Closes #1067
> [Data Grid] Add aria-selected to selected rows

- .changeset/two-pans-tell.md
- packages/core/src/panel/Panel.css
Primary variant was using secondary token
> Fix Panel primary variant background 

- packages/core/stories/split-layout.doc.stories.mdx
Updates from feedback 
https://github.com/jpmorganchase/salt-ds/issues/1128#issuecomment-1425869688
> Update SplitLayout docs from feedback

- .storybook/styles.css
- packages/core/src/card/Card.css
- packages/core/stories/card.doc.stories.mdx
- packages/core/stories/card.stories.tsx
- packages/theme/stories/characteristics/characteristics.stories.css
- packages/theme/stories/characteristics/characteristics.stories.mdx
- Fixes sbdocs custom theming overriding Salt styles in SB
- Aligns CSS tokens with convention (i.e. how Button does it)
- Uses Text component in examples
> Card component doc and styling improvements

- packages/core/src/spinner/Spinner.tsx
- packages/core/src/spinner/svgSpinners/SpinnerSVG.tsx
> Fix TS error in Spinner

- mosaic-site/package.json
- mosaic-site/src/layouts/DetailTechnical/DetailTechnical.tsx
- mosaic-site/src/pages/_app.tsx
- yarn.lock
- This is to fix a few bugs including mdx tables not rendering properly
- It also adds site search functionality that we can hide for now when we work on `AppHeader`
> Upgrade mosaic to the latest version

- site/docs/components/_content-template/index.mdx
> Update component document template

- README.md
The README of this project does not list direct links to the NPM package sources.
This PR formats README to include high-level heading for the Salt Design System package and also adds badges to NPM package sources. This way it makes it more developer friendly (especially for first time visitors).
Eager to hear thoughts on this PR.
Thanks!
> Update the README to include badges and a heading

- .changeset/loud-frogs-study.md
- packages/theme/css/foundations/size.css
- packages/theme/stories/foundations/size.stories.mdx
Renamed `--salt-size-selection` to `--salt-size-selectable`
> Change size-selection to size-selectable

- packages/grid/stories/grid.stories.css
The colors in grid.stories.css have been updated to use `status` and `accent` colors
> Use characteristic colors in grid.stories.css

- packages/lab/stories/tabs/tabs.doc.stories.mdx
- one liner fix for `Tabs` story
> fix tabs story

- mosaic-site/src/components/components/components-list.tsx
- site/docs/components/_index/components-list.tsx
Update components list on current and mosaic sites
> Update components list

- mosaic-site/docs/index.mdx
- mosaic-site/snapshots/latest/local/index.mdx
- mosaic-site/snapshots/latest/local/shared-config.json
- mosaic-site/src/components/app-header/AppHeader.module.css
- mosaic-site/src/css/index.css
- mosaic-site/src/css/navbar/index.css
- mosaic-site/src/css/navbar/navbar-sidebar.css
Add styling overrides to mobile nav so it matches the current site
> Customise mobile nav 

- packages/core/src/panel/Panel.tsx
- packages/core/stories/panel/panel.doc.stories.mdx
- packages/core/stories/panel/panel.stories.tsx
Very minor changes to docs and storybook
> Minor Panel changes

- packages/lab/src/checkbox/CheckboxIcon.css
This PR aims to update the characteristics tokens used within Checkbox to match the spec.
> updated tokens used for CSS in Checkbox

- .storybook/preview.tsx
- docs/public/mockServiceWorker.js
- package.json
- packages/grid/stories/dummyData.ts
- packages/grid/stories/grid-serverSideData.stories.tsx
- packages/grid/stories/grid-sortColumns.stories.tsx
- packages/grid/stories/grid.doc.stories.mdx
- yarn.lock
This builds on that PR and uses msw to mock the API so it looks more like how a user would use a server.
> Use MSW for server side grid examples

- .changeset/violet-walls-act.md
- packages/core/src/link/Link.tsx
- packages/core/stories/link/link.doc.stories.mdx
- packages/core/stories/link/link.stories.tsx
Make easier to hide icon in external links by changing types
> Make easier to hide icon in external links

- mosaic-site/docs/components/index.mdx
- mosaic-site/docs/getting-started/designing.mdx
- mosaic-site/docs/getting-started/developing.mdx
- mosaic-site/docs/getting-started/index.mdx
- mosaic-site/docs/getting-started/roadmap.mdx
- mosaic-site/docs/support-and-contributions/index.mdx
- mosaic-site/mosaic.config.js
- mosaic-site/snapshots/latest/salt/components/index.mdx
- mosaic-site/snapshots/latest/salt/getting-started/designing.mdx
- mosaic-site/snapshots/latest/salt/getting-started/developing.mdx
- mosaic-site/snapshots/latest/salt/getting-started/index.mdx
- mosaic-site/snapshots/latest/salt/getting-started/roadmap.mdx
- mosaic-site/snapshots/latest/salt/index.mdx
- mosaic-site/snapshots/latest/salt/support-and-contributions/index.mdx
- Remove empty `[]` breadcrumbs from docs
- Disable breadcrumbs plugin
- Update snapshots
> Disable breadcrumbs plugin on the site

- packages/core/stories/card/card.doc.stories.mdx
When to use Card guidance added to docs
> When to use Card guidance

- packages/grid/package.json
This PR moves grid to an alpha and changes the dist tag to next too
> Fix grid version

- mosaic-site/package.json
- mosaic-site/src/css/theme/theme.css
- mosaic-site/src/pages/_app.tsx
- mosaic-site/src/pages/_document.tsx
- yarn.lock
Our site loads quite slow atm. Looking at our core vitals the font loading is flagged. This uses next/font to see if it speeds up load.
Mobile Before:
Mobile After:
> Use next/font

- .changeset/mighty-donuts-wave.md
- .changeset/sweet-shrimps-allow.md
- package.json
- packages/core/src/tooltip/Tooltip.tsx
- packages/core/src/tooltip/useTooltip.ts
- packages/core/src/utils/index.ts
- packages/core/src/utils/mergeProps.ts
- packages/core/stories/tooltip/tooltip.qa.stories.tsx
- packages/lab/src/cascading-menu/CascadingMenuList.tsx
- packages/lab/src/combo-box-deprecated/internal/DefaultComboBox.tsx
- packages/lab/src/combo-box-deprecated/internal/MultiSelectComboBox.tsx
- packages/lab/src/dropdown/DropdownBase.tsx
- packages/lab/src/overlay/useOverlay.ts
- packages/lab/src/query-input/internal/ValueSelector.tsx
- yarn.lock
> Render Tooltip in a portal to avoid it being cut off

- site/src/pages/_document.tsx
My previous PR that fixed font removed the lang attribute on the HTML element. This add it back
> Re-add lang attribute on site

- .changeset/afraid-elephants-pretend.md
- .github/workflows/chromatic.yml
- .github/workflows/release.yml
- .github/workflows/storybook-preview.yml
- .prettierignore
- .storybook/preview.tsx
- docs/public/mockServiceWorker.js
- package.json
- packages/grid/src/ColumnSortContext.ts
- packages/grid/src/Grid.tsx
- packages/grid/src/GridColumn.tsx
- packages/grid/src/HeaderCell.css
- packages/grid/src/HeaderCell.tsx
- packages/grid/src/RowSelectionCheckboxColumn.tsx
- packages/grid/src/RowSelectionRadioColumn.tsx
- packages/grid/src/__tests__/__e2e__/Grid.cy.tsx
- packages/grid/stories/dummyData.ts
- packages/grid/stories/grid-cellCustomization.stories.tsx
- packages/grid/stories/grid-editableCells.stories.tsx
- packages/grid/stories/grid-pagination.stories.tsx
- packages/grid/stories/grid-rowSelectionModes.stories.tsx
- packages/grid/stories/grid-serverSideData.stories.tsx
- packages/grid/stories/grid-sortColumns.stories.tsx
- packages/grid/stories/grid.doc.stories.mdx
- packages/grid/stories/grid.stories.tsx
- packages/grid/stories/utils.ts
- yarn.lock
#1010
1) values from GridColumn `getValue` prop
2) values from `rowData`
3) custom sorting function
4) server side sorting using `onSortOrderChange `
story/data-grid-data-grid--server-side-sort
story/data-grid-data-grid--client-side-sort
Design approved by Darrin
Content reviewed by Sion
_[WIP] ADA to be reviewed by Stella_
> [Data Grid] implement sorting on grid columns

- packages/theme/stories/characteristics/accent.stories.mdx
- packages/theme/stories/characteristics/text.stories.mdx
- packages/theme/stories/foundations/color.stories.mdx
- packages/theme/stories/foundations/size.stories.mdx
- packages/theme/stories/palettes/error.stories.mdx
- packages/theme/stories/palettes/info.stories.mdx
- packages/theme/stories/palettes/success.stories.mdx
- packages/theme/stories/palettes/warning.stories.mdx
Missing tokens added plus restructuring of some stories which made the IA wonky
> Add missing tokens to docs

- packages/core/stories/spinner/spinner.doc.stories.mdx
- packages/core/stories/spinner/spinner.stories.tsx
Improved documentation for Spinner component
> Update Spinner docs and examples

- .changeset/dull-boxes-listen.md
Adds the changesets for #1038 and #1237
> Add missing Data Grid changeset

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
Adds npm package provenance https://github.blog/2023-04-19-introducing-npm-package-provenance/
> Use provenance when publishing

- packages/core/stories/checkbox/checkbox.doc.stories.mdx
> Fix story links in Checkbox

- packages/lab/stories/input-next/input-next.stories.tsx
Add controlled Input example story to InputNext
> Add controlled Input example story

- .changeset/funny-onions-build.md
- packages/lab/src/input-next/InputNext.css
- packages/lab/src/input-next/InputNext.tsx
- packages/lab/stories/input-next/input-next.stories.tsx
V1 of FormFieldNext includes **static** InputNext adornments.
> Input Static adornments

- .yarn/patches/modular-scripts-npm-3.4.0-8cdb747f13.patch
- yarn.lock
> Include caret when including local dependencies during build

- .changeset/brown-sloths-change.md
- packages/lab/src/tabs/TabActivationIndicator.tsx
- packages/lab/src/tabs/TabsTypes.ts
- packages/lab/src/tabs/Tabstrip.tsx
- packages/lab/src/tabs/useActivationIndicator.ts
- packages/lab/src/tabs/useKeyboardNavigation.ts
- packages/lab/src/tabs/useSelection.ts
- packages/lab/src/tabs/useTabs.ts
- packages/lab/src/tabs/useTabstrip.ts
- packages/lab/stories/tabstrip/tabstrip.stories.tsx
> Support Tabstrip  `activeTabIndex` to be null

- packages/styles/stories/introduction.stories.mdx
- packages/theme/stories/introduction.stories.mdx
Added documentation regarding the new style injection system
> Desktop support documentation

- .changeset/mighty-camels-sparkle.md
- packages/ag-grid-theme/css/_salt-ag-theme-icon-font.scss
- packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
- packages/ag-grid-theme/css/_uitk-ag-theme-icon-font.scss
- packages/ag-grid-theme/css/_uitk-ag-theme-mixin.scss
- packages/ag-grid-theme/css/uitk-ag-theme.scss
> Fix the ag-grid theme menu

- packages/lab/src/list-next/ListItemNext.css
- packages/lab/src/list-next/ListItemNext.tsx
- packages/lab/src/list-next/ListNext.css
- packages/lab/src/list-next/ListNext.tsx
- packages/lab/src/list-next/useList.ts
- packages/lab/stories/list-next/list.stories.tsx
cleaning hook and leaving comments on things we need to keep tabs on
> List next clean and comment hook

- packages/core/package.json
- packages/countries/package.json
- packages/data-grid/package.json
- packages/icons/package.json
- packages/lab/package.json
- packages/lab/src/list/VirtualizedList.tsx
- packages/lab/src/progress/CircularProgress/CircularProgressParts.tsx
- packages/lab/src/query-input/internal/SearchList.tsx
- packages/lab/src/slider/internal/SliderHandle.tsx
- packages/lab/src/slider/internal/SliderMarkLabels.tsx
- packages/lab/src/slider/internal/SliderRail.tsx
- packages/lab/src/slider/internal/SliderRailMarks.tsx
- packages/lab/src/slider/internal/SliderSelection.tsx
- packages/lab/src/window/ElectronWindow.tsx
Need to investigate how these were missed
> Fix missed CSS imports

- .changeset/sixty-dolls-pretend.md
- packages/theme/css/foundations/delay.css
- packages/theme/css/foundations/duration.css
- packages/theme/stories/foundations/delay.stories.mdx
- packages/theme/stories/foundations/duration.stories.mdx
The values were missing the units
> Fix the duration foundation tokens having invalid values

- .changeset/fresh-pigs-warn.md
- .changeset/lovely-waves-cross.md
missed for #1747 
updated for #1745
> Add/update changeset for Input changes

- packages/core/stories/form-field/form-field.doc.stories.mdx
- packages/core/stories/form-field/form-field.stories.tsx
- packages/core/stories/input/input.doc.stories.mdx
Improved documentation and doc fixes for new features
> Improve docs for Input/FF v2 features

- packages/lab/src/__tests__/__e2e__/list-next/ListNext.cy.tsx
- packages/lab/src/list-next/useList.ts
- packages/lab/stories/list-next/list.stories.tsx
add cypress test for controlled single select list example
> Controlled tests

- packages/lab/stories/form-field-legacy/form-field.doc.stories.mdx
- packages/lab/stories/input-legacy/input-legacy.doc.stories.mdx
> Fix links pointing to new components in docs

- site/docs/getting-started/roadmap.mdx
Adds details of which foundation pages we intend to deliver in Q2 & Q3 to the roadmap page
> Adds foundation page work to roadmap

- yarn.lock
Closes https://github.com/jpmorganchase/salt-ds/security/dependabot/69
> Fix fast-xml-parser vulnerability

- .changeset/fair-plums-crash.md
- packages/core/src/checkbox/Checkbox.css
- packages/core/src/checkbox/CheckboxGroup.css
- packages/core/src/radio-button/RadioButton.css
- packages/core/src/radio-button/RadioButtonGroup.css
Increased spacing between Checkbox/Radio Button and value, and spacing between each when horizontally grouped
> Increase spacing on Checkbox/RadioButton

- .changeset/khaki-tigers-battle.md
- packages/core/src/checkbox/Checkbox.tsx
- packages/core/src/checkbox/CheckboxIcon.css
- packages/core/stories/checkbox/checkbox.doc.stories.mdx
- packages/core/stories/checkbox/checkbox.stories.tsx
- packages/theme/css/characteristics/status.css
Removes styles of disabled error in Checkbox [RadioButton will follow #1817 ]
Puts disabled > error in logic
> Remove error disabled styling variant in Checkbox

- .changeset/wild-ligers-argue.md
- packages/lab/src/dialog/DialogTitle.css
- packages/lab/src/dialog/DialogTitle.tsx
Closes #1800 
title was missing a line height
> Fixed issue where the Dialog heading overlapped when wrapped

- .changeset/plenty-mangos-tan.md
- packages/core/src/checkbox/Checkbox.tsx
- packages/core/src/checkbox/CheckboxGroup.tsx
- packages/core/src/checkbox/internal/CheckboxGroupContext.ts
- packages/core/src/radio-button/RadioButton.tsx
- packages/core/src/radio-button/RadioButtonGroup.tsx
- packages/core/src/radio-button/internal/RadioGroupContext.tsx
- packages/core/stories/form-field/form-field.stories.tsx
Checkbox and RadioButton integration with FF full support
Part of V2 Form Field features
**PENDING**: Warning and Readonly support (features missing & both needed in CB/RB)
> [Form Field v2] Checkbox and Radiobutton support

- .changeset/late-lemons-thank.md
- packages/theme/css/characteristics/selectable.css
- packages/theme/css/foundations/fade.css
- packages/theme/css/foundations/palette.css
- packages/theme/stories/characteristics/selectable.stories.mdx
- packages/theme/stories/palettes/interact.stories.mdx
new tokens for selected disabled
> Add selectedDisabled background token to selectable

- .changeset/yellow-toys-rescue.md
- packages/theme/css/characteristics/selectable.css
- packages/theme/stories/characteristics/selectable.stories.mdx
> Add --salt-selectable-cursor-readonly

- packages/ag-grid-theme/package.json
- packages/core/package.json
- packages/countries/package.json
- packages/data-grid/package.json
- packages/icons/package.json
- packages/lab/package.json
- packages/styles/package.json
- packages/theme/package.json
- packages/window/package.json
The env variable wasn't working by itself so hopefully adding it to the publishConfig helps
> Publish with provenance

- packages/data-grid/src/__tests__/__e2e__/Grid.cy.tsx
- packages/lab/src/__tests__/__e2e__/query-input/QueryInput.cy.tsx
fixes https://github.com/jpmorganchase/salt-ds/issues/1694
> skip unstable tests

- .changeset/empty-hounds-approve.md
- packages/core/src/__tests__/__e2e__/form-field/FormField.cy.tsx
- packages/core/src/__tests__/__e2e__/input/Input.cy.tsx
- packages/core/src/form-field-context/FormFieldContext.ts
- packages/core/src/form-field/FormField.tsx
- packages/core/src/form-field/FormFieldLabel.css
- packages/core/src/form-field/FormFieldLabel.tsx
- packages/core/src/input/Input.tsx
- packages/core/stories/form-field/form-field.stories.tsx
Adds necessity prop to FormFieldLabel component
> [FormField v3] Necessity label

- .changeset/tame-foxes-grab.md
- packages/theme/css/characteristics/status.css
- packages/theme/css/foundations/palette.css
- packages/theme/stories/characteristics/status.stories.mdx
- packages/theme/stories/palettes/error.stories.mdx
- packages/theme/stories/palettes/info.stories.mdx
- packages/theme/stories/palettes/negative.stories.mdx
- packages/theme/stories/palettes/static.stories.mdx
- packages/theme/stories/palettes/success.stories.mdx
- packages/theme/stories/palettes/warning.stories.mdx
Missing docs for static and some other status tokens
Deprecated tokens that are no longer used due to recent updates
> Deprecate unused status tokens and add missing docs

- .changeset/tame-foxes-grab.md
- packages/core/CHANGELOG.md
- packages/lab/CHANGELOG.md
- packages/theme/CHANGELOG.md
- packages/theme/css/foundations/palette.css
- packages/theme/stories/characteristics/editable.stories.mdx
- packages/theme/stories/characteristics/measured.stories.mdx
- packages/theme/stories/characteristics/status.stories.mdx
- packages/theme/stories/palettes/error.stories.mdx
- packages/theme/stories/palettes/info.stories.mdx
- packages/theme/stories/palettes/negative.stories.mdx
- packages/theme/stories/palettes/positive.stories.mdx
- packages/theme/stories/palettes/static.stories.mdx
- packages/theme/stories/palettes/success.stories.mdx
- packages/theme/stories/palettes/warning.stories.mdx
Uses the previous hex value rather than N/A
> Change replacement token in docs to hex values

- .changeset/blue-falcons-sing.md
- .changeset/happy-panthers-fry.md
- packages/data-grid/src/DropdownCellEditor.tsx
- packages/data-grid/src/__tests__/__e2e__/Grid.cy.tsx
- packages/lab/src/__tests__/__e2e__/dropdown/Dropdown.cy.tsx
- packages/lab/src/dropdown/Dropdown.tsx
- packages/lab/src/dropdown/useDropdown.ts
> Fix Dropdown same option selection issue

- .changeset/dry-timers-build.md
- packages/core/src/button/Button.css
- packages/lab/src/pill/Pill.css
- packages/lab/src/toggle-button/ToggleButton.css
- packages/lab/src/toolbar/ToolbarButton.css
A requirement from design where Button and Toggle Button need to have a fixed gap of spacing-50 between the icon and text
> Update Toggle Button and Button to have a fixed icon gap

- .changeset/tiny-trains-ring.md
- packages/lab/src/list-next/ListItemNext.css
removes unneeded transition in list item next
> Removed unnecessary transition in List Item Next

- .changeset/dry-actors-warn.md
- packages/core/src/input/Input.css
- packages/core/stories/input/input.stories.tsx
Fixes placeholder styling and activation indicator width on readonly variant in Input component
> Input styling fixes

- .changeset/fresh-planets-talk.md
- packages/core/src/form-field/FormFieldLabel.css
- packages/core/src/form-field/FormFieldLabel.tsx
- packages/core/stories/form-field/form-field.doc.stories.mdx
- packages/core/stories/form-field/form-field.stories.tsx
- site/docs/patterns/index.mdx
> Change pronounced prop to intent in FormFieldLabel

- .changeset/sixty-squids-explain.md
- packages/core/stories/form-field/form-field.stories.tsx
- packages/lab/src/multiline-input/MultilineInput.css
- packages/lab/src/multiline-input/MultilineInput.tsx
- packages/lab/stories/multiline-input/multiline-input.stories.tsx
Fixed alignment styling of adornments in MultilineInput
Fixed left padding of Multiline when readonly with and without a full border
Fixed height of textarea fixed to number of rows
> Minor design and story fixes for Multiline Input

- tooling/stylelint/custom-property-starts-with-component-name/index.js
Getting CSS files was previously done by using a predefined set of directories and recursively going through all of the nested folders. This replaces that method with a file glob and fixes the linting on Windows
> Fix stylelint on Windows

- .changeset/breezy-rabbits-carry.md
- packages/core/src/button/Button.css
> Remove "user-select:none" from Button

- packages/ag-grid-theme/stories/ag-grid.doc.stories.mdx
> Fix AG Grid theme package install instructions

- packages/core/stories/multiline-input/multiline-input.doc.stories.mdx
> Fix Multiline Input character count story not showing on the documentation page

- .changeset/lazy-ties-own.md
- packages/core/src/form-field/FormFieldHelperText.css
https://github.com/jpmorganchase/salt-ds/issues/2070
> Fix spacing between status icon and helper text in Form Field

- packages/core/stories/drawer/drawer.doc.stories.mdx
Render Drawer stories in Storybook docs on an iframe instead of inline
> Fix `Drawer` docs 

- .changeset/stupid-lions-swim.md
- packages/lab/src/stepped-tracker/SteppedTracker.css
- packages/lab/src/stepped-tracker/TrackerConnector/TrackerConnector.css
- packages/lab/src/stepped-tracker/TrackerStep/TrackerStep.css
- packages/lab/stories/stepped-tracker/stepped-tracker.stories.tsx
Small fix to spacing calculations in SteppedTracker which meant connector was slightly off-center
> Fix Stepped Tracker spacing

- .changeset/forty-insects-jog.md
- packages/core/src/checkbox/Checkbox.css
- packages/core/src/checkbox/CheckboxIcon.css
- packages/core/src/radio-button/RadioButton.css
- packages/core/src/radio-button/RadioButtonIcon.css
Removes selected hover states from Checkbox and Radio Button. Missed from #1952
> Remove selected hover styles from Checkbox and Radio Button

- .changeset/neat-mice-try.md
Add missing changeset for #2077
> Add missing changeset for 2077

- .changeset/sharp-drinks-listen.md
- packages/core/src/checkbox/Checkbox.css
- packages/core/src/radio-button/RadioButton.css
Fixes [issue 2145](https://github.com/jpmorganchase/salt-ds/issues/2145)
> Fix svg positioning bug when used as icon

- packages/lab/stories/dropdown-next/dropdown-next.doc.stories.mdx
- docs updated post review by @sion-docs
> DropdownNext V1: docs updated post content team review

- .changeset/polite-dryers-boil.md
- packages/theme/css/deprecated/foundations.css
- packages/theme/css/foundations/zindex.css
> Deprecate `--salt-zIndex-docked`

- .changeset/silent-chicken-drive.md
- packages/lab/src/__tests__/__e2e__/combo-box-next/ComboBoxNext.cy.tsx
- packages/lab/src/combo-box-next/ComboBoxNext.css
- packages/lab/src/combo-box-next/ComboBoxNext.tsx
- packages/lab/src/combo-box-next/utils.tsx
- packages/lab/stories/combo-box-next/combo-box-next.stories.tsx
- packages/lab/stories/dropdown-next/dropdown-next.doc.stories.mdx
Splitting https://github.com/jpmorganchase/salt-ds/pull/2181#issue-1846550676
into more contained changes.
in this PR:
- enable commented test, 
- tweaks from design 
- change `itemRenderer` for `ListItem`
> Combobox itemRenderer for ListItem

- packages/lab/src/__tests__/__e2e__/combo-box-next/ComboBoxNext.cy.tsx
- packages/lab/src/combo-box-next/ComboBoxNext.tsx
- packages/lab/src/combo-box-next/useComboboxPortal.ts
- packages/lab/src/combo-box-next/utils.tsx
- packages/lab/stories/combo-box-next/combo-box-next.stories.tsx
Splitting https://github.com/jpmorganchase/salt-ds/pull/2181#issue-1846550676
into more contained changes.
in this PR:
combobox
- add types for ListItem
- add controlled to `open`
> update Combobox types and add controlled to open

- .changeset/proud-ducks-swim.md
- packages/lab/src/__tests__/__e2e__/combo-box-next/ComboBoxNext.cy.tsx
- packages/lab/src/combo-box-next/ComboBoxNext.tsx
- packages/lab/src/combo-box-next/useComboBox.tsx
- packages/lab/stories/combo-box-next/combo-box-next.doc.stories.mdx
- packages/lab/stories/combo-box-next/combo-box-next.stories.tsx
Last split of https://github.com/jpmorganchase/salt-ds/pull/2181
Changes to Combo Box:
- Fix controlled implementation.
- Removed `InputProps`.
- Added `onListChange` and `onSelect` props.
> Combo Box controlled

- site/docs/components/salt-provider/accessibility.mdx
- site/docs/components/salt-provider/examples.mdx
- site/docs/components/salt-provider/index.mdx
- site/docs/components/salt-provider/usage.mdx
- site/src/examples/salt-provider/Breakpoints.tsx
- site/src/examples/salt-provider/Density.module.css
- site/src/examples/salt-provider/Density.tsx
- site/src/examples/salt-provider/Modes.tsx
- site/src/examples/salt-provider/NestedProviders.module.css
- site/src/examples/salt-provider/NestedProviders.tsx
- site/src/examples/salt-provider/Theme.tsx
- site/src/examples/salt-provider/index.ts
> Add Salt Provider documentation

- site/src/examples/accordion/InlineBadge.tsx
https://saltdesignsystem-git-accordion-docs-fed-team.vercel.app/salt/components/accordion/examples#inline-badge
> Inline Badge Accordion example fix

- site/docs/components/form-field/usage.mdx
> Remove form field usage from sidebar

- .changeset/empty-pumpkins-shout.md
- packages/core/src/status-indicator/StatusIndicator.css
- site/docs/components/status-indicator/accessibility.mdx
- site/docs/components/status-indicator/examples.mdx
- site/docs/components/status-indicator/index.mdx
- site/docs/components/status-indicator/usage.mdx
- site/src/examples/status-indicator/Labelling.tsx
- site/src/examples/status-indicator/Size.tsx
- site/src/examples/status-indicator/Status.tsx
- site/src/examples/status-indicator/index.ts
> Status indicator docs

- site/docs/components/spinner/accessibility.mdx
- site/docs/components/spinner/examples.mdx
- site/docs/components/spinner/index.mdx
- site/docs/components/spinner/usage.mdx
- site/src/examples/spinner/Loading.tsx
- site/src/examples/spinner/LoadingPartial.module.css
- site/src/examples/spinner/LoadingPartial.tsx
- site/src/examples/spinner/Size.tsx
- site/src/examples/spinner/SizeDefault.tsx
- site/src/examples/spinner/SizeLarge.tsx
- site/src/examples/spinner/index.ts
> Spinner docs

- site/docs/components/country-symbol/accessibility.mdx
- site/docs/components/country-symbol/examples.mdx
- site/docs/components/country-symbol/index.mdx
- site/docs/components/country-symbol/usage.mdx
- site/propsGen.js
- site/src/examples/country-symbol/AllCountrySymbols.tsx
- site/src/examples/country-symbol/BasicUsage.tsx
- site/src/examples/country-symbol/LazyLoading.tsx
- site/src/examples/country-symbol/Size.tsx
- site/src/examples/country-symbol/index.ts
> Country symbol docs

- site/src/examples/multiline-input/ValidationStatus.tsx
Fix MultilineInput validation example
currenltly wrong
https://saltdesignsystem-git-accordion-docs-fed-team.vercel.app/salt/components/multiline-input/examples
> Fix MultilineInput validation example

- site/docs/components/card/accessibility.mdx
- site/docs/components/card/examples.mdx
- site/docs/components/card/usage.mdx
Some content changes agreed in the Word doc for Card
> Updates to Cards docs

- site/docs/components/text/accessibility.mdx
- site/docs/components/text/examples.mdx
- site/docs/components/text/index.mdx
- site/docs/components/text/usage.mdx
- site/src/examples/text/Styles.tsx
- site/src/examples/text/Styling.tsx
- site/src/examples/text/Truncation.tsx
- site/src/examples/text/Variant.tsx
- site/src/examples/text/index.ts
> Add Text documentation to the site

- .changeset/funny-ways-argue.md
- packages/lab/src/__tests__/__e2e__/dropdown-next/DropdownNext.cy.tsx
- packages/lab/src/dropdown-next/DropdownNext.tsx
- packages/lab/stories/dropdown-next/dropdown-next.stories.tsx
- site/src/examples/dropdown/Default.tsx
- site/src/examples/dropdown/DefaultSelected.tsx
closes #2371 
Dropdown has no onChange/onSelect so you can't access the selected item when using it. This PR adds onSelect.
> Add onSelect prop to DropdownNext

- .eslintrc.js
Reduce eslint error [from](https://github.com/jpmorganchase/salt-ds/actions/runs/6188247284/job/16799838569) 
> ✖ 4959 problems (4872 errors, 87 warnings)
Down to
> ✖ 1915 problems (1828 errors, 87 warnings)
> Fix unable to resolve path eslint error

- .changeset/fresh-planes-add.md
- packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
Fixes alignment with below cell text
> AG grid theme floating filter input text alignment

- packages/core/src/utils/useFloatingUI/README.md
- packages/core/src/utils/useFloatingUI/index.ts
- packages/core/src/utils/useFloatingUI/useFloatingUI.tsx
Added a ReadMe for the floating UI desktop work.
Also fixed a few linting issues at the same time
> add readme for floating component guidance

- .storybook/main.ts
code panel was lost during v7 upgrade
> Adds back storybook addon-storysource

- .changeset/perfect-beans-search.md
- packages/core/src/flex-layout/FlexLayout.css
- packages/core/src/stack-layout/StackLayout.css
remove smaller gap for flex layout touch
> Stack layout touch gap

- packages/core/stories/toggle-button-group/toggle-button-group.doc.stories.mdx
- packages/lab/stories/combo-box-next/combo-box-next.doc.stories.mdx
- packages/lab/stories/tabs/tabs.doc.stories.mdx
- packages/lab/stories/toast-group/toast-group.doc.stories.mdx
fix broken stories in storybook for toggle button group, tabs, combobox, and toast group
> Fix broken stories

- packages/ag-grid-theme/stories/ag-grid.doc.stories.mdx
- site/src/components/components/components-list.tsx
Links to storybook docs from https://www.saltdesignsystem.com/salt/components/index are broken
> Fix site doc links

- .changeset/cuddly-kiwis-attack.md
- .changeset/witty-kings-search.md
- packages/lab/src/progress/CircularProgress/CircularProgress.css
- packages/lab/src/progress/CircularProgress/CircularProgress.tsx
- packages/lab/src/progress/Info.tsx
- packages/lab/src/progress/LinearProgress/LinearProgress.css
- packages/lab/src/progress/LinearProgress/LinearProgress.tsx
- packages/lab/stories/progress/circular-progress.stories.tsx
- packages/lab/stories/progress/linear-progress.stories.tsx
- packages/lab/stories/progress/progress.qa.stories.tsx
- packages/theme/css/foundations/size.css
- tooling/stylelint/correct-theme-token-usage/index.js
closes #1872
preview: https://18c300e1.saltdesignsystem-storybook.pages.dev/?path=/docs/documentation-core-accordion--docs
> Progress 2

- site/src/layouts/DetailPattern/Resources.tsx
We need to add a link to a github resource in navigation pattern, but the current implementation adds the figma link by default.
> add github link type to pattern resources

- site/docs/components/navigation-item/examples.mdx
Preview at https://saltdesignsystem-git-navigation-item-docs-fed-team.vercel.app/salt/components/navigation-item/examples
> Update navigation item vertical nested group example copy

- .changeset/short-moons-tickle.md
- packages/core/stories/switch/switch.doc.stories.mdx
- site/docs/components/switch/index.mdx
- site/docs/components/switch/usage.mdx
- site/src/components/components/components-list.tsx
> Switch: fix import and component-list update

- .changeset/small-cycles-fold.md
- packages/lab/src/combo-box-next/utils.tsx
> Fix missing forwardedRef on `DefaultListItem`

- .changeset/dry-squids-confess.md
- packages/ag-grid-theme/css/_salt-ag-theme-default-params.scss
Closes https://github.com/jpmorganchase/salt-ds/issues/2651
> [Ag Grid Theme] Set tooltip background color

- packages/lab/stories/pill-next/pill-next.stories.tsx
- site/docs/components/pill/accessibility.mdx
- site/docs/components/pill/examples.mdx
- site/src/examples/pill/Closable.tsx
- site/src/examples/pill/index.ts
to follow https://github.com/jpmorganchase/salt-ds/pull/2641
> add docs and example for closable pill

- site/docs/components/stepped-tracker/index.mdx
Stepped tracker page should have lab label and 🚧
https://www.saltdesignsystem.com/salt/components/stepped-tracker/examples
Preview
https://saltdesignsystem-git-stepped-tracker-doc-to-lab-fed-team.vercel.app/salt/components/index
> Update stepped track doc to be in lab

- packages/lab/stories/tabstrip-next/tabstrip-next.stories.tsx
- site/docs/components/tabs/accessibility.mdx
- site/docs/components/tabs/examples.mdx
- site/docs/components/tabs/index.mdx
- site/docs/components/tabs/usage.mdx
- site/src/examples/tabs/Inline.tsx
- site/src/examples/tabs/MainTabstrip.tsx
- site/src/examples/tabs/WithBadge.tsx
- site/src/examples/tabs/WithIcon.tsx
- site/src/examples/tabs/index.ts
> Tabs Site Docs

- .changeset/stupid-suits-switch.md
- packages/lab/src/tabs-next/TabNext.css
> Inline Tab Height

- site/docs/patterns/international-address-input.mdx
- site/docs/patterns/international-phone-number-input.mdx
the link to Figma in the page International phone Number Input should be removed for now as the templates are not provided
> remove resources for International phone Number Input

- .changeset/bright-masks-learn.md
- packages/lab/src/badge/Badge.css
- packages/lab/stories/badge/badge.stories.tsx
> Fixed Badge occupying space when it is anchored to a child component

- .changeset/tall-crabs-attend.md
- packages/core/src/card/Card.css
- packages/core/src/card/Card.tsx
- packages/core/src/card/InteractableCard.css
- packages/core/src/card/InteractableCard.tsx
- packages/core/stories/card/card.qa.stories.tsx
- site/docs/components/card/examples.mdx
- site/src/examples/card/Secondary.tsx
- site/src/examples/card/SecondaryInteractableCard.tsx
- site/src/examples/card/index.ts
> Card Secondary Variant

- packages/core/stories/form-field/form-field.doc.stories.mdx
- packages/lab/stories/pill-next/pill-next.doc.stories.mdx
- packages/lab/stories/pill/pill.doc.stories.mdx
A few links are broken in Storybook, this PR fixes them.
> Fix Storybook links

- .changeset/chilly-cherries-build.md
- packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
closes https://github.com/jpmorganchase/salt-ds/issues/2755
> Remove override style for pinned column's text

- .changeset/happy-turkeys-rule.md
- .changeset/warm-bulldogs-type.md
- packages/core/CHANGELOG.md
- packages/lab/CHANGELOG.md
I'll update the release notes after.
> Add icons changeset and update changelogs

- packages/core/stories/input/input.qa.stories.tsx
- packages/core/stories/multiline-input/multiline-input.qa.stories.tsx
> Add QA stories for Input and Multiline Input text button adornments

- .changeset/hip-taxis-wonder.md
- packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
- packages/ag-grid-theme/stories/examples/Default.tsx
Closes https://github.com/jpmorganchase/salt-ds/issues/2783
> Fix border misalignment on range selection when a single column or a single row is selected

- site/src/components/components/ExamplesListView.tsx
> Add default example on page load

- .changeset/sweet-rules-dream.md
- packages/core/src/input/Input.css
- packages/core/src/multiline-input/MultilineInput.css
> Fix Button Input adornment style overrides

- .changeset/moody-hornets-sleep.md
- packages/core/src/badge/Badge.css
This is revealed when badge (from navigation bar) appears on top of dialog
Reproduce: https://stackblitz.com/edit/salt-template-cjahgn?file=App.tsx
> Update Badge's z-index

- .changeset/chatty-carpets-kick.md
This PR only adds a changeset as the fix is releasing the styles package and all the other packages.
> Fixed issue where components are not injecting their styles

- .changeset/strange-years-compare.md
- packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
This was a request from MTK. Discussed and agreed with @bhoppers2008 
MTK has tested and they're happy
> Update AG Grid theme header icon alignment 

- .github/ISSUE_TEMPLATE/bug_report.yml
User can't report bug on website
> Add website to bug report template

- .changeset/dull-games-yawn.md
- package.json
- packages/core/src/__tests__/__e2e__/checkbox/CheckboxGroup.cy.tsx
- packages/core/src/__tests__/__e2e__/radio-button/RadioButtonGroup.cy.tsx
- packages/core/src/checkbox/Checkbox.tsx
- packages/core/src/checkbox/CheckboxGroup.tsx
- packages/core/src/checkbox/internal/CheckboxGroupContext.ts
- packages/core/src/checkbox/internal/useCheckboxGroup.ts
- packages/core/src/radio-button/RadioButton.tsx
- packages/core/src/radio-button/RadioButtonGroup.tsx
- packages/core/src/radio-button/internal/RadioGroupContext.tsx
- yarn.lock
> Fix incorrect aria labelling of radio button and checkbox groups

- packages/core/stories/patterns/search/search.stories.tsx
> Add Search pattern examples

- site/docs/components/overlay/accessibility.mdx
- site/docs/components/overlay/examples.mdx
- site/docs/components/overlay/index.mdx
- site/docs/components/overlay/usage.mdx
- site/src/examples/overlay/Default.tsx
- site/src/examples/overlay/LongContent.tsx
- site/src/examples/overlay/Placement.tsx
- site/src/examples/overlay/WithActions.tsx
- site/src/examples/overlay/index.module.css
- site/src/examples/overlay/index.ts
closes #2807
documentation for #2735
> Overlay docs and examples on site

- packages/core/stories/patterns/contact-details/contact-details.stories.tsx
Updates to contact details pattern example data
> Contact detail pattern

- .changeset/funny-dolphins-jam.md
- packages/core/src/accordion/AccordionHeader.css
- packages/theme/css/global.css
> Fix disabled Accordions not showing a disabled cursor

- site/docs/components/overlay/accessibility.mdx
- site/docs/components/overlay/examples.mdx
- site/docs/components/overlay/index.mdx
- site/docs/components/overlay/usage.mdx
- site/src/examples/overlay/Default.tsx
- site/src/examples/overlay/LongContent.tsx
- site/src/examples/overlay/Placement.tsx
- site/src/examples/overlay/WithActions.tsx
- site/src/examples/overlay/index.module.css
- site/src/examples/overlay/index.ts
> add Overlay site docs and examples

- .changeset/clever-boats-fly.md
- packages/core/src/__tests__/__e2e__/salt-provider/SaltProvider.cy.tsx
- packages/core/src/salt-provider/SaltProvider.tsx
Closes #2841 
Updates the error detection logic so you can have a root provider in a new window.
> Improve the error detection logic in Salt Provider

- .changeset/slimy-dryers-occur.md
- packages/core/src/utils/useFloatingUI/useFloatingUI.tsx
- packages/lab/src/__tests__/__e2e__/combo-box-next/ComboBoxNext.cy.tsx
- packages/lab/src/__tests__/__e2e__/dropdown-next/DropdownNext.cy.tsx
- packages/lab/src/combo-box-next/ComboBoxNext.tsx
- packages/lab/src/combo-box-next/useComboBoxNext.tsx
- packages/lab/src/dropdown-next/DropdownNext.tsx
- packages/lab/src/list-control/ListControlContext.tsx
- packages/lab/src/list-control/ListControlState.ts
- packages/lab/src/option/Option.tsx
- packages/lab/src/option/OptionList.css
- packages/lab/stories/combo-box-next/combo-box-next.stories.tsx
- site/src/examples/combo-box/CustomFiltering.tsx
Refactored CB and DD to use floating-ui useInteractions. This keeps them consistent with other components and fixes items not being able to be selected in a desktop environment.
> Refactor CB and DD

- .changeset/sweet-dogs-sin.md
- packages/core/src/utils/useFloatingUI/useFloatingUI.tsx
- packages/lab/src/dialog/Dialog.tsx
- packages/lab/stories/dialog/dialog.stories.tsx
- site/docs/components/dialog/examples.mdx
- site/src/examples/dialog/CloseButton.tsx
- site/src/examples/dialog/Default.tsx
- site/src/examples/dialog/DisableScrim.tsx
- site/src/examples/dialog/Error.tsx
- site/src/examples/dialog/Info.tsx
- site/src/examples/dialog/MandatoryAction.tsx
- site/src/examples/dialog/Sizes.tsx
- site/src/examples/dialog/Success.tsx
- site/src/examples/dialog/Warning.tsx
- site/src/examples/dialog/WithoutAccent.tsx
- site/src/examples/dialog/index.ts
- Add disableScrim prop + examples 
- Fix useFloatingUI focus manager implementation
> refactor dialog + disable scrim prop

- site/src/examples/drawer/BottomDrawer.tsx
- site/src/examples/drawer/MandatoryAction.tsx
- site/src/examples/drawer/RightDrawer.tsx
- site/src/examples/drawer/TopDrawer.tsx
- Add aria-labelledby to Drawer examples that have a title
> Update examples with aria-labelled by

- .changeset/ninety-pumpkins-hug.md
- packages/core/src/toast/Toast.tsx
> Remove scrollIntoView from Toast

- cypress/support/component.ts
Makes the tests more consistent by resetting the mouse placement.
> Reset mouse on every test

- .changeset/five-apricots-jump.md
- .changeset/five-apricots-sit.md
- .changeset/five-apricots-stand.md
- docs/components/QAContainer.css
- packages/core/src/badge/Badge.css
- packages/core/src/card/Card.css
- packages/core/src/checkbox/Checkbox.css
- packages/core/src/checkbox/CheckboxIcon.css
- packages/core/src/file-drop-zone/FileDropZone.css
- packages/core/src/flex-layout/FlexLayout.css
- packages/core/src/input/Input.css
- packages/core/src/progress/CircularProgress/CircularProgress.css
- packages/core/src/progress/LinearProgress/LinearProgress.css
- packages/core/src/radio-button/RadioButton.css
- packages/core/src/switch/Switch.css
- packages/lab/src/dialog/Dialog.css
- packages/lab/src/dialog/DialogTitle.css
- packages/lab/src/drawer/Drawer.css
- packages/lab/src/form-field-legacy/FormLabel.css
- packages/lab/src/input-legacy/InputLegacy.css
- packages/lab/src/layer-layout/LayerLayout.css
- packages/lab/src/list/List.css
- packages/lab/src/option/Option.css
- packages/lab/src/option/OptionList.css
- packages/lab/src/tabs-next/TabNext.css
- packages/lab/src/tabs-next/TabstripNext.css
- packages/lab/src/tokenized-input-next/TokenizedInputNext.css
- packages/lab/src/tokenized-input/TokenizedInput.css
- packages/theme/css/global.css
The reset was causing issues in other applications. And retrospectively that reset doesn't fit with the other styles in the file which are assigning salt styles or the color-scheme.
> Remove box-sizing from the global.css and add it to the component CSS

- .changeset/serious-avocados-give.md
- packages/ag-grid-theme/css/salt-ag-theme.scss
> Grid header text use secondary color #3065

- .changeset/angry-houses-bake.md
- packages/core/src/link/Link.css
> Fix target _blank link icon alignment

- .changeset/tiny-hairs-itch.md
- packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
- packages/ag-grid-theme/stories/ag-grid.stories.tsx
- packages/ag-grid-theme/stories/examples/WrappedCell.tsx
- packages/ag-grid-theme/stories/examples/index.ts
> Fix ag grid theme wrapping cells

- .changeset/angry-donuts-enjoy.md
- packages/core/src/__tests__/__e2e__/tooltip/Tooltip.cy.tsx
- packages/core/src/tooltip/useTooltip.ts
fixes https://github.com/jpmorganchase/salt-ds/issues/3034
> Allow tooltip to flip direction when space is limited

- packages/lab/src/combo-box-next/ComboBoxNext.tsx
- packages/lab/src/dropdown-next/DropdownNext.tsx
- packages/lab/src/pill-input/PillInput.tsx
- packages/lab/src/pill-input/useTruncatePills.ts
This is purposely missing a changeset
> Clean up ComboBox and PillInput

- site/public/sitemap.xml
- site/src/components/mdx/index.ts
- site/src/components/mdx/link/A.module.css
- site/src/components/mdx/link/A.tsx
- site/src/components/mdx/link/index.ts
> Fix links on the site

- .changeset/gentle-mangos-joke.md
- packages/lab/src/segmented-button-group/SegmentedButtonGroup.tsx
> Fix segmented button group

- .changeset/large-clocks-grin.md
- packages/core/src/__tests__/__e2e__/dialog/Dialog.cy.tsx
- packages/core/src/dialog/Dialog.tsx
- packages/core/stories/dialog/dialog.stories.tsx
- packages/core/stories/drawer/drawer.stories.tsx
> Fix Dialog unmounting twice when closing

- .changeset/long-pandas-wink.md
- packages/core/src/__tests__/__e2e__/progress/CircularProgress.cy.tsx
- packages/core/src/__tests__/__e2e__/progress/LinearProgress.cy.tsx
- packages/core/src/progress/LinearProgress/LinearProgress.tsx
> Fix linear progress render 0 in DOM

- .changeset/quick-beers-clap.md
- packages/core/src/interactable-card/InteractableCard.css
Fix for interactable card showing hover style when disabled.
> Fix interactable card showing hover style when disabled

- .changeset/spicy-vans-whisper.md
- packages/core/src/interactable-card/InteractableCard.css
- packages/core/src/link-card/LinkCard.css
> Update InteractableCard and LinkCard to support the new corner palette

- .changeset/slow-pears-clean.md
- packages/core/src/tooltip/Tooltip.css
> Fix tooltip status icon spacing

- site/src/examples/navigation-item/VerticalGroup.tsx
- site/src/examples/navigation-item/VerticalNestedGroup.tsx
> Fix nav item vertical group spacing

- tooling/stylelint/correct-theme-token-usage/index.js
Print warning of deprecated token in style lint. Keep it warning so we can gradually fix it.
Sample warning in core
```
packages/core/src/button/Button.css
55:44  ⚠  No deprecated token (--salt-size-unit) should be used in component  salt/correct-theme-token-usage
packages/core/src/card/Card.css
35:15  ⚠  No deprecated token (--salt-size-accent) should be used in component  salt/correct-theme-token-usage
44:14  ⚠  No deprecated token (--salt-size-accent) should be used in component  salt/correct-theme-token-usage
51:15  ⚠  No deprecated token (--salt-size-accent) should be used in component  salt/correct-theme-token-usage
60:14  ⚠  No deprecated token (--salt-size-accent) should be used in component  salt/correct-theme-token-usage
packages/core/src/checkbox/Checkbox.css
28:55  ⚠  No …
```
> Update stylelint to include no deprecated warning

- .changeset/rare-turkeys-change.md
- packages/core/src/switch/Switch.css
- packages/core/stories/form-field/form-field.qa.stories.tsx
- packages/core/stories/form-field/form-field.stories.tsx
- packages/core/stories/switch/switch.qa.stories.tsx
- packages/core/stories/switch/switch.stories.tsx
- site/docs/components/form-field/examples.mdx
- site/docs/components/switch/examples.mdx
- site/src/examples/form-field/WithControls.tsx
- site/src/examples/form-field/index.ts
- site/src/examples/switch/LeftAlignedLabel.tsx
- site/src/examples/switch/index.ts
> Fix Switch's alignment when it's used with a left/right aligned FormFieldLabel

- .changeset/fresh-garlics-fry.md
- packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx
- packages/core/src/combo-box/ComboBox.tsx
- packages/core/src/combo-box/useComboBox.tsx
> Fix CB pill deletion

- .changeset/eighty-coins-trade.md
- packages/ag-grid-theme/css/_salt-ag-theme-icon-font.scss
- packages/ag-grid-theme/css/_uitk-ag-theme-icon-font.scss
- packages/ag-grid-theme/css/uitk-ag-theme.scss
- packages/ag-grid-theme/stories/ag-grid.stories.tsx
- packages/ag-grid-theme/stories/dependencies/useAgGridHelpers.ts
- packages/ag-grid-theme/stories/examples/Default.tsx
Fixed CSS, adding a new story for Chromatic
#3351
> Fixed icon not displayed correctly when salt theme class is not the first

- packages/core/src/link/Link.tsx
- packages/core/src/text/Text.css
- packages/core/src/text/Text.tsx
- packages/core/stories/link/link.qa.stories.tsx
- packages/core/stories/link/link.stories.tsx
- packages/core/stories/text/text.qa.stories.tsx
- packages/core/stories/text/text.stories.tsx
- packages/lab/src/contact-details/ContactPrimaryInfo.tsx
- packages/lab/src/contact-details/ContactSecondaryInfo.tsx
- packages/lab/src/contact-details/ContactTertiaryInfo.tsx
- packages/lab/src/contact-details/types.ts
- packages/lab/src/stepped-tracker/StepLabel/StepLabel.tsx
- site/docs/components/link/examples.mdx
- site/docs/components/text/examples.mdx
- site/src/examples/link/Color.tsx
- site/src/examples/link/index.ts
- site/src/examples/text/Color.tsx
- site/src/examples/text/index.ts
Fix issues [#2286 ](https://github.com/jpmorganchase/salt-ds/issues/2286)
> adding new color property in Text and Link component

- packages/core/stories/patterns/forms/forms.stories.tsx
- site/docs/patterns/forms.mdx
Adds some examples of forms pattern to storybook.
> Add forms examples

- .changeset/heavy-geckos-scream.md
- packages/ag-grid-theme/css/_salt-ag-theme-default-params.scss
> Ag grid header background color point to container characteristics

- .changeset/rude-ravens-design.md
- packages/lab/src/__tests__/__e2e__/calendar/Calendar.cy.tsx
- packages/lab/src/calendar/Calendar.tsx
- packages/lab/src/calendar/internal/CalendarCarousel.tsx
- packages/lab/src/calendar/internal/CalendarNavigation.css
- packages/lab/src/calendar/internal/useFocusManagement.ts
- packages/lab/src/calendar/useCalendar.ts
- Fixed mozilla div focus bug https://bugzilla.mozilla.org/show_bug.cgi?id=1069739 and added aria label to calendar for accessibility improvement.
- Prevent event defaults in keyboard navigation.
> fixes on calendar

- packages/lab/src/__tests__/__e2e__/calendar/Calendar.cy.tsx
- packages/lab/src/calendar/useCalendar.ts
- packages/lab/src/calendar/useSelection.ts
account for cases where selection is a selection of undefined
> Calendar fix range check 

- packages/core/stories/patterns/split-button/split-button.stories.tsx
- site/docs/patterns/split-button.mdx
Add split button examples and add link to site page
> Split button examples

- packages/lab/src/__tests__/__e2e__/tabs/Tabs.cy.tsx
skip flaky test in tabs while we investigate
> skip flaky test

- packages/core/stories/patterns/navigation/navigation.stories.tsx
- site/docs/patterns/navigation.mdx
Adds an example of Navigation layout to storybook
> Navigation pattern example

- .changeset/new-parrots-deny.md
- packages/core/src/dialog/Dialog.css
Order of the css was not correctly applied
> Fixed Dialog border css

- .changeset/neat-masks-care.md
- packages/core/src/dialog/DialogContent.css
- packages/core/stories/dialog/dialog.qa.stories.tsx
- packages/core/stories/dialog/dialog.stories.css
- packages/core/stories/dialog/dialog.stories.tsx
Example at https://0431a4bc.saltdesignsystem-storybook.pages.dev/?path=/story/core-dialog--sticky-footer
> Change Dialog Footer alignment

- packages/theme/css/characteristics/container-next.css
- packages/theme/css/characteristics/editable-next.css
- packages/theme/css/characteristics/overlayable-next.css
- packages/theme/css/characteristics/selectable-next.css
- packages/theme/css/characteristics/separable-next.css
- packages/theme/css/characteristics/track-next.css
- packages/theme/css/foundations/fade-next.css
- packages/theme/css/palette/alpha-next.css
- packages/theme/css/palette/background-next.css
- packages/theme/css/palette/neutral-next.css
- packages/theme/css/theme-next.css
Move theme next tokens before first release
> Theme next: add alpha-next palette

- .changeset/clever-shrimps-knock.md
- packages/lab/src/date-picker/DatePickerPanel.tsx
- packages/lab/stories/date-picker/date-picker.stories.tsx
- site/src/examples/date-picker/CustomFormatter.tsx
update custom format example to use DateFormat to avoid it rendering different depending on locale
> Date picker update custom format example

- .changeset/text-class-name-disappear.md
- packages/core/src/__tests__/__e2e__/text/Text.cy.tsx
- packages/core/src/text/Code.tsx
- packages/core/src/text/Display.tsx
- packages/core/src/text/Text.tsx
- packages/core/src/text/TextAction.tsx
- packages/core/src/text/TextNotation.tsx
> Fix Text components not applying `className` correctly

- .changeset/switch-no-label-span.md
- packages/core/src/__tests__/__e2e__/switch/Switch.cy.tsx
- packages/core/src/switch/Switch.tsx
> Fix no empty label span in Switch

- .changeset/clever-lemons-fetch.md
- packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.cy.tsx
- packages/lab/src/date-picker/DatePickerPanel.css
> Fix date picker shown behind dialog

- site/docs/foundations/density.mdx
- site/docs/foundations/division.mdx
- site/docs/foundations/responsiveness.mdx
- site/docs/foundations/spacing.mdx
Documentation updated for Density, Division , Responsiveness and Spacing
> Foundation's documentation links updated 

- .changeset/stale-shirts-greet.md
- packages/core/src/__tests__/__e2e__/toast/Toast.cy.tsx
- packages/core/src/toast/Toast.css
- packages/core/src/toast/Toast.tsx
- packages/core/stories/toast/toast.qa.stories.tsx
- packages/core/stories/toast/toast.stories.tsx
- site/docs/components/toast/examples.mdx
- site/src/examples/toast/CustomIcon.tsx
- site/src/examples/toast/index.ts
Closes #3088. This is a reopen of https://github.com/jpmorganchase/salt-ds/pull/3116 but with changes to Toast only, no changes to StatusIndicator.
> Add custom icon feature to Toast 

- .changeset/wet-jokes-jog.md
- packages/core/src/segmented-button-group/SegmentedButtonGroup.css
- packages/core/stories/segmented-button-group/segmented-button-group.qa.stories.tsx
- packages/core/stories/text/text.qa.stories.tsx
Was a quick fix.
@origami-z how are we handling changesets for stuff like this?
> Fix SegmentedButtonGroup with corner rounded

- .changeset/lucky-apricots-try.md
- packages/core/stories/salt-provider/salt-provider-next.mdx
- packages/theme/css/characteristics/text.css
- packages/theme/css/palette/text-next.css
- packages/theme/css/palette/text.css
H1 should be the only one changed
Display 4 / amplitude font weight switch
- step 1: this PR commit 1, add font weight palette for theme 1
- step 2: this PR commit 2, add font weight switch at palette level for theme 2
- step 3: add display 4 mapping #3495
Part of #3368
> Added font weight palette and update H1 font weight

- .changeset/sharp-files-unite.md
- packages/core/stories/link/link.qa.stories.tsx
- packages/theme/css/foundations/color-next.css
Further design change to enable possible purple accent switch
Design: https://www.figma.com/design/DWClNw9QaYIRU9GzIdmOpQ?node-id=7532-41161#829030518
> Update purple 600-900 in theme next

- site/docs/components/avatar/index.mdx
- site/docs/components/badge/index.mdx
- site/docs/components/card/index.mdx
- site/docs/components/checkbox/index.mdx
- site/docs/components/combo-box/index.mdx
- site/docs/components/dialog/index.mdx
- site/docs/components/drawer/index.mdx
- site/docs/components/dropdown/index.mdx
- site/docs/components/file-drop-zone/index.mdx
- site/docs/components/form-field/index.mdx
- site/docs/components/input/index.mdx
- site/docs/components/menu/index.mdx
- site/docs/components/navigation-item/index.mdx
- site/docs/components/overlay/index.mdx
- site/docs/components/pagination/index.mdx
- site/docs/components/panel/index.mdx
- site/docs/components/parent-child-layout/index.mdx
- site/docs/components/pill/index.mdx
- site/docs/components/progress/index.mdx
- site/docs/components/radio-button/index.mdx
- site/docs/components/scrim/index.mdx
- site/docs/components/segmented-button-group/index.mdx
- site/docs/components/spinner/index.mdx
- site/docs/components/switch/index.mdx
- site/docs/components/tooltip/index.mdx
- site/src/layouts/DetailComponent/DetailComponent.tsx
- site/src/layouts/DetailComponent/SecondarySidebar.tsx
Would be good to show first version available on site
> Adds component available since version in side bar

- .changeset/long-berries-heal.md
- packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx
- packages/core/src/combo-box/useComboBox.tsx
> Fix combo box defaultValue

- .changeset/polite-laws-shout.md
- .changeset/two-rats-protect.md
- .storybook/preview.tsx
- docs/decorators/withTheme.tsx
- packages/core/src/__tests__/__e2e__/salt-provider/SaltProvider.cy.tsx
- packages/core/src/button/Button.css
- packages/core/src/salt-provider/SaltProvider.tsx
- packages/core/src/text/Text.css
- packages/core/src/theme/ActionFont.ts
- packages/core/src/theme/index.ts
- packages/core/src/toggle-button/ToggleButton.css
- packages/core/stories/salt-provider/salt-provider-next.mdx
- packages/theme/css/characteristics/text.css
- packages/theme/css/palette/text-next.css
- packages/theme/css/palette/text.css
Adds 
- `actionFont` switch to `UNSTABLE_SaltProviderNext`
- Add theme tokens for theme and theme next
- Update Button css
#3528
> Add action font theme switch

- .changeset/config.json
- .changeset/many-forks-lick.md
- packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
https://github.com/jpmorganchase/salt-ds/blob/0da6bf82a253a10fb081bd1c4c190f9184e245e3/.github/workflows/release.yml#L7
~Need to work out hotfix release mechanism~ With #3587 merged and `baseBranch` change, once this PR is merged, we should get a changeset auto PR 
#3581
> [Hotfix] Fix column menu not scrollable

- .github/workflows/release.yml
Replay #3587
Hopefully this will trigger release action
> Add hotfix branch to release pipeline

- site/docs/components/tag/examples.mdx
- site/src/examples/tag/Bordered.tsx
- site/src/examples/tag/Categories.tsx
- site/src/examples/tag/Icon.tsx
- site/src/examples/tag/Secondary.tsx
- site/src/examples/tag/Variants.tsx
- site/src/examples/tag/WithIcon.tsx
- site/src/examples/tag/index.ts
addressed feedback from https://github.com/jpmorganchase/salt-ds/pull/3515
> Tag content update

- .changeset/mighty-birds-tie.md
- packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx
- packages/core/src/__tests__/__e2e__/dropdown/Dropdown.cy.tsx
- packages/core/src/combo-box/ComboBox.tsx
- packages/core/src/list-control/ListControlState.ts
> Fix combo box can be focused when disabled

- .changeset/twelve-pets-poke.md
- packages/core/src/__tests__/__e2e__/menu/Menu.cy.tsx
- packages/core/src/menu/MenuPanel.css
> Fix Menu showing behind Drawer

- site/src/css/theme/theme.css
Fixes action font not showing on site.
See issue here: https://www.saltdesignsystem.com/salt/components/button/examples
> Fix action font family on site

- .changeset/red-deers-share.md
- packages/core/src/__tests__/__e2e__/file-drop-zone/FileDropZone.cy.tsx
- packages/core/src/file-drop-zone/FileDropZoneTrigger.tsx
- packages/core/stories/file-drop-zone/file-drop-zone.stories.tsx
> Fix file drop zone not able to select the same file

- packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx
- packages/core/stories/combo-box/combo-box.stories.tsx
- site/docs/components/combo-box/examples.mdx
- site/src/examples/combo-box/EmptyMessage.tsx
updates empy combobox example in site and closes https://github.com/jpmorganchase/salt-ds/issues/3632
> Update empty message combobox site example

- .changeset/unlucky-cats-add.md
- packages/core/src/tooltip/Tooltip.css
> Fix Tooltip height

- site/src/examples/dialog/Sizes.tsx
Updating large dialog example to show correct size
> Update Dialog sizes example

- site/docs/components/combo-box/usage.mdx
- site/docs/components/dropdown/usage.mdx
documentation to address https://github.com/jpmorganchase/salt-ds/issues/3333
> Combobox and Dropdown documentation about list height

- .changeset/hip-mirrors-attend.md
- packages/lab/src/calendar/internal/CalendarDay.css
- packages/lab/src/date-picker/DatePickerPanel.css
- packages/lab/stories/calendar/calendar.qa.stories.tsx
> Update styling of date picker and calendar

- .changeset/soft-lions-divide.md
- packages/core/src/__tests__/__e2e__/dialog/Dialog.cy.tsx
- packages/core/src/dialog/Dialog.tsx
> Fix Dialog's initialFocus prop

- .changeset/witty-terms-march.md
- packages/core/src/salt-provider/SaltProvider.tsx
> Add JSDoc to `SaltProviderNext` props

- .changeset/fresh-brooms-explain.md
- site/docs/components/avatar/index.mdx
- site/docs/components/badge/index.mdx
- site/docs/components/checkbox/index.mdx
- site/docs/components/pill/index.mdx
Added links for Avatar, Badge and Checkbox to other components that are marked as similar to them.
> Added reciprocal links for some components

- .changeset/loud-avocados-teach.md
- packages/core/src/pagination/PageButton.css
> Fix Pagination hover color when theme next is enabled

- .changeset/tame-islands-tell.md
- packages/lab/src/dropdown/Dropdown.css
- packages/lab/src/dropdown/DropdownBase.tsx
- packages/lab/src/tabs/Tabstrip.css
- packages/lab/src/toolbar/overflow-panel/OverflowPanel.css
- site/src/css/utilities/patches.css
> Change Dropdown's classname to saltDropdownBase

- .changeset/pretty-feet-dance.md
- packages/core/src/list-control/ListControlState.ts
Closes #3893 
Test: https://stackblitz.com/edit/salt-template-kt57bp?file=package.json
> Fix ListBox not scrolling to the active item in some circumstances

- .changeset/seven-rivers-fail.md
- packages/core/src/form-field/FormField.css
fixes https://github.com/jpmorganchase/salt-ds/issues/3848
> Update gap for top aligned FormField

- .changeset/mean-kids-marry.md
- packages/core/src/option/Option.css
- packages/core/stories/combo-box/combo-box.qa.stories.tsx
- packages/core/stories/dropdown/dropdown.qa.stories.tsx
closes https://github.com/jpmorganchase/salt-ds/issues/3618
> fix only item scroll in combobox

- .changeset/strong-pens-fix.md
- packages/lab/src/calendar/internal/CalendarDay.css
> Fix disabled out of bounds days still having a hover state in Calendar

- packages/core/stories/dialog/dialog.qa.stories.tsx
> Move Dialog QA story to core

- .changeset/curly-bugs-behave.md
- packages/core/src/__tests__/__e2e__/navigation-item/NavigationItem.cy.tsx
- packages/core/src/navigation-item/NavigationItem.tsx
- packages/core/stories/navigation-item/navigation-item.qa.stories.tsx
> Fix the default NavigationItem being considered a parent and onClick not being called

- .changeset/button-changes.md
Add deprecated / replacement mapping
> Update button update changeset with mapping

- .changeset/heavy-pears-walk.md
- packages/core/src/radio-button/RadioButtonIcon.tsx
- packages/core/stories/radio-button/radio-button.qa.stories.tsx
> Fix read-only checked radio buttons having the incorrect icon color

- .changeset/sour-turtles-itch.md
- packages/core/src/pill-input/PillInput.css
- packages/core/src/pill/Pill.css
> Update Pill to follow the new button styles

- site/docs/foundations/size.mdx
- site/docs/foundations/spacing.mdx
- site/docs/theming/index.mdx
Extract edits from #3898
Closes #3666
> Update theming page with code examples

- .changeset/kind-ants-bathe.md
- packages/core/src/pill-input/PillInput.css
Since #3930 is blocked, this is a quick fix for the multiselect pills in combo box.
> Fix multiselect combobox having incorrect pill styles in theme next

- site/docs/foundations/density.mdx
- site/docs/foundations/division.mdx
- site/docs/foundations/duration.mdx
- site/docs/foundations/responsiveness.mdx
- site/docs/foundations/scale.mdx
- site/docs/foundations/size.mdx
- site/docs/foundations/spacing.mdx
- site/docs/foundations/typography.mdx
Feedback from site research interviews
> Fix broken site links under foundations

- .changeset/little-bobcats-obey.md
- packages/core/src/checkbox/Checkbox.css
- packages/core/src/checkbox/CheckboxIcon.css
- packages/core/src/radio-button/RadioButton.css
- packages/core/src/radio-button/RadioButtonIcon.css
> Checkbox and RadioButton fixes

- .changeset/lemon-humans-remain.md
- packages/core/src/button/Button.css
> Fixed focusble when disabled button's having incorrect styling when in a disabled active state

- .changeset/smooth-candles-explain.md
- packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx
- packages/core/src/__tests__/__e2e__/dropdown/Dropdown.cy.tsx
- packages/core/src/combo-box/ComboBox.tsx
- packages/core/src/dropdown/Dropdown.tsx
> Fixed ComboBox and Dropdown calling onBlur when an option in the list is clicked

- packages/core/stories/pill/pill.stories.tsx
- site/src/examples/pill/Closable.tsx
> Update closable pill icon in examples

- .changeset/five-dodos-divide.md
- .storybook/main.ts
- packages/core/src/navigation-item/NavigationItem.css
- packages/core/stories/navigation-item/navigation-item.qa.stories.tsx
- packages/core/stories/navigation-item/navigation-item.stories.css
- packages/core/stories/navigation-item/navigation-item.stories.tsx
- site/src/examples/navigation-item/VerticalNestedGroup.tsx
- site/src/examples/navigation-item/WithNestedItems.tsx
Closes #4023
I decided to fix this two different ways:
- Fix the styling issue (icon taking the link styling)
- Update the docs to show our preferred usage of NavigationItem
> Fix the icon inside Navigation Item having the incorrect color when a  parent item is also a link

- .changeset/spotty-beers-add.md
- packages/core/src/accordion/Accordion.css
- packages/core/src/accordion/Accordion.tsx
- packages/core/src/accordion/AccordionHeader.css
- packages/core/src/accordion/AccordionHeader.tsx
- packages/core/src/accordion/AccordionPanel.tsx
- packages/core/stories/accordion/accordion.qa.stories.tsx
> Fixed disabled accordions having status styling

- .changeset/slow-dodos-allow.md
- packages/core/src/dialog/Dialog.css
- site/propsGen.js
Dialog to have modal z-index.
Scrim remains as Drawer zindex - 1, given Drawer also uses it.
> Fix Dialog to have `--salt-zIndex-modal`

- .changeset/twenty-bugs-help.md
- packages/core/src/checkbox/Checkbox.css
- packages/core/src/radio-button/RadioButton.css
> Fix the alignment of Checkbox and Radio Button when they don't have a label

- .storybook/toolbar/ThemeNextToolbar.tsx
make the button active when next is "enable"
> Make storybook theme next toggle active more obvious

- site/docs/foundations/color.mdx
-Short term text update of Color page to include **definitions for status, sentiment and neutrality** for September Button release
> Update Color foundation page 

- .changeset/beige-poets-enjoy.md
- packages/core/src/pill-input/PillInput.css
- packages/core/src/pill/Pill.css
> Update Pill's styling to align to Button's new styling

- .changeset/metal-pumas-pretend.md
- packages/core/src/file-drop-zone/FileDropZone.css
- packages/core/src/menu/MenuGroup.css
- packages/core/src/menu/MenuItem.css
- packages/core/src/option/OptionGroup.css
- packages/core/src/overlay/OverlayPanel.css
- packages/core/src/panel/Panel.css
- packages/core/src/tooltip/Tooltip.css
> Fixed text contrast issues in Menu, Dropdown, ComboBox and ListBox and removed some deprecated token usage

- site/docs/components/index.mdx
> Update lab package doc paragraph

- site/docs/components/toast/accessibility.mdx
update following https://github.com/jpmorganchase/salt-ds/pull/4194#discussion_r1780697185
> update toast accessibility docs

- .changeset/slow-suns-end.md
- packages/core/src/text/Text.css
added letter spacing to text styles for consistency
> Update text typographic styles for consistency

- .changeset/pretty-teachers-vanish.md
- packages/lab/src/date-input/DateInputSingle.tsx
> Fix `DateInput` `inputRef` type

- .changeset/lazy-camels-hope.md
- packages/core/stories/button/button.qa.stories.tsx
- packages/theme/css/characteristics/actionable-next.css
- packages/theme/css/foundations/alpha-next.css
- packages/theme/css/palette/negative-next.css
- packages/theme/css/palette/positive-next.css
- packages/theme/css/palette/warning-next.css
#4302
Fortunately this is only in one file, search `var\([-\w]+\s` in "./packages/theme/css"
> Fix invalid css variables

- .changeset/red-chefs-taste.md
- packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx
- packages/core/src/__tests__/__e2e__/dropdown/Dropdown.cy.tsx
- packages/core/src/combo-box/ComboBox.tsx
- packages/core/src/dropdown/Dropdown.tsx
> Fix aria-multiselectable being incorrectly applied in the ComboBox and Dropdown

- site/src/components/mdx/anchorHeading/AnchorHeading.module.css
- site/src/components/mdx/link/A.module.css
> Add focus outline to site links

- .github/ISSUE_TEMPLATE/bug_report.yml
current link is getting suffixed
> Update bug report template go link

- .github/workflows/react-cron.yml
> Add react canary testing

- site/docs/foundations/division.mdx
- User feedback from Salt email list 
- Fixed anchor link to Modes section of external site
> Fix broken link in Division.mdx

- .changeset/olive-ears-add.md
- packages/core/src/checkbox/Checkbox.css
- packages/core/src/radio-button/RadioButton.css
> Fix focus rings not appearing on checkboxes and radio buttons.

- site/docs/components/dialog/examples.mdx
> Update Dialog doc size table

- .changeset/hot-tomatoes-hide.md
- packages/core/stories/file-drop-zone/file-drop-zone.qa.stories.tsx
- packages/theme/css/characteristics/target-next.css
> Fix target characteristic tokens being incorrect in Salt Next

- .changeset/chatty-geckos-obey.md
- packages/core/src/toggle-button/ToggleButton.css
(This work has already been done in Figma)
Aligned to Button's CSS so we add sentiment later (#4187)
> Update ToggleButton's styling to align to Button's new styling

- .changeset/chilly-frogs-scream.md
- packages/core/src/link/Link.tsx
Cherry picked from #4325
Fixes #4324
> Fix color prop not working for Link

- packages/core/src/overlay/OverlayPanelContent.css
add specificity to the content overflow in overlay
> Fix overlay overflow cutting focus ring

- .changeset/seven-bugs-tickle.md
- packages/core/src/__tests__/__e2e__/menu/Menu.cy.tsx
- packages/core/src/menu/MenuItem.tsx
- packages/core/stories/menu/menu.stories.tsx
> Fix disabled menu items triggering click events

- .changeset/lazy-bugs-obey.md
- packages/core/src/__tests__/__e2e__/dialog/Dialog.cy.tsx
- packages/core/src/utils/useResponsiveProp.ts
> Fix useResponsiveProp not being inclusive when calculating breakpoints

- .changeset/eighty-bears-chew.md
- packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx
- packages/core/src/__tests__/__e2e__/dropdown/Dropdown.cy.tsx
- packages/core/src/combo-box/ComboBox.tsx
- packages/core/src/dropdown/Dropdown.tsx
> Fix aria-activedescendant not being removed when Dropdown or ComboBox is closed 

- .changeset/poor-mayflies-bow.md
- packages/theme/css/characteristics/actionable.css
> Fix actionable background token reference

- .changeset/spotty-eels-remember.md
- packages/theme/css/deprecated/foundations-next.css
- packages/theme/css/foundations/color-next.css
- packages/theme/css/theme-next.css
The token is not used anywhere by us
Caught in #4320
> Fix titanium background token name

- .changeset/pretty-geese-watch.md
- packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.range.cy.tsx
- packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.single.cy.tsx
- packages/lab/src/date-picker/DatePickerRangeInput.tsx
- packages/lab/stories/date-picker/date-picker.stories.tsx
> Fix `DatePickerRangeInput` not passing down `format`

- README.md
Not using deprecated prop in readme 😅
> Update readme Button example code

- site/docs/components/toast/examples.mdx
> Toast group site example heading add lab icon

- .changeset/stupid-worms-learn.md
- packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.range.cy.tsx
- packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.single.cy.tsx
- packages/lab/src/date-picker/DatePicker.tsx
- packages/lab/src/date-picker/DatePickerOverlayProvider.tsx
- packages/lab/src/date-picker/DatePickerRangeInput.tsx
- packages/lab/src/date-picker/DatePickerSingleInput.tsx
- packages/lab/stories/date-picker/date-picker.stories.tsx
> Date picker fix readOnly overlay

- .changeset/smart-jobs-heal.md
- packages/core/src/accordion/AccordionHeader.css
> Set AccordionHeader's background color to align with Figma

- package.json
- yarn.lock
Updating to a version that is present in Artifactory.
> Update AG Grid version

- .changeset/seven-pears-juggle.md
- packages/core/src/dropdown/Dropdown.tsx
Fixes #4548 
**Before**
_________________________________________
**After**
> Remove validation status for disabled dropdown

- .changeset/dirty-emus-remain.md
- packages/theme/css/foundations/color.css
> Fix `--salt-color-autumn-500`, `--salt-color-indigo-500`, `--salt-color-rose-500` not meeting color contrast requirements in certain scenarios

- .changeset/two-tomatoes-press.md
- packages/theme/css/characteristics/navigable-next.css
- packages/theme/css/characteristics/navigable.css
- packages/theme/css/deprecated/characteristics.css
- packages/theme/css/deprecated/foundations.css
- packages/theme/css/deprecated/palette.css
- packages/theme/css/foundations/fade.css
- packages/theme/css/foundations/opacity.css
- packages/theme/css/palette/navigate.css
> Deprecate navigable background hover

- .changeset/spotty-jeans-pump.md
- packages/core/src/checkbox/Checkbox.tsx
- packages/core/src/radio-button/RadioButton.tsx
> Add inputRef to Checkbox and RadioButton

- .changeset/lovely-bats-kick.md
- packages/core/src/interactable-card/InteractableCard.css
- packages/core/stories/interactable-card/interactable-card.qa.stories.tsx
> Fix tertiary card disabled styles

- .changeset/strong-cameras-shop.md
- packages/theme/css/foundations/spacing.css
> Extend the spacing foundation to spacing-950

- site/docs/getting-started/designing/index.mdx
> Update get started page

- packages/core/stories/patterns/international-phone-number/international-phone-number.stories.tsx
- site/docs/patterns/international-phone-number-input.mdx
> Add international phone number examples

- site/docs/components/text/examples.mdx
- site/src/examples/text/Weight.tsx
- site/src/examples/text/index.ts
> Add font weight examples to Text docs

- .yarn/patches/@changesets-assemble-release-plan-npm-6.0.5-3055b7bcad.patch
- package.json
- yarn.lock
> Update changesets dependencies

- .changeset/light-oranges-knock.md
- .changeset/short-gorillas-train.md
- .changeset/wise-dragons-punch.md
- packages/theme/css/characteristics/track-next.css
- packages/theme/css/deprecated/fade.css
- packages/theme/css/foundations/alpha-next.css
- packages/theme/css/foundations/alpha.css
- packages/theme/css/palette/alpha.css
> Update alpha colors

- .changeset/neat-doors-cry.md
- packages/core/src/avatar/Avatar.css
- packages/core/src/avatar/Avatar.tsx
- packages/core/stories/avatar/avatar.qa.stories.tsx
- site/docs/components/avatar/examples.mdx
- site/src/examples/avatar/Categories.tsx
- site/src/examples/avatar/index.ts
> Add category to Avatar

- .changeset/silly-taxis-sort.md
- packages/theme/css/characteristics/accent-next.css
- packages/theme/css/characteristics/accent.css
- packages/theme/css/characteristics/track-next.css
- packages/theme/css/characteristics/track.css
- packages/theme/css/deprecated/characteristics.css
> Undeprecate --salt-accent-borderColor-disabled and --salt-track-borderColor-disabled

- site/docs/getting-started/designing/index.mdx
Updated unpublished date for old libraries
> Updated unpublished date for old libraries

- site/docs/themes/index.mdx
Make sure Figma and code appear next to each other in right hand side TOC
> Update themes doc heading level

- site/docs/components/link/usage.mdx
Amended out of date wording, discussed this with Paul + Josh
> Update Link usage guidance.mdx

- .changeset/six-crabs-approve.md
- packages/lab/src/__tests__/__e2e__/tabs-next/TabsNext.cy.tsx
- packages/lab/src/tabs-next/hooks/useOverflow.ts
- packages/lab/stories/tabs-next/tabs-next.stories.tsx
> Fix `TabsNext` overflow when only having enough space for one tab

- .changeset/friendly-pans-boil.md
- packages/date-adapters/scripts/build.mjs
> Fix date-adapter entry points

- .changeset/action-fontweight.md
- .changeset/theme-action-fontweight.md
- packages/core/src/button/Button.css
- packages/core/src/text/Text.css
- packages/theme/css/characteristics/text.css
- packages/theme/css/palette/text.css
> Add action fontWeight support

- .changeset/quiet-camels-explode.md
- packages/core/stories/form-field/form-field.stories.css
- packages/core/stories/form-field/form-field.stories.tsx
- packages/theme/css/characteristics/content-next.css
- packages/theme/css/characteristics/content.css
Use [`/?path=/story/core-form-field--custom-required`](https://jpmorganchase-new-content-at.saltdesignsystem-storybook.pages.dev/?path=/story/core-form-field--custom-required) story to check
> Add --salt-content-attention-foreground

- packages/countries/scripts/templateCountrySymbol.mustache
Run build in countries, you'll see components import order in the diff
> Correct countries mustache import order

- .changeset/strong-papayas-buy.md
- packages/core/src/__tests__/__e2e__/button/Button.cy.tsx
- packages/core/src/button/Button.tsx
> Fix invalid Button prop would crash

- packages/core/src/option/Option.tsx
- packages/core/stories/list-box/list-box.qa.stories.tsx
Changeset existed, follow up from #4882
> Disable checkbox in disabled option

- packages/core/src/switch/Switch.tsx
- site/docs/components/switch/usage.mdx
Thanks @libertymayc for noticing this
> Fix Switch prop description

- site/docs/components/localization-provider/usage.mdx
> Fix AdapterDayjs in doc

- site/src/components/mdx/code/Code.module.css
- site/src/components/mdx/pre/Pre.module.css
- site/src/components/mdx/pre/Pre.tsx
- Add background color to both inline code and code block to make it more obvious
- Adjust inline code alignment
> Site code block color adjustment

- .changeset/quiet-dingos-rhyme.md
- packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx
- packages/core/src/__tests__/__e2e__/dropdown/Dropdown.cy.tsx
- packages/core/src/combo-box/ComboBox.tsx
- packages/core/src/dropdown/Dropdown.tsx
- packages/core/src/list-box/ListBox.tsx
- packages/core/src/list-control/ListControlState.ts
> Fix dropdown errors when move focus in keyDownCapture

- .changeset/token-deprecation.md
- packages/ag-grid-theme/css/parts/ag-root-var.css
- packages/theme/css/characteristics/overlayable-next.css
- packages/theme/css/characteristics/overlayable.css
- packages/theme/css/characteristics/text.css
- packages/theme/css/deprecated/characteristics.css
> Deprecate `overlayable-rangeSelection` and `text-textTransform`

- site/src/components/search/Search.tsx
Try go to homepage, search and type in "sal" then would crash on the current build
> Fix site search crash when type in "sal"

- packages/ag-grid-theme/src/dependencies/useAgGridHelpers.ts
- site/docs/components/ag-grid-theme/examples.mdx
- site/src/components/ag-grid-doc/AgEnterpriseFeature.tsx
- site/src/components/ag-grid-doc/index.ts
- site/src/components/index.ts
- site/src/examples/ag-grid-theme/useAgGridHelpers.ts
> doc: Add ag grid enterprise feature callout

- .changeset/smart-brooms-juggle.md
- packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx
- packages/core/src/combo-box/ComboBox.tsx
> Trigger onPillRemove callback when a pill is removed in ComboBox

- .changeset/eighty-eyes-sniff.md
- biome.jsonc
- packages/core/src/button/Button.tsx
- packages/core/src/dialog/DialogHeader.tsx
- packages/core/src/overlay/OverlayHeader.tsx
> Fix self import package name in core

- site/src/components/navigation/VerticalNavigation.tsx
Component > Slide > Slide ([Preview](https://saltdesignsystem-git-site-nested-component-page-active-fed-team.vercel.app/salt/components/slider/examples)) should be highlighted in the nav bar
> Fix site nested component page active state

- site/docs/foundations/density.mdx
Links on `/salt/foundations/density`
> Fix foundation responsiveness links

- .changeset/brown-mugs-confess.md
- packages/core/src/pagination/PageButton.css
- Updated Pagination styles to include a border on the selected state.
- Updated Pagination to use default text styles instead of action text.
- Fixed hover styles overriding selected styles on Pagination.
> Update Pagination styles

- packages/core/stories/patterns/app-header/app-header.stories.tsx
Just noticed it's missing, looks like an error, thought would raise a PR quickly to fix it
> Fix Missing Closing Bracket

- .changeset/heavy-trees-think.md
- packages/core/src/__tests__/__e2e__/button/Button.cy.tsx
- packages/core/src/button/Button.tsx
> Fix loading buttons submitting forms

- site/docs/getting-started/designing/index.mdx
Adding 2 sections below in Getting started - designing
1. What are Salt Figma Template components?
2. Salt Design Asset Definitions
> Add design asset descriptions to the design getting started page

- site/docs/foundations/color/categorical-colors.mdx
- site/docs/foundations/duration.mdx
- site/docs/foundations/responsiveness/index.mdx
- site/docs/foundations/responsiveness/small-viewports.mdx
Raised by a consumer on Public Teams channel. 
Caused due to Internal site IA change.
> Fix broken foundation section internal site links

- .changeset/khaki-pigs-live.md
- packages/core/src/__tests__/__e2e__/link/Link.cy.tsx
- packages/core/src/link/Link.tsx
> Update link's HAT

- .changeset/giant-lizards-melt.md
- packages/lab/src/static-list/StaticList.css
> Fix StaticList margin

- .changeset/angry-fireants-hide.md
- packages/core/src/stepper/Step.css
- packages/core/src/stepper/internal/StepIcon.css
- packages/core/src/stepper/internal/StepText.css
- site/src/examples/stepper/StageStatus.tsx
> Align stepper

- .changeset/sweet-spiders-juggle.md
- packages/core/src/dialog/DialogContent.css
- packages/core/src/dialog/DialogHeader.css
> Improve DialogHeader wrapping

- .changeset/eight-news-give.md
- packages/theme/css/characteristics/status-next.css
- packages/theme/css/deprecated/palette-next.css
- packages/theme/css/palette/info-next.css
- packages/theme/css/palette/negative-next.css
- packages/theme/css/palette/positive-next.css
- packages/theme/css/palette/warning-next.css
These tokens should be -weakest, as they are in design
> Fix weak/weakest tokens not aligned with figma

- packages/ag-grid-theme/package.json
- packages/core/package.json
- packages/countries/package.json
- packages/data-grid/package.json
- packages/date-adapters/package.json
- packages/embla-carousel/package.json
- packages/icons/package.json
- packages/lab/package.json
- packages/react-resizable-panels-theme/package.json
- packages/styles/package.json
- packages/theme/package.json
- packages/window/package.json
An example of before: https://github.com/jpmorganchase/salt-ds/actions/runs/16931861992/job/47979070715?pr=5448
After: https://github.com/jpmorganchase/salt-ds/actions/runs/16932347320/job/47980678210?pr=5451
> Normalise repository.url in package.json files

- site/docs/components/country-symbol/examples.mdx
- site/docs/components/country-symbol/index.mdx
- site/docs/components/country-symbol/usage.mdx
- site/docs/foundations/assets/country-symbols.mdx
Pending further changes @pseys
> Text updates to Country Symbols component

- .changeset/fuzzy-coats-turn.md
- packages/core/stories/badge/badge.qa.stories.tsx
- packages/lab/src/tabs-next/TabListNext.css
- packages/lab/src/tabs-next/TabListNext.tsx
- packages/lab/src/tabs-next/TabNext.css
- packages/lab/src/tabs-next/TabNext.tsx
- packages/lab/src/tabs-next/TabNextTrigger.css
- packages/lab/src/tabs-next/TabNextTrigger.tsx
- packages/lab/src/tabs-next/TabOverflowList.css
- packages/lab/src/tabs-next/hooks/useOverflow.ts
- packages/lab/src/tabs-next/hooks/useRestoreActiveTab.ts
- packages/lab/stories/tabs-next/tabs-next.stories.tsx
> Tab bug fixes

- .changeset/three-deer-melt.md
- packages/ag-grid-theme/css/parts/ag-root-var.css
> Fix menu color in secondary and zebra variants

- site/docs/components/avatar/usage.mdx
- site/docs/components/banner/usage.mdx
- site/docs/components/border-layout/usage.mdx
- site/docs/components/country-symbol/usage.mdx
- site/docs/components/dialog/usage.mdx
- site/docs/components/navigation-item/usage.mdx
- site/docs/components/pill/usage.mdx
- site/docs/components/salt-provider/usage.mdx
- site/docs/components/semantic-icon-provider/usage.mdx
- site/docs/components/static-list/usage.mdx
- site/docs/components/status-indicator/usage.mdx
- site/docs/components/stepper/usage.mdx
- site/docs/components/system-status/usage.mdx
- site/docs/components/tag/usage.mdx
Spotted whilst going through docs - fixes import snippet not showing (probably due to some recent update?)
> Fix import docs

- .changeset/dry-ears-follow.md
- packages/theme/css/global.css
> Add focus ring global style

- .changeset/shiny-frogs-pump.md
- packages/highcharts-theme/css/salt-highcharts-theme.css
- packages/highcharts-theme/src/default-options.ts
- packages/highcharts-theme/src/examples/BulletChart.tsx
- packages/highcharts-theme/src/examples/dependencies/bulletOptions.ts
- packages/highcharts-theme/src/examples/dependencies/index.ts
- packages/highcharts-theme/src/examples/dependencies/lineOptions.ts
- packages/highcharts-theme/src/examples/dependencies/stackedBarOptions.ts
- packages/highcharts-theme/src/examples/index.ts
- packages/highcharts-theme/stories/highcharts-theme.stories.tsx
- site/docs/components/highcharts-theme/examples.mdx
- site/src/examples/highcharts-theme/BulletChart.tsx
- site/src/examples/highcharts-theme/LineChart.tsx
- site/src/examples/highcharts-theme/index.ts
Add Bullet Chart w/ warning on plot bands being a WIP
> Add Bullet Chart

- .changeset/poor-tips-complain.md
- packages/lab/src/__tests__/__e2e__/date-input/DateInputRange.cy.tsx
- packages/lab/src/__tests__/__e2e__/date-input/DateInputSingle.cy.tsx
- packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.range.cy.tsx
- packages/lab/src/calendar/useCalendarSelection.ts
- packages/lab/src/date-input/DateInputRange.tsx
- packages/lab/src/date-input/DateInputSingle.tsx
- packages/lab/src/date-picker/DatePickerRangeInput.tsx
- packages/lab/src/date-picker/DatePickerSingleInput.tsx
- packages/lab/stories/date-picker/CustomDatePickerPanel.tsx
> fix date input issue recorded in issue 5499

- .changeset/cuddly-bikes-cover.md
- packages/core/src/vertical-navigation/VerticalNavigationItemTrigger.css
> Fix VerticalNavigation having double focus rings

- .changeset/hungry-seals-hide.md
- packages/highcharts-theme/css/salt-highcharts-theme.css
- packages/highcharts-theme/src/examples/BarChart.tsx
- packages/highcharts-theme/src/examples/dependencies/barOptions.ts
- packages/highcharts-theme/src/examples/dependencies/index.ts
- packages/highcharts-theme/src/examples/index.ts
- packages/highcharts-theme/stories/highcharts-theme.stories.tsx
- site/docs/components/highcharts-theme/examples.mdx
- site/src/examples/highcharts-theme/BarChart.tsx
- site/src/examples/highcharts-theme/index.ts
- Adds Bar Chart
- Make bar chart & stacked bar chart examples more consistent with each other and places examples in a logical order (bar, then stacked bar)
- Add omissions such options being optional in sb example
> Add Bar Chart

- packages/highcharts-theme/css/salt-highcharts-theme.css
- packages/highcharts-theme/src/default-options.ts
- packages/highcharts-theme/src/examples/ColumnChart.tsx
- packages/highcharts-theme/src/examples/dependencies/columnOptions.ts
- packages/highcharts-theme/src/examples/dependencies/index.ts
- packages/highcharts-theme/src/examples/index.ts
- packages/highcharts-theme/stories/highcharts-theme.stories.tsx
- site/docs/components/highcharts-theme/examples.mdx
- site/src/examples/highcharts-theme/ColumnChart.tsx
- site/src/examples/highcharts-theme/index.ts
Add Column Chart
- Fix border-radius for bullet in v11+
> Add Column Chart
