jpmorganchase/salt-ds

packages/lab/src/color-chooser/Swatch.tsx
Resolve below build warning
> Entry module "packages/lab/src/color-chooser/Swatch.tsx" is using named and default exports together. Consumers of your bundle will have to use `chunk["default"]` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning
=> Remove unneeded default export from Swatch

.github/workflows/chromatic.yml
Should cut 2 mins off our installs for the Chromatic deployment
=> Enable dependency caching for Chromatic deployments

docs/components/AllRenderer.tsx, docs/components/DocGrid.css, docs/components/DocGrid.tsx
When DocGrid, AllRenderer are used in QA compare story to compare to a generated snapshot, we don't want the layout to vary based on global density setting, as the screenshot is fixed at medium density.
=> allow allrenderer and docgrid styling to be controlled

packages/core/package.json, packages/icons/package.json, packages/lab/package.json, yarn.lock
We don't want to block users to use react 18, otherwise something like below will happen
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! 
> npm ERR! While resolving: @jpmorganchase/uitk-core@0.1.0
> npm ERR! Found: @types/react@18.0.9
> npm ERR! node_modules/@types/react
> npm ERR!   @types/react@"*" from @types/react-dom@18.0.5
> npm ERR!   node_modules/@types/react-dom
> npm ERR!     dev @types/react-dom@"^18.0.0" from the root project
> npm ERR!   dev @types/react@"^18.0.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peerOptional @types/react@"^16.8.6 || ^17.0.0" from @jpmorganchase/uitk-core@0.1.0
=> Allow @types/react 18 peer dependency

.changeset/chilled-kings-compete.md, .github/workflows/test.yml, .stylelintrc.json, package.json, packages/core/src/icon/Icon.css, tooling/stylelint/custom-property-no-foundation-color/index.js, yarn.lock
Add a custom rule to not allow foundation or palette color used in component css.
Starting from core components only.
Example failure: https://github.com/jpmorganchase/uitk/runs/6859637980
=> Stylelint no foundation or palette color used in component css

.changeset/cold-ravens-chew.md, packages/lab/src/__tests__/__e2e__/layout/Split.cy.tsx, packages/lab/src/layout/SplitLayout/SplitLayout.tsx
Adding gap prop to SplitLayout to allow spacing to be controlled. Fixes #160.
=> Control spacing of Split Layout

.changeset/witty-donkeys-deliver.md, packages/core/src/card/Card.css, packages/core/stories/card.qa.stories.css, packages/core/stories/card.qa.stories.tsx, packages/lab/src/checkbox/CheckboxIcon.css, packages/lab/src/dropdown/DropdownButton.css, packages/lab/src/metric/Metric.css, packages/lab/src/metric/MetricContent.css, packages/lab/src/pill/internal/PillCheckbox.css, packages/lab/src/radio-button/RadioButtonGroup.tsx, packages/lab/src/radio-button/RadioIcon.css, packages/lab/src/switch/Switch.css, packages/lab/src/switch/Switch.tsx, packages/lab/stories/checkbox.qa.stories.tsx, packages/lab/stories/form-field.qa.stories.tsx, packages/lab/stories/input.qa.stories.tsx, packages/lab/stories/metric.qa.stories.tsx, packages/lab/stories/radio-button.qa.stories.tsx, packages/lab/stories/switch.qa.stories.css, packages/lab/stories/switch.qa.stories.tsx
Includes taking chromatic screenshot of backwards compat story if applicable for component
**Standardisation**:
- AllExamplesGrid: has new Odyssey styling (screenshotted)
- BackwardsCompatGrid: overrides AllExamplesGrid with backwardsCompat className (screenshotted)
- TK1 VR: Uses BackwardsCompatGrid
- Class name "backwardsCompat" should be applied to the root of the component along with it's base name. Then, CSS should be specific selecting that component i.e. .backwardsCompat.uitkCheckbox (no space). 
_Note 1_: it may be necessary to have the class applied in two places depending on how component can be used, e.g. .backwardsCompat.uitkRadioButton and .backwardsCompat.uitkRadioButtonGroup
_Note 2_: if it is a shared component, e.g. ControlLabel, it is best to use .backwardsCompat …
=> Standardize backwards compat classes and QA

.changeset/violet-pianos-tell.md, packages/icons/package.json
This hopefully will resolve the issue that Icon CSS is not being loaded while using `react-scripts` / webpack based setup.
<Button>
 {"No icon here ->"}
<SearchIcon size={12} />
</Button>
Above code in fresh CRA / modular set up will result in below render (reproduce [repo](https://github.com/origami-z/uitk-cra-icon-css-loading))
While debugging, no code in `node_modules/@jpmorganchase/uitk-icons/dist-es/packages/icons/src/icon/Icon.css.js` is executed at runtime while using webpack based tooling (vite is fine). There might be other ways to force code being included, but given `css.js` files are generated by build tool, we don't have much control over that.
Interestingly enough, the same code doesn't have problem on Stackblitz [example](https://stackblitz.com/edit/react-ts-uarhsw?file=App. …
=> Modify sideEffects to css related files for icons package.json

.changeset/spicy-worms-clap.md, packages/core/src/__tests__/__e2e__/layout/Flex.cy.tsx, packages/core/src/layout/FlexItem/FlexItem.tsx, packages/core/src/layout/FlexLayout/FlexLayout.css, packages/core/src/layout/FlexLayout/FlexLayout.tsx, packages/core/src/layout/FlowLayout/FlowLayout.tsx, packages/core/src/layout/ParentChildLayout/ParentChildLayout.tsx, packages/core/src/layout/SplitLayout/SplitLayout.tsx, packages/core/src/layout/StackLayout/StackLayout.tsx, packages/core/src/layout/types.ts, packages/core/stories/layout/border-layout.stories.tsx, packages/core/stories/layout/flex-item.stories.tsx, packages/core/stories/layout/flex-layout.stories.tsx, packages/core/stories/layout/flow-layout.stories.tsx, packages/core/stories/layout/grid-layout.stories.tsx, packages/core/stories/layout/split-layout.stories.tsx, packages/core/stories/layout/stack-layout.stories.tsx
These changes have been reviewed by Stella. They mostly include small tweaks to the storybook examples but the most important change is allowing the `FlexLayout` component to wrap by default
=> Wrap by default on FlexLayout and tweak layout storybook examples

.changeset/selfish-dots-rush.md, packages/core/src/__tests__/__e2e__/pill/Pill.cy.tsx, packages/core/src/pill/internal/PillBase.tsx, packages/core/stories/pill.stories.tsx
This enables support for having different tooltip title than the pill label
=> Add TooltipProps to Pill

.changeset/itchy-bobcats-attack.md, packages/core/src/__tests__/__e2e__/aira-announcer/AriaAnnouncer.cy.tsx, packages/core/src/aria-announcer/AriaAnnouncerProvider.tsx
Closes #277
AriaAnnouncerProvider needed a small negative margin hack to prevent affecting the document flow. Also, the styles were updated to more closely match the [tailwind visually hidden class](https://tailwindcss.com/docs/screen-readers).
=> fix(aria-announcer): prevent breaking full height layouts

packages/lab/src/__tests__/__e2e__/calendar/Calendar.cy.tsx, packages/lab/src/__tests__/__e2e__/tabs/Tabs.cy.tsx
We had a few instances of the test is failing on CI
>  1) Navigation, Given a Tabstrip
>        WHEN initial size is sufficient to display all contents
>          WHEN the tabstrip is first rendered
>            WHEN the selected tab is clicked
>              WHEN the right arrow key is pressed
>                THEN focus will be transfered to the next tab:
>      AssertionError: Timed out retrying after 4000ms: expected '<div#uitk-97739-1.uitkTab.uitkFocusVisible>' to be 'focused'
>   2) GIVEN a Calendar component
>        Navigation
>          Keyboard
>            SHOULD move the focus when the shortcut keys are pressed
>              Shift PageDown:
>      AssertionError: Timed out retrying after 4000ms: expected '<button.uitkCalendarDay>' to be 'focused'
=> fix unstable Tabs and Calendar cy test

.changeset/seven-cherries-kiss.md, packages/core/src/checkbox/CheckboxIcon.css, packages/lab/src/accordion/Accordion.css, packages/lab/src/dialog/Dialog.css, packages/lab/src/pagination/Pagination.css, packages/lab/src/skip-link/SkipLink.css, packages/lab/src/toolbar/Toolbar.css, packages/lab/src/tree/TreeNode.css
Checkbox:
-box-size -> -height and -width
Pagination/Accordion:
—pagination and —accordion prefixes added
Tree node:
—padding-left token changed to padding-left attribute: fixed typo
Dialog/Toolbar:
background-color changed to background as standard 
Skip link:
—skipLink-- (double dash) changed to —skipLink-
=> Fix minor CSS typos

.changeset/honest-cats-yell.md, packages/core/src/checkbox/CheckboxIcon.css, packages/core/src/pill/internal/PillCheckbox.css, packages/core/stories/Checkbox.stories.new-app-checkbox.css, packages/core/stories/checkbox.doc.stories.mdx, packages/grid/src/grid/column-types/row-selection-checkbox/RowSelectionCheckboxColumn.css
Change checkbox token -solid-color to -fill since it is used for fill, and solid-color is picked up as a CSS attr on #344 linting
=> Change checkbox token -solid-color to -fill

.changeset/unlucky-colts-destroy.md, packages/core/src/button/Button.css
`justify-content` value is invalid without `var`
So text will not be center aligned
=> Fix Button justify-content css

.changeset/thirty-kings-do.md, packages/lab/src/combo-box-deprecated/ComboBox.css, packages/lab/src/dropdown/Dropdown.css, packages/lab/src/layout/LayerLayout/LayerLayout.css
z-index bug 
https://uitk.pages.dev/?path=/story/lab-dropdown--with-form-field-label-top
=> Fix z-index for ComboBox, Dropdown and LayerLayout due to CSS variable name mismatch

.changeset/grumpy-socks-develop.md, packages/lab/src/dropdown/DropdownBase.tsx, packages/lab/src/dropdown/DropdownButton.css
Dropdown text will be invisible in `:active` state 
https://d9ff6dec.uitk.pages.dev/?path=/story/lab-dropdown--with-form-field-label-top
=> Fix Dropdown button active text and icon color

.changeset/small-starfishes-battle.md, packages/core/src/theme/Theme.ts
The theme's `id` is for example `uitk-dark` whereas the theme's `name` is just `dark`. 
By using `.uitk-${this.id}`, the `uitk-` portion was duplicated and the code would try to run ``document.body.querySelector(`.uitk-uitk-dark`)`` for example.
This change simply changes the `id` to `name` in that code snippet, alternatively, replacing `.uitk-${this.id}` with `${this.id}` would also suffice if that makes more sense.
While this is not fixed, you can instead call `getCharacteristicValue()` with the `scopeElement` parameter set to ``document.body.querySelector(`.uitk-${theme.name}`)``.
=> Fix: Bug in getCharacteristicValue

packages/core/src/__tests__/__e2e__/scrim/Scrim.cy.tsx, packages/core/src/focus-manager/FocusManager.tsx, packages/core/src/focus-manager/internal/useReturnFocus.ts, packages/core/src/scrim/Scrim.tsx, packages/core/stories/scrim.doc.stories.mdx, packages/core/stories/scrim.stories.tsx
Closes #331 
Each prop refactor is split in to its own commit so I can cherry pick what we like on to the #338 or merge this whole PR if we like them all.
- Refactor `containerFix` and `parentRef` in to a single prop. Currently both of these props are necessary for the "container" feature to work. One is a feature flag to enable it and the ref is necessary to know which container element to bound Scrim to. The refactor consolidates both of these in to a single prop `containerRef` which is used both as a ref and as a feature flag. The only downside of this approach that I can see is that the container mode cannot be switched to on the fly. You have to close and then reopen the Scrim to bind it to a container element. You cannot toggle an already open Scrim from being bound to the window, …
=> Refactor scrim props

packages/lab/src/__tests__/__e2e__/cascading-menu/CascadingMenu.cy.tsx, packages/lab/src/__tests__/__e2e__/combo-box-deprecated/ComboBox.keyboardNavigation.cy.tsx, packages/lab/src/__tests__/__e2e__/list/List.accessibility.cy.tsx, packages/lab/src/__tests__/__e2e__/list/List.declarative.cy.tsx, packages/lab/src/__tests__/__e2e__/list/List.selection.cy.tsx, packages/lab/src/__tests__/__e2e__/tabs/Tabs.cy.tsx, packages/lab/src/__tests__/__e2e__/toolbar/Toolbar.cy.tsx
All our PRs are showing red cross with the same set failing in React 18, which makes it very hard to determine genuine pipeline failures v.s. React 18 ones. Try to skip tests when running React 18 in the PR.
When tests are `undefined`, they are marked as `pending` in Cypress report (same as `skip`), which is better than simply not running them (i.e. `is18 && it(...)`.
=> Skip certain tests failing in React 18

.changeset/orange-emus-turn.md, packages/core/src/control-label/ControlLabel.css, packages/core/src/input/Input.css, packages/core/stories/switch.qa.stories.tsx, packages/grid/src/grid/column-types/row-selection-radio/RowSelectionRadioColumn.css, packages/grid/src/grid/components/Grid.css, packages/lab/src/accordion/Accordion.css, packages/lab/src/breadcrumbs/Breadcrumbs.css, packages/lab/src/calendar/internal/CalendarDay.css, packages/lab/src/calendar/internal/CalendarNavigation.css, packages/lab/src/color-chooser/ColorChooser.css, packages/lab/src/contact-details/ContactDetails.css, packages/lab/src/dialog/DialogTitle.css, packages/lab/src/metric/MetricContent.css, packages/lab/src/pagination/Pagination.css, packages/lab/src/tokenized-input/TokenizedInput.css
Part of CSS clean up: 
- Remove component name classes when tokens are density dependent (see issue #330 for explanation) - go to Contact Details compare with TK1 story and switch to touch density for obvious example of this issue (fixed with this PR)
- Includes creation of tokens where necessary (e.g. ControlLabel)
- Includes Grid.css updates to use CSS API for components with special values for uitk-density-ultrahigh
=> Remove component name classes when tokens are density dependent

packages/core/src/__tests__/__e2e__/button/Button.cy.tsx
This pull request adds two test to Button.cy.tsx to improve the coverage.
Within Button, the function at line 29 is reported as not covered.
Within DivButton, the function at line 32 is reported as not covered and the branch at line 98 is reported as not covered
=> Added tests to improve coverage of Button

.changeset/curly-llamas-sing.md, packages/core/src/button/Button.css, packages/core/src/form-field/FormField.css, packages/core/src/switch/Switch.css, packages/grid/src/grid/components/Grid.css, packages/lab/src/accordion/Accordion.css, packages/lab/src/link/Link.css, packages/lab/src/list-deprecated/ListItem.css, packages/lab/src/list/ListItem.css, packages/lab/src/tokenized-input/TokenizedInput.css, packages/lab/src/toolbar/Tooltray.css, packages/lab/src/tree/Tree.css, packages/lab/src/tree/TreeNode.css
As agreed with dev and design - remove focus visible styling API from components; always use characteristic directly (exception for List - which may need to be looked at by design)
=> Remove focus visible styling API; always use characteristic directly 

.changeset/sour-timers-glow.md, packages/core/src/__tests__/__e2e__/layout/Flex.cy.tsx, packages/core/src/layout/FlexLayout/FlexLayout.css, packages/core/src/layout/FlexLayout/FlexLayout.tsx, packages/core/src/layout/FlowLayout/FlowLayout.tsx, packages/core/src/layout/ParentChildLayout/ParentChildLayout.tsx, packages/core/src/layout/SplitLayout/SplitLayout.tsx, packages/core/src/layout/StackLayout/StackLayout.tsx, packages/core/stories/layout/border-layout.stories.tsx, packages/core/stories/layout/flex-item.stories.tsx, packages/core/stories/layout/flex-layout.stories.tsx, packages/core/stories/layout/layer-layout.stories.tsx, packages/core/stories/layout/split-layout.stories.tsx
- Change the default `wrap` value in `FlexLayout` to false so it matches css Flexbox
- Simplify `FlexLayout` examples
=> Revert to FlexLayout not wrapping by default

.changeset/lovely-readers-talk.md, packages/core/src/responsive/useWidth.ts, packages/icons/src/icon/createIcon.tsx, packages/lab/src/contact-details/ContactMetadataItem.tsx
Fixes circular dependencies warning during `yarn build`, excluding grid package which has a lot more interdependencies to be worked on. cc @ararus
=> Fix circular dependencies warning

.changeset/tricky-comics-fry.md, packages/lab/src/__tests__/__e2e__/combo-box/ComboBox.keyboardNavigation.cy.tsx, packages/lab/src/__tests__/__e2e__/combo-box/ComboBox.selection.cy.tsx, packages/lab/src/__tests__/__e2e__/list/List.scrollApi.cy.tsx, packages/lab/src/list/List.tsx, packages/lab/src/list/VirtualizedList.tsx, packages/lab/src/list/listTypes.ts, packages/lab/src/list/useList.ts, packages/lab/src/list/useVirtualization.ts, packages/lab/stories/list.stories.tsx
- List ref is forwarded to its container HTML element, just like all other components
- Added `scrollingApiRef` for scrolling for both List and VirtualizedList
- VirtualizedList doesn't scroll beyond buffered items, not planning to cover in this PR 
- Fix empty source passed to VirtualizedList will throw error (fixes #359)
- Fix virtualized list className uitkHighlighted
=> Update list ref and scrolling api ref

packages/lab/src/metric/Metric.css, packages/lab/src/metric/MetricContent.css, packages/lab/src/progress/CircularProgress/CircularProgress.css, packages/lab/src/slider/Slider.css, packages/lab/src/spinner/Spinner.css, packages/lab/src/spinner/svgSpinners/SpinnerMedium.tsx
Part of CSS clean up (#377)
For backwards compat tokens, standardise by:
- If density/theme dependent, creating —backwardsCompat- token
- Then set the local token of what needs adjusting (if exists, else the raw attr) within .backwardsCompat class to the backwardsCompat token defined or otherwise the necessary value
Components in this PR: 
> Spinner
> Slider
> CircularProgress
> Metric
See #428 #441
=> Backwards compat styling standardisation 3

packages/core/src/checkbox/Checkbox.css, packages/core/src/checkbox/CheckboxIcon.css, packages/lab/src/list/ListItem.css
See #455 regarding :not usage - CheckboxIcon is last component needing back compat standardisation
=> Remove :not usage on Checkbox and standardise backwards compat

.changeset/sour-icons-relax.md, packages/lab/src/__tests__/__e2e__/list/List.keyboardNavigation.cy.tsx, packages/lab/src/common-hooks/useKeyboardNavigation.ts, packages/lab/src/list/List.css, packages/lab/src/list/List.tsx, packages/lab/stories/list.stories.tsx
ListItems may be populated dynamically - must support the scenario where there may be no data. An empty list currently throws an exception when focus is received.
When empty list receives focus, apply focusVisible to the List.
=> List fix, do not throw exception if focussed when empty

.changeset/thin-taxis-sip.md, packages/lab/src/tabs/Tab.tsx, packages/lab/src/tabs/TabsTypes.ts, packages/lab/src/tabs/Tabstrip.tsx, packages/lab/src/tabs/drag-drop/useDragDropNaturalMovement.tsx, packages/lab/src/tabs/useEditableItem.ts, packages/lab/src/tabs/useKeyboardNavigation.ts, packages/lab/src/tabs/useTabstrip.ts
Allowing client code to supply onMouseDown to Tabstrip allows for client controlled drag drop.
Tidy up some of the types in Tabs.
Remove unused code.
=> Fix onMouseDown prop on Tabstrip being ignored and Improve TypeScript types for Tabs

.changeset/swift-cows-brake.md, packages/core/src/__tests__/__e2e__/button/Button.cy.tsx, packages/core/src/button/Button.tsx
This pull request fixes issue #461, by setting the attribute `type` to "button".
=> Make Button's default type "button" instead of submit

.changeset/serious-cars-agree.md, packages/lab/src/responsive/overflowUtils.tsx, packages/lab/src/responsive/useOverflow.ts
We sometimes see a nasty shimmering effect on Tabstrip or Toolbar at a certain width. It gets stuck in an infinite loop of rendering with and then without the overflow indicator.
The root cause is the method it used to detect overflow, using scrollHeight/width. It's not reliable. 
This is now fixed for horizontal scroll containers. In fact, this fix is to restore the original mechanism used for overflow detection. The reason this was changed was because it did not work in Vertical scrollbars, because of a bug in most browsers on a wrapping flexbox, when flex-direction is column. When such a container wraps, the width is not increased as it a should be.
Vertical Toolbars/Tabstrips will still have the bug, which requires a more complex fix in these cases. Horizontal usage is more common, …
=> fix overflow detection issue for overflow containers

packages/grid/src/EditorContext.ts, packages/grid/src/Grid.css, packages/grid/src/Grid.tsx, packages/grid/src/GridColumn.tsx, packages/grid/src/NumericColumn.tsx, packages/grid/src/RowSelectionCheckboxCellValue.tsx, packages/grid/src/RowSelectionCheckboxColumn.tsx, packages/grid/src/RowSelectionRadioCellValue.tsx, packages/grid/src/RowSelectionRadioColumn.tsx, packages/grid/src/SelectionContext.ts, packages/grid/src/TextCellEditor.tsx, packages/grid/src/__tests__/__e2e__/Grid.cy.tsx, packages/grid/src/internal/ColumnGhost.css, packages/grid/src/internal/gridHooks.tsx, packages/grid/stories/grid-cssVariables.stories.tsx, packages/grid/stories/grid.stories.tsx
Keyboard navigation refactoring
Space and arrows don't scroll the page
Cell editors fixed (when edit mode initiated by typing)
Space on checkbox/radio column doesn't reset previous selection (it toggles selection on the focused row as expected)
API updated: onKeyDown prop added to GridColumn
=> Grid keyboard handling refactoring and bugfixes

.changeset/famous-tomatoes-scream.md, .changeset/witty-zoos-fly.md, packages/core/src/switch/Switch.tsx, packages/lab/src/accordion/Accordion.tsx
Switch and Accordion is doing `console.log` in handlers, removed in this PR.
=> Remove console from Switch and Accordion

.changeset/short-olives-heal.md, packages/lab/src/color-chooser/Swatch.css, packages/lab/stories/color-chooser.qa.stories.tsx
Current active swatch color is smaller, see below 
Fix the style and added a new QA story "Swatches Picker QA"
=> Color chooser: fix active state swatch size

.changeset/witty-parrots-roll.md, packages/grid/src/Grid.css, packages/grid/src/Grid.tsx, packages/grid/src/internal/ColumnDropTarget.css, packages/grid/src/internal/ColumnDropTarget.tsx, packages/grid/src/internal/ColumnGhost.css, packages/grid/src/internal/ColumnGhost.tsx, packages/grid/src/internal/gridHooks.tsx
Updated styles of column ghost (appears when column is moved using drag-and-drop) and column drop targets.
Escape cancels column move.
=> Update styles for Column drag-and-drop and fix escape key not cancelling column move

.github/workflows/test.yml, .yarn/patches/modular-scripts-npm-3.4.0-8cdb747f13.patch, playground/theme-editor-app/package.json, playground/theme-editor-app/src/ThemeEditorApp.d.ts, playground/theme-editor-app/tsconfig.json, yarn.lock
Another half day wasted because of modular....
- Added additional modular patch and `tsconfig` change, so theme-editor-app could run and build
- Added a build job in GitHub action to ensure we don't break it again without noticing
- Updated `dependencies` in `package.json` to fix modular warning look like below 
> [modular] Package @jpmorganchase/uitk-theme imported in @jpmorganchase/theme-editor-app source but not found in package dependencies or hoisted dependencies - this will prevent you from successfully building, starting or moving esm-views and will cause an error in the next release of modular
=> Fix theme editor build

.changeset/rare-coats-talk.md, packages/lab/src/contact-details/ContactDetails.css, packages/theme/css/characteristics/ratable.css, packages/theme/stories/characteristics/ratable.stories.mdx
Ratable is the only characteristic having `border` not `borderColor` in border color naming. e.g. search `-border(-\w+)?:` in `./packages/theme/css/characteristics` folder v.s. search `-borderColor(-\w+)?:`.
Palette color tokens (e.g. `--uitk-palette-rate-border`, `--uitk-palette-neutral-cta-border`) are having `border` as names which is worth a separate discussion.
=> Rename ratable border color token

.changeset/yellow-masks-punch.md, package.json, packages/core/src/aria-announcer/useAriaAnnouncer.ts, packages/core/src/layout/BorderLayout/BorderLayout.tsx, packages/lab/src/breadcrumbs/Breadcrumbs.tsx, packages/lab/src/carousel/Carousel.tsx, packages/lab/src/combo-box-deprecated/ComboBoxDeprecated.tsx, packages/lab/src/list-deprecated/useList.ts, packages/lab/src/metric/MetricHeader.tsx, packages/lab/src/tokenized-input/TokenizedInputBase.tsx, packages/lab/src/tokenized-input/internal/defaultItemToString.ts, packages/lab/src/tokenized-input/useTokenizedInput.tsx, yarn.lock
`@types/classnames` is a stub dependency and isn't needed
Moved stylelint so it's more consistent
Removed warning and rely on native console functionality
=> Dependency clean up

.changeset/pink-goats-do.md, packages/core/src/input/Input.css, packages/core/src/pill/Pill.css, packages/core/src/switch/Switch.css, packages/lab/src/app-header/AppHeader.css, packages/lab/src/logo/Logo.css, packages/lab/src/toggle-button/ToggleButtonGroup.css, packages/theme/css/foundations/palette.css, packages/theme/css/foundations/size.css, packages/theme/stories/foundations/foundations.stories.mdx, packages/theme/stories/foundations/size.stories.mdx
- --uitk-palette-opacity-background fixed to be correct opacity
- Size tokens updated to use unit calculations where density aware
- Pill, Switch, AppHeader, Logo and ToggleGroupButton size tokens moved to respective components:
--uitk-size-adornment -> Input --input-adornment-height
--uitk-size-appHeader --> AppHeader --appHeader-height
--uitk-size-pill -> Pill --pill-height
--uitk-size-switch -> Switch --switch-height
--uitk-size-logo -> Logo --logo-height
--uitk-size-toggleGroupButton -> ToggleGroupButton --toggleGroupButton-height
- Deleted:
--uitk-size-formField-top
- Moved to become density invariant:
--uitk-size-separator: 1px;
--uitk-size-bottomBorder: 2px;
--uitk-size-brandBar: 4px;
=> Size characteristic changes and opacity update

.changeset/quick-rocks-remain.md, packages/lab/src/combo-box/ComboBox.tsx, packages/lab/src/dropdown/Dropdown.tsx, packages/lab/src/list-deprecated/useList.ts, packages/lab/stories/dropdown.stories.tsx, packages/lab/stories/list.stories.tsx
- Generic `Item` type of List family components should be `string` not string literal type `"string"`
- Adding `props` spreading to stories so Storybook's Actions panel will display correctly for handlers (with existing setup [here](https://github.com/jpmorganchase/uitk/blob/6338ff7101b267be268a94b0a3e5821f3fe2fea8/.storybook/preview.tsx#L81))
=> Fix generic default string type for List, Dropdown and Combobox

packages/icons/stories/icon.stories.tsx
remove max width of the flex wrapper for icons lists, and decrease the gap between items
=> Fix spacing in icon search and all list examples

.changeset/tricky-roses-judge.md, packages/lab/src/toggle-button/ToggleButtonGroup.css, packages/theme/css/characteristics/container.css, packages/theme/stories/characteristics/container.stories.mdx
Figma feedback- remove container border color variants, they can be replaced with the same values via emphasis
=> Remove container border color variants

.changeset/gold-bees-try.md, packages/core/src/__tests__/viewport-provider/ViewportProvider.spec.tsx, packages/core/src/viewport/ViewportProvider.tsx
use single ResizeObserver for nested ViewportProviders to detect viewport width
=> Stop nested ViewportProviders creating multiple ResizeObservers

.changeset/violet-yaks-begin.md, packages/grid/src/BaseCell.tsx, packages/grid/src/Grid.tsx, packages/grid/src/GridColumn.tsx, packages/grid/src/RowSelectionCheckboxCellValue.tsx, packages/grid/src/RowSelectionRadioCellValue.tsx, packages/grid/src/__tests__/__e2e__/Grid.cy.tsx, packages/grid/src/internal/TableRow.tsx
Row selection cells show focus border around the interactive element within the cell (radio button or checkbox), not on the cell itself.
=> Row selection checkbox gets focus

site/docusaurus.config.js, site/src/pages/index.tsx
Previously, our site name was configured to be "Welcome to Salt" (same as the H1 _in-page_ title we use on the homepage). However, this meant that our `<title>` texts, which are displayed in browser tabs, bookmarks and search engine results weren't ideal.
For example:
* When browser tabs are narrow and the full text is truncated, you only see "Welcome...", which isn't helpful when you're trying to find the "Salt (Design System)" site in your open tabs:
* The site name is appended to all page titles, meaning it appears twice on the homepage and also every other page is suffixed with "| _Welcome to_ Salt", which looks odd
This PR fixes this by setting the site name to "Salt Design System" (I intentionally included the "Design System" bit to help differentiate this in search results or …
=> Improve site <title> text

.changeset/healthy-spoons-sip.md, packages/core/src/layout/DeckItem/DeckItem.tsx, packages/core/src/utils/useId.ts, packages/lab/src/list-deprecated/useList.ts
This moves useId to a more standard way of polyfilling React's useId (taken from their RFC) and should solve the conflicts we've been seeing on the CI.
=> Move to global id for useId

site/docusaurus.config.js
Turns out adding this config made the edit links appear and mess up some of our page layouts :-(
=> Remove edit page links

site/docs/components/_index/ComponentsList.tsx
Currently we don't display the components figma `N/A` status on mobile view
=> Display components "N/A" label on mobile

site/static/robots.txt
FYI: Docusaurus does already output a `sitemap.xml` file, so linking to it from the `robots.txt` will work fine.
=> adds robots.txt file to site

.changeset/beige-bulldogs-brush.md, packages/core/src/flow-layout/FlowLayout.tsx, packages/core/src/stack-layout/StackLayout.tsx
Previous change from `extend FlexLayoutProps` to `extend HTMLAttributes` for components built from `FlexLayout` to avoid them inheriting all of `FlexLayout` props meant they no longer had access to its polymorphic `as` property.
This change allows `StackLayout` and `FlowLayout` to use the polymorphic prop.
=> Fix flex layouts polymorphic prop

.changeset/fuzzy-foxes-grin.md, packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss, packages/ag-grid-theme/stories/ag-grid.doc.stories.mdx, packages/ag-grid-theme/stories/dependencies/columnSpanningExampleColumns.ts, packages/ag-grid-theme/stories/dependencies/customFilterExampleColumns.ts, packages/ag-grid-theme/stories/dependencies/dataGridExampleColumns.ts, packages/ag-grid-theme/stories/dependencies/dataGridExampleRowGroupPanel.ts, packages/ag-grid-theme/stories/dependencies/dataGridExampleRowGrouping.ts, packages/ag-grid-theme/stories/dependencies/dataGridInfiniteScrollExampleColumns.ts, packages/ag-grid-theme/stories/dependencies/masterDetailExampleData.ts, packages/ag-grid-theme/stories/dependencies/rowDragColumns.ts, packages/ag-grid-theme/stories/examples/ColumnGroup.tsx
- `.editable-cell`
- `.numeric-cell`
Numeric cells can be editable or not, and we can have non-numeric editable cells. So that's the motivation for two separate 
classes (which can be composed together). Technically, we could remove the numeric class and let the user do that 
themselves but since we already handled text alignment in numeric cells I thought we keep it around
Previously, `overflow: hidden` on the cell prevented us from placing the focused corner tag on top of border but with this change where we replace overflow with `clip-path` and now it is possible.
=> [ag-grid-theme] Separate generic numeric and editable cell classes, and fix corner tag

packages/grid/stories/grid-editableCells.stories.tsx, packages/grid/stories/grid-pagination.stories.tsx, packages/grid/stories/grid-serverSideData.stories.tsx
This was causing the grid not being visible on first load on some stories
=> [Data Grid] Add css import on the missing stories 

.changeset/fuzzy-foxes-grin.md, packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
We want to avoid breaking changes for now so I added back the `.editable-numeric-cell` in ag-grid theme. The two new class names can be used in tandem.
=> [ag-grid theme] Add back .editable-numeric-cell 

.changeset/bright-hats-argue.md, packages/theme/css/foundations/shadow.css
The spread has the old spec value of 5px, needs replacing to be consistently 0 across shadows
=> Tweak shadow-5 token

.changeset/shy-kids-cheer.md, packages/theme/css/foundations/fade.css, packages/theme/css/foundations/palette.css
Added `--salt-palette-opacity-background-readonly: var(--salt-opacity-1)`
Appropriate fade tokens now point to this bg
=> Add new opacity token in palette for readonly backgrounds

.changeset/seven-dogs-repeat.md, packages/ag-grid-theme/css/uitk-ag-theme.scss
The `list-item-height` variable was set to 60px (same height as "touch" density) for HD.
This was making the dropdown element inside the floating filter taller than it should be in HD.
=> Fix ag-grid uitk theme floating filter input height in High density

.changeset/orange-sloths-count.md, packages/theme/css/foundations/palette.css
Warning foreground and border tokens in light mode now use `--salt-color-orange-700` to fix accessibility issue found in data grid work
=> Palette warning token change

.changeset/smooth-rules-drum.md, packages/theme/css/foundations/palette.css
Success foreground and border tokens in dark mode now use `--salt-color-green-400` to fix accessibility issue found in data grid work
=> Palette success token change

.changeset/odd-wasps-eat.md, packages/lab/src/logo/Logo.css, packages/theme/css/foundations/size.css, packages/theme/stories/foundations/size.stories.mdx
Alignment of naming conventions
Deprecated `--salt-size-divider-height`, `--salt-size-divider-strokeWidth`, replaced with `--salt-size-separator-height`, `--salt-size-separator-strokeWidth`
=> Replace size divider tokens with separator

.changeset/poor-lions-hear.md, packages/core/src/__tests__/__e2e__/flex-item/FlexItem.cy.tsx, packages/core/src/__tests__/__e2e__/flex-layout/FlexLayout.cy.tsx, packages/core/src/flex-item/FlexItem.css, packages/core/src/flex-item/FlexItem.tsx
Without the basis, need to use `style` to give flex basis for simple 2 column layout like below
For the 2nd row, i'm can't get input / form field to be exactly half of the space
```
<FlexLayout gap={1}>
{/* without flexBasis input will be bigger than the empty space */}
<FlexItem grow={1} shrink={1} style={{ flexBasis: 1 }}>
<FormField label="Decimal">
<Input />
</FormField>
</FlexItem>
<FlexItem grow={1} shrink={1}></FlexItem>
</FlexLayout>
```
=> Add `basis` to FlexItem

site/docs/components/_index/ComponentsList.tsx
On [component status page](https://www.saltdesignsystem.com/components/), when sorting by "React", it's quite confusing to see "Released in v1.1.0" is mixed with "Released in v1.0.0".
Redo #1187
=> Sort component status table with version number

.changeset/happy-hats-argue.md, packages/lab/src/__tests__/color-chooser/Color.spec.ts, packages/lab/src/__tests__/color-chooser/ColorHelpers.spec.ts, packages/lab/src/__tests__/color-chooser/color-utils.spec.tsx, packages/lab/src/color-chooser/Color.ts, packages/lab/src/color-chooser/ColorHelpers.ts, packages/lab/src/color-chooser/color-utils.ts
Currently when choosing color using `ColorChooser`, `Color` object doesn't contain color name (e.g. orange 700) even if picking color from the swatches.  Adding `colorName` so at least there is a way to get the information when needed.
Also fixed `isTransparent` so any hex with `00` alpha value will return true.
Redo of #1240
=> Add colorName to Color

.storybook/preview.tsx, packages/core/stories/border-item/border-item.stories.tsx, packages/core/stories/border-layout/border-layout.stories.tsx, packages/core/stories/flex-item/flex-item.stories.tsx, packages/core/stories/flex-layout/flex-layout.stories.tsx, packages/core/stories/flow-layout/flow-layout.stories.tsx, packages/core/stories/grid-item/grid-item.stories.tsx, packages/core/stories/grid-layout/grid-layout.stories.tsx, packages/core/stories/split-layout/split-layout.stories.tsx, packages/core/stories/stack-layout/stack-layout.stories.tsx
Remove default `as` from the storybook preview controls and add the type in the ones that have the prop.
=> Remove default as in storybook controls

.github/workflows/snapshot.yml
This PR removes the changesets action from the snapshot workflow.
The changesets action does too much here and tries to create a PR and do the normal release workflow. This isn't needed in a snapshot workflow.
=> Remove changesets action from snapshot workflow

packages/lab/stories/checkbox/checkbox.doc.stories.mdx, packages/lab/stories/checkbox/checkbox.stories.tsx
This fixes an omission of the `aria-label` attribute on the example `WithoutLabel`
=> Make the Checkbox WithoutLabel example accessible

.changeset/real-numbers-shake.md, .changeset/tasty-goats-applaud.md, packages/core/src/__tests__/__e2e__/text/Text.cy.tsx, packages/core/src/text/Text.css, packages/theme/css/characteristics/text.css
1. `--salt-text-fontFamily` was not applied on text components at all, so add it to `.saltText` with test
2. Adds new variables like `--salt-text-h1-fontFamily` which bridges to default text one. This is useful for code generator tool which generates CSS automatically from design softwares like Figma, or design tokens typography definitions (e.g. [draft format#typography](https://design-tokens.github.io/community-group/format/#typography)) where font family is defined together with other text properties like font size, font weight, line height.
Open for alternative suggestion on 2nd point
Redo of #1265
=> Font family on text component

.changeset/ten-ducks-dream.md, packages/lab/src/__tests__/__e2e__/dropdown/Dropdown.cy.tsx, packages/lab/src/dropdown/useDropdownBase.ts
Currently the focus ring won't show up when focused
e.g. the story here: https://storybook.saltdesignsystem.com/?path=/story/lab-dropdown--with-form-field-label-top
=> Fix focus ring doesn't show up when Dropdown is wrapped in Form Field

.changeset/blue-mangos-ring.md, packages/lab/src/app-header/AppHeader.css, packages/lab/src/tabs/Tab.css, packages/lab/src/tabs/TabActivationIndicator.css, packages/lab/src/tabs/Tabstrip.css, packages/lab/src/toolbar/Toolbar.css
Currently Tab is very misaligned within App Header. Try to do some *minimal* change to make it usable
- Center align toolbar items vertically instead of using margin top
- Adjust tab activation indicator css api to support app header hiding the line but not the thumb
=> Improve Tabs alignment in AppHeader

.changeset/polite-windows-tap.md, packages/core/src/avatar/Avatar.css, packages/icons/src/icon/Icon.css, packages/theme/css/foundations/icon.css, packages/theme/stories/foundations/icon.stories.mdx, site/src/components/accordion/Accordion.module.css, site/src/components/getting-started/develop-fonts-accordion/DevelopFontsAccordion.module.css, tooling/stylelint/custom-property-no-foundations/index.js
Deprecated `--salt-size-icon-base`, replaced with `--salt-icon-size-base` (aligns with design, and follows pattern of starting with foundation name)
Added `--salt-icon-size-status-adornment`
=> Icon size token changes

packages/lab/src/common-hooks/useCollectionItems.ts, packages/lab/stories/combobox/combobox.stories.tsx
Closes #1404
setFilterPattern in useCollectionItems was referencing collection data via a ref. That ref is not updated when change to source triggers rebuild of collection.
No reason not to reference the collection directly, with the appropriate entry in dependency array.
=> Fix Combo Box filtering bug

.changeset/friendly-impalas-explode.md, packages/core/src/__tests__/__e2e__/tooltip/Tooltip.cy.tsx, packages/core/src/tooltip/Tooltip.css
When tooltip is used in heading tags, text is not showing default sizes. 
```
<h3>
Header{' '}
<Tooltip open content="Tooltip">
<InfoIcon />
</Tooltip>
</h3>
```
Reproduce: https://stackblitz.com/edit/salt-1-2-0-tooltip-in-heading?file=App.tsx
Redo #1238
=> Fix Tooltip using default text styles

site/src/components/app-header/AppHeader.module.css
=> Prevent AppHeader links from wrapping 

.changeset/gentle-geese-smile.md, packages/core/src/tooltip/Tooltip.tsx
Update Tooltip props to account for new content attribute introduced in new react types version.
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3f5d20608d31363487694535189ef64569043ff9
=> Update Tooltip props to account for new content attribute

.changeset/forty-toes-type.md, packages/lab/src/form-field-context-next/FormFieldContextNext.ts, packages/lab/src/form-field-next/FormFieldHelperText.tsx, packages/lab/src/form-field-next/FormFieldLabel.tsx, packages/lab/src/form-field-next/FormFieldNext.tsx, packages/lab/src/index.ts, packages/lab/src/input-next/InputNext.tsx
Fixed ids in `FormFieldLabel` and `FormFieldHelperText` from useFormFieldPropsNext
Deleted `a11yValueAriaProps`, replaced `a11yProps` type with `A11yValueProps` in `FormFieldContextNext`
=> Fix ids in label and helper text of FF Next

.changeset/cuddly-cups-judge.md, packages/core/src/input/Input.tsx
Makes it consistent with the impl of `aria-labelledby`
=> Input: merge aria-describedby prop from FF context and input props

packages/window/src/WindowProvider.tsx
I spotted a bug (I think) in the `WindowProviderProps` interface while trying to resolve some Salt site build issues. It extends `WindowContextType` (which is currently just an alias for `Window`) and therefore includes all the Window properties. Presumably that was not the intent, and what's actually needed is just a `window` prop, whose type is `WindowContextType`. (Note, this has gone unnoticed so far because the `Window` interface happens to have a `.window` property whose type is `Window & typeof globalThis` and therefore compatible with `Window`)
This PR corrects that.
However, I think this will once again break the Salt site builds. Since a static HTML representation of each page is generated at build time, there is no `Window` object, since the React components are being rendered …
=> Fixes WindowProvider props so that they don't extend from Window

site/src/_index/accordion/Accordion.module.css, site/src/components/card/Card.module.css, site/src/components/card/Card.tsx, site/src/css/base/base.css, site/src/pages/index.module.css, site/src/pages/index.tsx
The cards on our site's homepage have turned white. This fixes that.
The root cause is as follows:
* The website's `Card` component (which is _not_ the Salt core `Card` at the moment), was using `useTheme()` to determine light/dark mode and then adding extra CSS classes to change the colors
* For some weird reason, that call to `useTheme()` on the homepage was incorrectly reporting `light`, when it was actually meant to be `dark`, so the wrong card styles were applied. (Weirdly, the elements rendered to the DOM _do_ actually set a `data-mode="dark"` attribute, so as far as CSS is concerned, dark mode is in effect)
My fix removes that JS code and instead leans on our CSS custom properties to apply the correct light/dark styling. Our homepage actually uses some bespoke colors, so I'm doing …
=> Fix homepage card styling regressions on website

site/src/components/getting-started/icons-table/IconsTable.module.css
Closes #1441
A minor fix to the table, previously a scroll pane was added to scroll the table on small screens but this created more issues around accessibility. 
This PR changes the table to a fixed layout so it scales with screen size
=> Fix icons table on the site

.changeset/clever-cobras-crash.md, packages/core/src/checkbox/Checkbox.tsx, packages/core/src/checkbox/CheckboxGroup.tsx, packages/core/src/checkbox/CheckboxIcon.css, packages/core/src/checkbox/CheckboxIcon.tsx, packages/core/src/checkbox/internal/CheckboxGroupContext.ts, packages/core/src/radio-button/RadioButton.tsx, packages/core/src/radio-button/RadioButtonGroup.tsx, packages/core/src/radio-button/RadioButtonIcon.css, packages/core/src/radio-button/RadioButtonIcon.tsx, packages/core/src/radio-button/internal/RadioGroupContext.tsx, packages/core/stories/checkbox/checkbox.doc.stories.mdx, packages/core/stories/checkbox/checkbox.stories.tsx, packages/core/stories/radio-button/radio-button.doc.stories.mdx, packages/core/stories/radio-button/radio-button.stories.tsx
Added `validationStatus` prop to RadioButton and Checkbox allowing for error and warning status, added `validationStatus` to group context
Deprecated `error` prop in RadioButton and Checkbox
=> Add warning to Checkbox and RadioButton

.changeset/new-brooms-punch.md, packages/data-grid/src/DropdownCellEditor.tsx
this change avoids showing a dropdown in a cell editor when there is no source or the source is empty
=> Fix Data Grid Dropdown showing when there are no list items

.changeset/mighty-turkeys-join.md, packages/core/src/stack-layout/StackLayout.tsx, packages/core/src/utils/useResponsiveProp.ts
Prevents grid (and probably others that use responsiveProps)from ignoring some breakpoints if they don't come in the right order.
=> Fix breakpoints being ignored if they are out of order

site/docs/components/button/examples.mdx, site/src/components/components/ExamplesListView.tsx, site/src/components/components/LivePreview.tsx, site/src/components/components/LivePreviewControls.tsx, site/src/components/components/formatComponentExampleName.ts, site/src/layouts/DetailComponent/MobileDrawer.module.css
- Add optional `title` prop to `LivePreview` component to allow users to customise the title that is displayed for each example. This will default to the example file name if not provided and will also allow for a cleaner `examples.mdx`
- Add missing `value` to mode toggle button
- Amend mobile drawer transition speed
- Preview at https://saltdesignsystem-git-live-preview-tweaks-joshwooding.vercel.app/salt/components/button/examples
=> Allow site component examples title to be customised

README.md
Firefox version is not an accurate description on what's supported by our code, e.g. css gap, focus visible.
It's better we put it back once true version support is defined by product
=> Remove browser versions from README.md

packages/theme/css/foundations/palette.css
Very minor; but these weren't moved in the PR when they were deprecated
Moving them makes it clearer
Already documented as deprecated
=> Move palette negative/positive tokens to deprecated section 

.changeset/short-shrimps-reflect.md, packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss
add `ag-standard-button` styles to salt-ag-theme
path to see changes: 
https://31a01c59.saltdesignsystem-storybook.pages.dev/?path=/story/data-grid-ag-grid-theme--basic-grid
=> Fix button styling in ag grid filter panel

site/docs/components/index.mdx, site/src/pages/index.tsx
The roadmap page moved to the about section and this broke a couple of internal links. This PR fixes that.
=> fixes links to roadmap page

.changeset/hungry-toes-beam.md, packages/core/package.json, packages/countries/package.json, packages/data-grid/package.json, packages/icons/package.json, packages/lab/package.json, packages/styles/package.json, packages/window/package.json, yarn.lock
The various Salt packages incorrectly list React 16.8.0 as their minimum version. However, our code relies on the JSX transform, which was not added until 16.14.0.
Therefore, consumers who try to use Salt with React 16.8.0 - 16.13.x will encounter build errors. At least one consumer is known to have been tripped up by this.
This PR corrects our dependencies.
=> Corrects min. React 16 version in package dependencies

site/docs/components/index.mdx, site/src/components/components/ComponentsList.module.css
The "Need a component that's not listed? ..." text on the components page currently appears in bold & italic, which contradicts our own Typography foundations guidance.
This PR therefore:
* Places that text into a callout instead
* Adds a heading above the components table, to help separate it from the callout above
=> Component page text tweaks

.changeset/twelve-rabbits-pretend.md, packages/core/src/card/InteractableCard.css, packages/core/src/card/InteractableCard.tsx
This updates interactable card to follow our best practices so that it does not depend on card. This was causing an issue in production build, where the styles would clash.
=> Fix interactable card styling

packages/lab/stories/parent-child-layout/parent-child-layout.doc.stories.mdx
Stack example is not loading on [parent child doc](https://storybook.saltdesignsystem.com/?path=/story/documentation-lab-layout-parent-child-layout--page).
To check: fixed in preview doc: https://a6cc41ce.saltdesignsystem-storybook.pages.dev/?path=/docs/documentation-lab-layout-parent-child-layout--page
=> Fix not loading parent child doc story

.changeset/rich-horses-tie.md, packages/lab/src/list-next/ListNext.tsx, packages/lab/src/list-next/useList.ts, packages/lab/stories/list-next/list.stories.tsx
In this PR: 
- The previous change in useList meant that any key not purposefully declared in the hook would be prevented to do it's default, which meant `Tab` had to be explicitly declared.
- exposing `setSelectedItem` and `setHighlightedItem` for controlled usage.
- since `keydownHandler` is not guaranteed to be in a list when controlled, changed type
- The hook is setting highlighted when selected, so the example doesn't need to do it anymore.
- setting selectedItem on input change in the example so deleting from the input deletes the selection.
=> ListNext fix keyboard nav and expose hook setters

.gitignore, site/.env.local, site/.gitignore, site/docs/about/supported-platforms.mdx, site/docs/getting-started/supported-platforms.mdx
Added a page which describes the `Supported Platforms`, this page can be used to describe browser and platform versions.
Initially just a placeholder to align us all on the minimum browser versions.
Whilst creating this page, noticed that `active` mode was not supported by the site, so you had to change the snapshots to edit a page. With the `.env.local` file, you can not edit the page sources, locally and refresh the browser.
Also, noticed the IntelliJ (.idea) files were not ignored correctly
=> Add supported platform docs

.changeset/dull-goats-vanish.md, packages/lab/src/progress/LinearProgress/LinearProgress.css, packages/lab/src/progress/LinearProgress/LinearProgress.tsx, packages/lab/stories/progress/circular-progress.stories.tsx, packages/lab/stories/progress/linear-progress.stories.tsx
Fix to stop the progress bar from disappearing on reset (instead of animating back to the start)
=> Fix Linear Progress's bar not animating to the beginning on reset

packages/core/stories/form-field/form-field.stories.tsx
Left group was using right alignment
=> Fix form field group left label example

.changeset/new-colts-march.md, packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss, packages/ag-grid-theme/css/salt-ag-theme.scss, packages/ag-grid-theme/stories/ag-grid.stories.tsx, packages/ag-grid-theme/stories/dependencies/dataGridExampleColumnsWrap.ts, packages/ag-grid-theme/stories/examples/WrappedHeader.tsx, packages/ag-grid-theme/stories/examples/index.ts
closes #2074 
Also fixes 
- Floating filter height (gap between border and cell height)
- Adds a story for wrapped header text
=> Column separator height fix ag-grid theme

site/src/css/utilities/index.css, site/src/css/utilities/patches.css
Adds a temporary CSS workaround for Mosaic CSS which is inverting images on our site. Once they release a fix, we can remove this again.
=> Fix inverted images on Salt site

packages/lab/src/__tests__/__e2e__/dropdown-next/DropdownNext.cy.tsx, packages/lab/src/dropdown-next/DropdownNext.css, packages/lab/src/dropdown-next/DropdownNext.tsx, packages/lab/stories/dropdown-next/dropdown-next.doc.stories.mdx
closes #2179 
- make readonly dropdown focusable
- add box-shadow to dropdown list
- remove padding-right for readonly dropdown as no dropdown button icon present
- update cypress
=> DropdownNext V1: make readonly dropdown focusable; css updates

.changeset/chilled-jeans-hear.md, .changeset/chilly-buttons-agree.md, packages/theme/css/deprecated/foundations.css, packages/theme/css/foundations/size.css, site/docs/foundations/size.mdx
`size-indicator` is needed for navigation item and tabs. Whilst I was there I moved the old size tokens out of the main file
Closes ##2121
=> Add `--salt-size-indicator` and deprecate some size tokens

.changeset/cuddly-kings-count.md, .changeset/late-beds-melt.md, packages/ag-grid-theme/css/_salt-ag-theme-mixin.scss, packages/ag-grid-theme/css/_uitk-ag-theme-mixin.scss, packages/ag-grid-theme/css/salt-ag-theme.scss, packages/ag-grid-theme/css/uitk-ag-theme.scss
`box-sizing: border-box;` is already in ag grid default theme.
=> Removed extra CSS from the ag-grid theme

site/docs/components/button/accessibility.mdx, site/docs/components/button/examples.mdx, site/docs/components/button/usage.mdx, site/docs/components/progress/accessibility.mdx, site/docs/components/progress/examples.mdx, site/docs/components/progress/usage.mdx, templates/component-pages/component-name/accessibility.mdx, templates/component-pages/component-name/examples.mdx, templates/component-pages/component-name/usage.mdx
Updates the pre-existing component pages and template MDX files, to prevent the per-tab sub-pages from appearing in the left-hand nav.
Note: The left hand nav may appear blank on fresh page loads. This is due to a Mosaic bug, for which a fix has been prepared.
=> Excludes component tab pages from sidebar

site/docs/components/border-layout/accessibility.mdx, site/docs/components/border-layout/examples.mdx, site/docs/components/border-layout/index.mdx, site/docs/components/border-layout/usage.mdx, site/src/examples/border-layout/BorderItemAlignment.module.css, site/src/examples/border-layout/BorderItemAlignment.tsx, site/src/examples/border-layout/BorderItemPosition.module.css, site/src/examples/border-layout/BorderItemPosition.tsx, site/src/examples/border-layout/CustomRegionSize.tsx, site/src/examples/border-layout/Default.tsx, site/src/examples/border-layout/GapBetweenRegions.tsx, site/src/examples/border-layout/HideRegions.module.css, site/src/examples/border-layout/HideRegions.tsx, site/src/examples/border-layout/StickyPositioning.module.css, site/src/examples/border-layout/StickyPositioning.tsx, site/src/examples/border-layout/index.module.css, site/src/examples/border-layout/index.ts
Adds the `BorderLayout` docs and examples to the site
Preview at: https://saltdesignsystem-git-border-layout-docs-fed-team.vercel.app/salt/components/border-layout/examples
=> Border layout site docs

site/next.config.js, site/package.json, site/src/components/components/LivePreview.tsx, yarn.lock
- Replace `reactElementToJSXString` with webpack's `raw-loader` which will render the whole example file as a string (not just the output)
- Enable webpack's optimisation on the site
- Preview at https://saltdesignsystem-git-replace-react-element-to-jsx-fed-team.vercel.app/salt/components/accordion/examples (any component)
=> Fix examples code preview on the site docs

.changeset/sour-fireants-crash.md, packages/core/src/grid-layout/GridLayout.tsx
Fixing bug in GridLayout where columnGap/rowGap couldn't be set to zero, as logic was determining zero as falsey causing the default (non-zero) value to be used
=> fix bug in GridLayout where columnGap and rowGap couldn't be zero

.changeset/bright-tips-tell.md, packages/icons/src/icon/Icon.css, packages/icons/src/icon/Icon.tsx, site/docs/components/icon/examples.mdx, site/src/examples/icon/IconColor.tsx
This PR adds a color prop to Icon that supports: primary, secondary and inherit.
There should be another PR to align Text. 
But the reason for this change is to make working with Icon a lot easier, usually Icon will always following the text colour used and currently we have to be very explicit when trying to achieve this. Changing Icon to inherit the text colour by default would reduce a lot of extra code and improve compatibility with the UITK button
=> Add a color prop to Icon

.changeset/young-timers-explain.md, packages/core/src/form-field/FormField.css
closes #2497
ideally would use :has selector instead
Note that the same would apply above if no label is provided. I've only added the fix for helper text. I don't see why a label wouldn't be provided, the control would probably just be used itself in that case?
=> Fix FormField adds extra "padding" below the input

.github/workflows/release.yml
Trying to fix... 
Storybook deployment has failed several times: https://github.com/jpmorganchase/salt-ds/actions/runs/6383223367/job/17323441709
=> Add deployments permission to release

.github/workflows/release.yml
There are changes not appearing on storybook (e.g. https://github.com/jpmorganchase/salt-ds/issues/2546#issuecomment-1746647636), we're publishing site on every main commit, doing same for storybook. Can revert back when things are stable.
=> Publish Storybook on every commit on main

packages/lab/src/combo-box-next/ComboBoxNext.css, packages/lab/src/dropdown-next/DropdownNext.css
Both Dialog and ComboboxNext / DropdownNext use floating-ui Portal therefore they are competing for z-index and Dialog is using a higher z-index.  https://github.com/jpmorganchase/salt-ds/issues/2495
Change makes the ComboboxNext / DropdownNext z-index greater than the Dialog.
If a user opens dropdown / combobox and then a dialog, it would be considered a click away and therefore closing the dropdown or combobox avoiding the unwanted scenario where a dropdown / combobox in the background takes precedence over a dialog.
Alternatively the z-index of Dialog could be decreased, but i thought the above method made more sense.
=> Dropdown / Combobox renders behind Dialog

.changeset/itchy-kids-tell.md, .changeset/stupid-tools-sing.md, packages/core/src/utils/useId.ts, packages/styles/src/use-style-injection/useStyleInjection.ts
Fixes #2567
Issue raised when app is using a library re-bundling Salt.
- Reference https://github.com/webpack/webpack/issues/14814#issuecomment-1536757985
Thanks to @DavieReid suggesting the fix
----
Tested [snapshot release](https://github.com/jpmorganchase/salt-ds/pull/2561#issuecomment-1750756560) with CTA@5 & React@17
=> Fix `useId`, `useInsertionEffect` not found error when used by webpack

site/src/examples/badge/InlineBadge.tsx
```
site ➤ yarn build                                                                                                                               git:main*
Skipping linting
Checking validity of types .Failed to compile.
./src/examples/badge/InlineBadge.tsx:7:5
Type error: Type '{ children: Element[]; defaultSelected: string; style: { maxWidth: number; }; }' is not assignable to type 'IntrinsicAttributes & TabstripNextProps & RefAttributes<HTMLDivElement>'.
Property 'defaultSelected' does not exist on type 'IntrinsicAttributes & TabstripNextProps & RefAttributes<HTMLDivElement>'.
5 | export const InlineBadge = (): ReactElement => (
6 |   <TabstripNext
>  7 |     defaultSelected="Home"
|     ^
8 |     style={{
9 |       maxWidth: 400,
10 |     }}
Checking validity of types .% …
```
=> Fix invalid Tabnext prop on site example

.storybook/main.ts
This seems to fix below error
```
WARN   Failed to load preset: {"name":"/Users/zhihaocui/projects/salt-ds/node_modules/@storybook/addon-storysource/preset.js"} on level 2
./node_modules/@storybook/addon-storysource/preset.js:1
import './dist/preset';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at internalCompileFunction (node:internal/vm:73:18)
at wrapSafe (node:internal/modules/cjs/loader:1176:20)
at Module._compile (node:internal/modules/cjs/loader:1218:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Object.newLoader (./node_modules/@storybook/core-common/node_modules/esbuild-register/dist/node.js:2262:9)
at extensions..js (./node_modules/@storybook/core-common/node_modules/esbuild-register/dist/node.js:4838:24)
at Module.load …
```
=> Update storysource addon syntax

.changeset/olive-laws-vanish.md, packages/core/src/__tests__/__e2e__/viewport-provider/ViewportProvider.cy.tsx, packages/core/src/viewport/ViewportProvider.tsx
This PR ensures Viewport is read and set immediately. Previously, Viewport was sometimes 0 initially causing a flash of layouts.
=> Viewport provider fix

packages/core/src/__tests__/__e2e__/viewport-provider/ViewportProvider.cy.tsx
Previous test fails in almost all the runs (1 in 3 react versions)
=> Make ViewportProvider test more stable

.changeset/rich-bats-breathe.md, packages/core/src/checkbox/Checkbox.css, packages/core/src/radio-button/RadioButton.css
Should solve immediate issue for radio button #2671
Still need better way to test across all components. Maybe add this to our storybook, to make sure things still work
```
body {
font-weight: 400;
font-family: some-other-font;
font-size: 14px;
line-height: 1.85714286em;
}
```
=> Fix RadioButton and Checkbox not using default Salt text properties

packages/core/stories/accordion/accordion.qa.stories.tsx, packages/core/stories/avatar/avatar.qa.stories.tsx, packages/core/stories/banner/banner.qa.stories.tsx, packages/core/stories/button/button.qa.stories.tsx, packages/core/stories/card/card.qa.stories.tsx, packages/core/stories/checkbox/checkbox.qa.stories.tsx, packages/core/stories/form-field/form-field.qa.stories.tsx, packages/core/stories/input/input.qa.stories.tsx, packages/core/stories/link/link.qa.stories.tsx, packages/core/stories/multiline-input/multiline-input.qa.stories.tsx, packages/core/stories/multiline-input/multiline-input.stories.tsx, packages/core/stories/panel/panel.qa.stories.tsx, packages/core/stories/radio-button/radio-button.qa.stories.tsx, packages/core/stories/spinner/spinner.qa.stories.css, packages/core/stories/spinner/spinner.qa.stories.tsx, packages/core/stories/spinner/spinner.stories.tsx, packages/core/stories/status-indicator/status-indicator.qa.stories.tsx, packages/core/stories/switch/switch.qa.stories.tsx, packages/core/stories/text/text.qa.stories.tsx, packages/core/stories/toast/toast.qa.stories.tsx, packages/core/stories/toggle-button-group/toggle-button-group.qa.stories.tsx, packages/core/stories/toggle-button/toggle-button.qa.stories.tsx, packages/core/stories/tooltip/tooltip.qa.stories.tsx
Add missing QA stories to core components, so can do comparison in #2679
I specifically named all group name as `<Component> QA` so it's much clearer on Chromatic which component contains change
=> Add QA stories to all core components

.changeset/ten-humans-train.md, packages/core/src/tooltip/Tooltip.css, packages/core/stories/tooltip/tooltip.qa.stories.tsx
=> Fix Tooltip status icon alignment

.changeset/ninety-queens-retire.md, packages/lab/src/combo-box-next/ComboBoxNext.tsx
Fix issue where combobox onChange was lagging behind the text typed into the combobox by one render. 
This was caused by sending inputValue to the onInputChange callback which had been set via setInputValue, but won't be updated till the next render.
Instead this change passes the value from event/target.value which will be the updated value.
=> Fix Combo Box Next `onChange` using stale values

.changeset/empty-gorillas-lie.md, packages/lab/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx, packages/lab/src/__tests__/__e2e__/combo-box/ComboBox.keyboardNavigation.cy.tsx, packages/lab/src/combo-box/useCombobox.ts, packages/lab/stories/combobox/combobox.stories.tsx
Adds minimal change to old combobox, so it can be a stop gap solution for controlled usage
=> Fix Combobox input's `onChange` and `onKeyDown` not invoked

site/mosaic.config.js, site/package.json, site/src/layouts/DetailBase/DetailBase.module.css, site/src/layouts/DetailBase/DetailBase.tsx, site/src/layouts/DetailComponent/DetailComponent.tsx, site/src/layouts/types/index.ts, site/src/mosaic-plugins/ChildrenDocPaginatorPlugin.mjs, site/src/mosaic-plugins/ComponentsDocPaginatorPlugin.mjs
- Stack "Lab Component" badge on mobile. To test, go to dropdown component page on mobile viewport.
- Add missing footer prev/next navigation links on component pages, so it's navigable on mobile.
- Use `replace` instead of `push` to redirect from `<Component>/index` to `<Component>/examples`, so that browser back button will not always circulate back to index.
closes #2712
=> Fix component doc lab badge and missing next / prev bottom navs

.changeset/orange-bulldogs-glow.md, .changeset/young-pets-exist.md, .storybook/styles.css, docs/components/QAContainer.css, packages/ag-grid-theme/stories/examples/StatusBar.tsx, packages/ag-grid-theme/stories/examples/StatusBarDark.tsx, packages/core/src/avatar/Avatar.css, packages/core/src/badge/Badge.css, packages/core/src/banner/Banner.css, packages/core/src/card/Card.css, packages/core/src/form-field/FormField.css, packages/core/src/panel/Panel.css, packages/core/src/switch/Switch.css, packages/core/src/text/Text.css, packages/core/src/toast/Toast.css, packages/core/src/tooltip/Tooltip.css, packages/core/stories/badge/badge.qa.stories.tsx, packages/lab/src/content-status/ContentStatus.css, packages/lab/src/dialog/Dialog.css, packages/lab/src/dialog/DialogContent.css, packages/lab/src/form-field-legacy/FormFieldLegacy.css, packages/lab/src/list-next/ListNext.css, packages/lab/src/list/List.css, packages/lab/src/tabs-next/TabstripNext.css, packages/lab/src/tabs/Tab.css, packages/lab/src/toolbar/Toolbar.css, packages/lab/stories/form-field-legacy/form-field.stories.tsx, site/src/examples/ag-grid-theme/StatusBar.tsx
Added text styles appearing in UITK's `body` to storybook (not website), so all subsequent components we're working on will have that checked out. 
Try to fix all core component's defect as well in this PR, mostly rely on Chromatic snapshot comparison.
Given Chromatic snapshot are rendered using `QAContainer`, which has `SaltProvider` wrapped inside, additional `body` styles will not be taken effect (unlike the order of`:root.salt-theme body`). So I also added additional text styles to `QAContainer` as well (`.background-item-wrapper`)
#2671
Add default text styles to a fixed global className (similar to `.saltFocusVisible`), add apply that to components needed.
I didn't choose this with 2 reasons
1. Not all components needs the same default, e.g. for Button, which becomes an override of …
=> Fix Salt / UITK text property compatibility

site/src/components/components/PropsTable.tsx, site/src/components/mdx/code/Code.module.css, site/src/layouts/DetailComponent/DetailComponent.tsx, site/src/layouts/DetailComponent/SecondarySidebar.tsx
Fix code element font family:
Before:
After:
Use PillNext:
Before:
After:
=> Add Markdown support to component descriptions, use PillNext for tags and fix code element font family

site/src/components/keyboard-controls/KeyboardControl.tsx
Currently, alternate key combinations provided to the `<KeyboardControl>` component (which is used on the site's component pages in the accessibility tab) need to be separated by a slash (`/`). Based on a discussion with @mikearildbrown, we decided it would be more readable if we used the word "or" instead.
This PR allows you to use `/` or `or`, so that existing docs which all use `/` continue to work. However, they can now gradually be updated to use `or` instead.
=> Updated KeyboardControl site component to allow alternate keycombos to be separated by "or"

site/docs/patterns/dashboards/index.mdx
Update nav link to `/salt/patterns/dashboards/analytical-dashboard`
=> fix dashboard pattern link

.changeset/plenty-hotels-obey.md, packages/core/src/__tests__/__e2e__/form-field/FormField.cy.tsx, packages/core/src/tooltip/Tooltip.tsx
=> Fix Tooltip breaking when used inside a Form Field with an invalid value passed to the `validationStatus` prop

.changeset/thin-yaks-rush.md, packages/core/src/salt-provider/SaltProvider.tsx, packages/core/stories/style-injection/style-injection.default.stories.tsx, packages/core/stories/style-injection/style-injection.disabled.stories.tsx, packages/core/stories/style-injection/style-injection.enabled.stories.tsx, packages/styles/src/style-injection-provider/index.tsx
Root `StyleInjectionProvider` overrides nested `StyleInjectionProvider`
=> Fix nested Salt Providers not inheriting a parent provider's `enableStyleInjection` value

.changeset/old-weeks-travel.md, packages/lab/src/color-chooser/ColorPicker.css, packages/lab/src/color-chooser/ColorPicker.tsx
When using Salt with static css, including the entire labs css package surfaced an issue where ColorPicker adds two unprefixed classes .root and .rootDisabledAlpha which are causing global css clashes.
=> Remove unprefixed classnames from ColorPicker

site/src/components/keyboard-controls/KeyboardControls.module.css
This PR adds styling to the keys in the keyboard controls table (used on the component docs pages), so they look like keys. 
I added it while working on App Header pattern it's not really needed as part of that, so raising a separate PR since I've done it anyways and (I think) it looks nice.
=> Style Keys in Keyboard Accessibility Table

.changeset/chilled-wombats-marry.md, packages/theme/css/foundations/fade.css
This PR adds a definition for `--salt-color-white-fade-backdrop` which is currently not defined.
Noticed this issue when looking at [Scrim](https://storybook.saltdesignsystem.com/?path=/story/lab-scrim--default). As you can see, it has no background colour when opened.
=> Update backdrop CSS tokens

.changeset/hot-teachers-know.md, packages/core/src/__tests__/__e2e__/common/CustomFloatingComponentProvider.tsx, packages/core/src/tooltip/Tooltip.tsx, packages/core/src/utils/useFloatingUI/useFloatingUI.tsx, packages/core/stories/floating-platform/custom-floating-ui-platform.stories.tsx, packages/lab/src/__tests__/__e2e__/common/CustomFloatingComponentProvider.tsx, packages/lab/src/combo-box-next/ComboBoxNext.tsx, packages/lab/src/dropdown-next/DropdownNext.tsx
FloatingComponent was typed with:
```ts
type CombinedFloatingComponentProps = PropsWithChildren<FloatingComponentProps>;
forwardRef<
HTMLElement,
CombinedFloatingComponentProps
>
Component: ForwardRefExoticComponent<CombinedFloatingComponentProps>;
```
Which allowed for incorrect refs to be passed and ignored that there is an assumption that the floating component will always be a `div`, making typing harder to do than necessary.
This PR tidies that up and fixes the code where FloatingComponent is already used.
=> Fix FloatingComponent types

.changeset/fresh-jars-attack.md, .eslintrc.js, packages/core/src/checkbox/Checkbox.tsx, packages/core/src/checkbox/CheckboxGroup.tsx, packages/core/src/input/Input.tsx, packages/core/src/multiline-input/MultilineInput.tsx, packages/core/src/radio-button/RadioButton.tsx, packages/core/src/radio-button/RadioButtonGroup.tsx, packages/core/src/switch/Switch.tsx, packages/core/src/tooltip/Tooltip.tsx, packages/core/src/utils/useFloatingUI/useFloatingUI.tsx, packages/lab/src/dropdown/DropdownBase.tsx, packages/lab/src/editable-label/EditableLabel.tsx, packages/lab/src/toolbar/overflow-panel/OverflowPanel.tsx, packages/lab/src/tree/Tree.tsx, packages/lab/stories/pagination/pagination.qa.stories.tsx, packages/lab/stories/pagination/pagination.stories.tsx
Reduces the likelihood of mistakes being made where using `??` would cause unwanted behaviour with booleans
=> Disable prefer nullish coalescing for expressions containing booleans

.changeset/lucky-yaks-shop.md, packages/core/src/card/Card.css, packages/core/src/panel/Panel.css
Fix issues introduced from #2671 #2679.
When Salt container component is used during UITK app migration, most content within containers will inherit text properties from `body` or `:root`. With the text properties set at container level, content will be reset to use Salt properties instead. In most cases, this is not the intended effect of these container components would behave.
=> Remove text properties from Card and Panel

.changeset/five-goats-joke.md, packages/data-grid/src/Grid.css, packages/data-grid/stories/grid-cellCustomization.stories.tsx, packages/data-grid/stories/grid-cellValidation.stories.tsx, packages/data-grid/stories/grid-columnGroups.stories.tsx, packages/data-grid/stories/grid-cssVariables.stories.tsx, packages/data-grid/stories/grid-editableCells.stories.tsx, packages/data-grid/stories/grid-headerCustomization.stories.tsx, packages/data-grid/stories/grid-pagination.stories.tsx, packages/data-grid/stories/grid-rowSelectionControlled.stories.tsx, packages/data-grid/stories/grid-rowSelectionModes.stories.tsx, packages/data-grid/stories/grid-serverSideData.stories.tsx, packages/data-grid/stories/grid-sortColumns.stories.tsx, packages/data-grid/stories/grid-variants.stories.tsx, packages/data-grid/stories/grid.doc.stories.mdx, packages/data-grid/stories/grid.stories.tsx
Data grid examples are not showing correct text properties (e.g. https://storybook.saltdesignsystem.com/?path=/story/data-grid-data-grid--cell-customization). Applying similar treatment from #2671 #2679.
Data gird is not receiving active development, so moving it away from ag grid theme in storybook to avoid confusion, although it's not documented on site.
=> Data grid uses text properties from theme and move doc to lab

.changeset/tender-baboons-walk.md, packages/core/src/__tests__/__e2e__/checkbox/Checkbox.cy.tsx, packages/core/src/__tests__/__e2e__/toggle-button/ToggleButton.cy.tsx, packages/core/src/checkbox/Checkbox.tsx, packages/core/src/link/Link.tsx, packages/core/src/radio-button/RadioButton.tsx, packages/core/src/radio-button/RadioButtonGroup.tsx, packages/core/src/switch/Switch.tsx, packages/core/src/toggle-button/ToggleButton.css, packages/core/src/toggle-button/ToggleButton.tsx, packages/core/src/tooltip/useTooltip.ts, site/docs/components/badge/accessibility.mdx, site/docs/components/badge/examples.mdx, site/src/examples/badge/BadgeWithMaximumDigits.tsx, site/src/examples/badge/BadgeWithString.tsx, site/src/examples/badge/Default.tsx
Fixes the following:
- Tooltip's being announced as focusable/clickable due to floating-ui adding tabIndex -1
- External link's having redundant screen reader text that announces Link.
- Read-only checkboxes/radio button's not being announced as such.
- Standalone ToggleButton group's being announced as checkboxes (not ideal but not that wrong).
- Checkbox and radio button not being announced as indeterminate.
- Switch's thumb being announced.
- Badge's not being announced in all of the examples.
=> Fix accessibility issues raised during the review.

.changeset/tiny-radios-exercise.md, packages/core/src/__tests__/__e2e__/multiline-input/MultilineInput.cy.tsx, packages/core/src/multiline-input/MultilineInput.css, packages/core/src/multiline-input/MultilineInput.tsx, packages/core/stories/multiline-input/multiline-input.stories.tsx, site/src/examples/multiline-input/Bordered.tsx, site/src/examples/multiline-input/NumberOfRows.tsx, site/src/examples/multiline-input/Primary.tsx, site/src/examples/multiline-input/Secondary.tsx
Adds resizing to MultilineInput. Resizing can be done two ways:
- As new lines are entered, the field's height increases.
- An end-user can drag the resize handle to resize the field vertically. After doing this, the field no longer adjusts based on the content of the field.
=> Add resizing support to MultilineInput

.changeset/chilly-dragons-unite.md, packages/lab/src/progress/CircularProgress/CircularProgress.css, packages/lab/src/progress/LinearProgress/LinearProgress.css, packages/lab/src/slider/Slider.css, packages/lab/src/stepped-tracker/TrackerConnector/TrackerConnector.css, packages/theme/CHANGELOG.md, packages/theme/css/characteristics/track.css, packages/theme/css/deprecated/characteristics.css
During the theme changes --salt-track-borderColor was incorrectly marked as deprecated. This PR reverts that.
=> Undeprecate --salt-track-borderColor

packages/core/stories/file-drop-zone/file-drop-zone.qa.stories.tsx
Noticed this when looking at #2977
=> Fix missing FileDropZone visual regression tests

.changeset/tasty-poets-matter.md, packages/core/src/form-field/FormField.css, packages/core/stories/form-field/form-field.stories.tsx, site/src/examples/form-field/GroupedWithEmptySlot.tsx, site/src/examples/form-field/GroupedWithMultipleColumns.tsx
The token should've followed the syntax used for CSS API variables as opposed to local tokens, creating an anomaly when trying to customize Form Field styling
--formField-label-width can be deprecated since we don't need it ourselves as a local token - I've kept it in to prevent breaking changes in case anyone used this token already. Usage should be replaced with the new API token
=> Deprecate --formField-label-width and replace with --saltFormField-label-width

packages/core/stories/accordion/accordion.stories.css, packages/core/stories/accordion/accordion.stories.tsx
Want to reuse stories for theme kitchen sink. Having `80vh` in story doesn't help to stack with others.
=> Update Accordion story to be not centered

.changeset/cuddly-hats-bake.md, packages/lab/src/__tests__/__e2e__/dialog/Dialog.cy.tsx, packages/lab/src/dialog/Dialog.tsx, packages/lab/src/dialog/DialogContent.css, packages/lab/src/dialog/DialogContext.tsx, packages/lab/src/dialog/DialogTitle.css, packages/lab/src/dialog/DialogTitle.tsx, packages/lab/stories/components/CloseTabWarningDialog.tsx, packages/lab/stories/dialog/dialog.qa.stories.tsx, packages/lab/stories/dialog/dialog.stories.css, packages/lab/stories/dialog/dialog.stories.tsx, site/docs/components/dialog/examples.mdx, site/src/examples/dialog/CloseButton.tsx, site/src/examples/dialog/Default.tsx, site/src/examples/dialog/DisableScrim.tsx, site/src/examples/dialog/Error.tsx, site/src/examples/dialog/Info.tsx, site/src/examples/dialog/MandatoryAction.tsx, site/src/examples/dialog/Sizes.tsx, site/src/examples/dialog/Subtitle.tsx, site/src/examples/dialog/Success.tsx, site/src/examples/dialog/Warning.tsx, site/src/examples/dialog/WithoutAccent.tsx, site/src/examples/dialog/index.ts
- Title and subtitle now passed via props to ensure consistent styling for the Title and Subtitle
- id attached to `Dialog` and passed to aria-labelledby to read out title and subtitle when using a screen reader
- tests added for `title` / `subtitle` props and `disableDismiss`
=> Dialog Title Refactor

site/src/examples/tabs/Inline.tsx
the example wrapper currently has no width set, which makes the tabstrip collapse
=> Fix example for inline tabstrip

.changeset/witty-flies-bake.md, packages/lab/src/tabs/Tab.tsx
Fixing issue where Tab could be deleting whilst editing label and pressing backspace. 
Referenced in issue https://github.com/jpmorganchase/salt-ds/issues/3036
=> Fix Tab deletion during editing

.changeset/smooth-bananas-know.md, packages/theme/css/characteristics/navigable.css
token refd deprecated value: --salt-palette-navigate-primary-background-hover
change to ref correct value: --salt-palette-navigate-background-hover
=> Fix --salt-navigable-background-hover referencing deprecated token

site/docs/patterns/selectable-card.mdx
This PR adds a link to the selectable card pattern storybook on the docs page.
=> Add link to examples for the selectable card pattern

.changeset/dry-pumpkins-battle.md, .changeset/shiny-bees-listen.md, packages/core/src/__tests__/__e2e__/breakpoint-provider/BreakpointProvider.cy.tsx, packages/core/src/__tests__/__e2e__/grid-layout/GridLayout.cy.tsx, packages/core/src/breakpoints/BreakpointProvider.tsx, packages/core/src/breakpoints/Breakpoints.tsx, packages/core/src/breakpoints/index.ts, packages/core/src/flex-item/FlexItem.tsx, packages/core/src/flex-layout/FlexLayout.css, packages/core/src/flex-layout/FlexLayout.tsx, packages/core/src/grid-item/GridItem.tsx, packages/core/src/grid-layout/GridLayout.css, packages/core/src/grid-layout/GridLayout.tsx, packages/core/src/index.ts, packages/core/src/salt-provider/SaltProvider.tsx, packages/core/src/salt-provider/matched-breakpoints.tsx, packages/core/src/stack-layout/StackLayout.css, packages/core/src/stack-layout/StackLayout.tsx, packages/core/src/utils/useResponsiveProp.ts, packages/core/stories/grid-layout/grid-layout.stories.tsx, site/docs/components/grid-layout/examples.mdx, site/src/examples/grid-layout/CustomColumnsAndRows.tsx, site/src/examples/grid-layout/index.ts
This moves us from using ViewportProvider and other logic when dealing with responsive props. Now at a provider level we calculate the matching breakpoints that allow components to get that list and check their props against them. 
There's a bit of duplication with how the breakpoints are handled in the code now, but the idea is that this would become the sole way and ViewportProvider should be removed in the next major.
=> Alternative responsive props

.changeset/violet-news-beg.md, packages/core/src/button/Button.css, packages/core/src/card/Card.css, packages/core/src/dialog/DialogHeader.css, packages/core/src/interactable-card/InteractableCard.css, packages/core/src/link-card/LinkCard.css, packages/core/src/tooltip/Tooltip.css, packages/core/stories/card/card.stories.css, packages/core/stories/layout/layout.stories.css, packages/core/stories/overlay/overlay.stories.css, packages/data-grid/src/Grid.css, packages/data-grid/src/HeaderCell.css, packages/data-grid/stories/grid.stories.css, packages/theme/css/deprecated/foundations.css
Noticed in Card that size-accent was being used which is deprecated; checked spec and it should be size-bar
This was the corresponding replacement noted in changelog - I changed all size-accent used in core components/data-grid to use size-bar
Also went ahead and changed size-unit (deprecated) to spacing-100 or corresponding multiplier
=> Fix usage of deprecated tokens in core and data-grid

packages/ag-grid-theme/stories/examples/CheckboxSelection.tsx, packages/ag-grid-theme/stories/examples/Coloration.tsx, packages/ag-grid-theme/stories/examples/ColumnGroup.tsx, packages/ag-grid-theme/stories/examples/ColumnSpanning.tsx, packages/ag-grid-theme/stories/examples/ContextMenu.tsx, packages/ag-grid-theme/stories/examples/CustomFilter.tsx, packages/ag-grid-theme/stories/examples/Default.tsx, packages/ag-grid-theme/stories/examples/DragRowOrder.tsx, packages/ag-grid-theme/stories/examples/FloatingFilter.tsx, packages/ag-grid-theme/stories/examples/HDCompact.tsx, packages/ag-grid-theme/stories/examples/Icons.tsx, packages/ag-grid-theme/stories/examples/InfiniteScroll.tsx, packages/ag-grid-theme/stories/examples/LoadingOverlay.tsx, packages/ag-grid-theme/stories/examples/MasterDetail.tsx, packages/ag-grid-theme/stories/examples/NoDataOverlay.tsx, packages/ag-grid-theme/stories/examples/Pagination.tsx, packages/ag-grid-theme/stories/examples/ParentChildRows.tsx, packages/ag-grid-theme/stories/examples/PinnedRows.tsx, packages/ag-grid-theme/stories/examples/RowGroupPanel.tsx, packages/ag-grid-theme/stories/examples/RowGrouping.tsx, packages/ag-grid-theme/stories/examples/SortAndFilter.tsx, packages/ag-grid-theme/stories/examples/StatusBar.tsx, packages/ag-grid-theme/stories/examples/WrappedCell.tsx, packages/ag-grid-theme/stories/examples/WrappedHeader.tsx
Prepare snapshot for #3195, where UITK ag grid theme is removed. Remove the switch in snapshot so there's some meaningful diff we can use.
=> Remove switch from ag grid theme snapshots

.changeset/fast-snakes-know.md, .changeset/violet-tomatoes-enjoy.md, packages/core/src/checkbox/Checkbox.css, packages/core/src/radio-button/RadioButton.css
Closes #3298
Change RadioButton  and Checkbox display to `inline-flex` so the hit area only covers the label
=> Fix checkbox and radio button hit area

.changeset/big-pumpkins-complain.md, packages/core/src/combo-box/ComboBox.tsx
Closes #3348
Moves reading event.target.value outside of the microtask so event is read immediately.
=> Fix ComboBox React 16 support

.changeset/theme-next-heading-font-core.md, .changeset/theme-next-heading-font-theme.md, .storybook/preview.tsx, docs/decorators/withTheme.tsx, packages/core/src/salt-provider/SaltProvider.tsx, packages/core/src/theme/HeadingFont.ts, packages/core/src/theme/index.ts, packages/core/stories/salt-provider/salt-provider-next.mdx, packages/theme/css/foundations/typography.css, packages/theme/css/palette/text-next.css, packages/theme/css/theme-next.css
Depends on #3391, review additional commits only
This serves initial feature support for font switching capability, but doesn't not include
- Upload Amplitude to storybook to be used (pending license discussion)
- Detailed doc on how to install Amplitude in an app, e.g., font face declaration for all font weight
- New display 4 text
- New display family size remapping in theme next
- Amplitude font weight remapping (medium v.s. Open Sans semi bold)
=> Theme next heading font switch

packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.cy.tsx, packages/lab/src/date-input/DateInput.css, packages/lab/src/date-picker/DatePicker.tsx, packages/lab/src/date-picker/DatePickerPanel.css, packages/lab/src/date-picker/DatePickerPanel.tsx, packages/lab/stories/date-picker/date-picker.stories.tsx, site/docs/components/date-picker/accessibility.mdx, site/docs/components/date-picker/examples.mdx, site/docs/components/date-picker/usage.mdx, site/src/examples/date-picker/SingleSelect.tsx, site/src/examples/date-picker/WithDisabledDates.tsx, site/src/examples/date-picker/WithFormField.tsx, site/src/examples/date-picker/index.ts
updates to date picker from unresolved feedback: 
https://github.com/jpmorganchase/salt-ds/pull/3234
in this PR, #discussion_ :
=> Date Picker updates

.changeset/bright-dogs-beg.md, packages/core/src/dialog/DialogContent.css, packages/core/stories/dialog/dialog.qa.stories.tsx
Preview at https://14c812da.saltdesignsystem-storybook.pages.dev/?path=/story/core-dialog--long-content
=> Remove padding in `DialogContent`

.changeset/salt-provider-next-accent.md, .changeset/strong-parents-march.md, .storybook/preview.tsx, docs/decorators/withTheme.tsx, packages/core/src/__tests__/__e2e__/salt-provider/SaltProvider.cy.tsx, packages/core/src/salt-provider/SaltProvider.tsx, packages/core/src/theme/Accent.ts, packages/core/src/theme/index.ts, packages/core/stories/salt-provider/salt-provider-next.mdx, packages/theme/css/foundations/fade-next.css, packages/theme/css/palette/accent-next.css
Depends on #3255, review additional commits only
=> Theme Next - accent switch

.changeset/little-years-press.md, packages/lab/src/__tests__/__e2e__/date-input/DateInput.cy.tsx, packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.cy.tsx, packages/lab/src/date-input/DateInput.tsx, packages/lab/src/date-picker/DatePicker.tsx, packages/lab/stories/date-input/date-input.stories.tsx, site/docs/components/date-picker/examples.mdx, site/src/examples/date-picker/Range.tsx
updates to date picker from unresolved feedback:
https://github.com/jpmorganchase/salt-ds/pull/3234
in this PR, #discussion_ :
for following PR:
=> Date picker updates from unresolved feedback on docs and tests

.changeset/silver-spiders-draw.md, docs/components/QAContainer.tsx, packages/core/stories/text/text.qa.stories.tsx, packages/lab/stories/kitchen-sink/kitchen-sink.stories.tsx, packages/theme/css/characteristics/status-next.css, packages/theme/css/palette/info-next.css, packages/theme/css/palette/negative-next.css, packages/theme/css/palette/positive-next.css, packages/theme/css/palette/warning-next.css
Replay of #3375 for theme next
=> Update status tokens for theme next to match latest design

.github/workflows/build-storybook.yml, .github/workflows/chromatic.yml, .github/workflows/publish-storybook.yml
Cancels in progress builds of Storybook to prevent Chromatic getting sent multiple builds when rebasing PRs.
Pins Chromatic to 11.3.5 to try resolve a bug.
=> Cancel in progress builds and pin Chromatic

packages/theme/css/foundations/color.css
No need for a changeset, correct values merged in #3477 (design updates)
=> Update citrine 900 lime 900 color

.changeset/config.json
Prevents ag-grid-theme being bumped as a major update when the theme package is updated.
=> Enable onlyUpdatePeerDependentsWhenOutOfRange for changesets

site/docs/components/ag-grid-theme/index.mdx
Adds v2 label to the site, to make it more obvious.
~~Maybe also a 'new' in the side bar?~~
=> Adds v2 to ag grid theme doc

.changeset/fluffy-snails-camp.md, packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.cy.tsx, packages/lab/src/date-input/DateInput.tsx, packages/lab/src/date-picker/DatePicker.tsx, packages/lab/stories/date-picker/date-picker.stories.tsx, site/docs/components/date-picker/examples.mdx, site/src/examples/date-picker/WithValidation.tsx
The following changes from feedback are addressed in this PR: 
~~- [ ] need an example for a custom placeholder~~
=> Date picker updates from feedback

.github/workflows/release.yml
Need to release a hotfix, ag-grid-theme@1.4.3 from #3585.
Enable the release PR from a branch, hopefully this is enough?
=> Add ag grid theme v1 release branch to CI

site/src/css/utilities/patches.css
Currently site date picker year dropdown is shown as truncated  
https://www.saltdesignsystem.com/salt/components/date-picker/examples
=> Fix site date picker calendar dropdown css

.changeset/kind-bottles-flow.md, packages/core/src/accordion/AccordionHeader.tsx, packages/core/src/accordion/AccordionPanel.css
Fixes the invalid HTML button > div vs button > span.
Updates a CSS selector to make it easier to override.
Adds a display name to a component to make it easier to debug.
=> Fix invalid HTML structure in AccordionHeader

.changeset/afraid-jobs-do.md, .storybook/preview.tsx, packages/theme/css/characteristics/content-next.css, packages/theme/css/characteristics/content.css, packages/theme/css/characteristics/status-next.css, packages/theme/css/characteristics/status.css, packages/theme/css/palette/error.css, packages/theme/css/palette/info.css, packages/theme/css/palette/success.css, packages/theme/css/palette/warning.css, packages/theme/stories/characteristics/content.mdx, packages/theme/stories/characteristics/status.mdx
To verify, use Storybook, go to `/?path=/docs/theme-characteristics-status--docs` and toggle between theme and theme next
I only did bare minimum in storybook, for us to confirm tokens in theme and theme next, given we don't have other mechanism to see them.
Part of #3535
=> Add status bold and content foreground bold tokens

.changeset/rotten-jokes-fix.md, packages/theme/css/characteristics/overlayable-next.css
The token is only used in ag grid theme, test with theme next enabled
#3517
=> Add `--salt-overlayable-rangeSelection` to theme next

site/docs/components/pill/index.mdx
This change is related to #25, adding a link in the right-hand column of the pill component back to badge
=> Add Badge to Pill's related components

.changeset/fresh-brooms-explain.md, packages/core/src/__tests__/__e2e__/salt-provider/SaltProvider.cy.tsx, packages/core/src/salt-provider/SaltProvider.tsx, site/docs/components/salt-provider/examples.mdx, site/src/examples/salt-provider/Theme.tsx
Uses `clsx` approach.
Added some doc for Salt provider props
=> Add support for multiple themes to be passed to `SaltProvider`

site/src/pages/_document.tsx
Closes #951
- Added a meta description.
- Copied the description text from the Salt home page, let me know if this should be changed to something else.
- Set the description in `_document.tsx`, however it can be set in `_app.tsx` instead if preferred. 
- Tested SEO using Lighthouse, 100% passing.
=> Add meta description

.changeset/large-carrots-end.md, package.json, packages/ag-grid-theme/css/salt-ag-grid-theme.css, packages/ag-grid-theme/src/dependencies/cell-editors/DropdownEditor.tsx, packages/ag-grid-theme/src/dependencies/cell-renderers/FlagRenderer.tsx, packages/ag-grid-theme/src/dependencies/dataGridExampleColumnsHdCompact.ts, packages/ag-grid-theme/src/dependencies/dataGridExampleData.ts, packages/ag-grid-theme/src/dependencies/useAgGridHelpers.ts, packages/ag-grid-theme/src/examples/HDCompact.tsx, packages/ag-grid-theme/stories/ag-grid-theme.stories.tsx, packages/core/src/list-control/ListControlState.ts, site/src/examples/ag-grid-theme/Default.tsx, site/src/examples/ag-grid-theme/useAgGridHelpers.ts
- Changed base size implementation in HD Compact
#3775, #3675
Design related task to support HD compact in Figma Next: https://github.com/jpmorganchase/salt-ds/issues/3850
=> Various ag grid theme fixes

.changeset/odd-candles-argue.md, packages/theme/css/deprecated/foundations.css
It is defined in `size.css` and not a deprecated token
=> Remove `--salt-size-selectable` from deprecated list

.changeset/dull-turtles-teach.md, packages/core/src/__tests__/__e2e__/form-field/FormField.cy.tsx, packages/core/src/form-field/FormFieldHelperText.tsx
Using the `color` prop instead of the deprecated `variant`. It should now apply the success/warning/error colour to the helper text based on the form field status.
Should address #3540
=> Support status color for FormFieldHelperText

.changeset/short-plants-own.md, packages/lab/src/__tests__/__e2e__/stepped-tracker/SteppedTracker.cy.tsx, packages/lab/src/stepped-tracker/TrackerStep/TrackerStep.css, packages/lab/src/stepped-tracker/TrackerStep/TrackerStep.tsx, packages/lab/stories/stepped-tracker/stepped-tracker.qa.stories.tsx, packages/lab/stories/stepped-tracker/stepped-tracker.stories.tsx, site/docs/components/stepped-tracker/examples.mdx, site/src/examples/stepped-tracker/Basic.tsx, site/src/examples/stepped-tracker/NonSequentialProgress.tsx, site/src/examples/stepped-tracker/StageAndStatus.tsx, site/src/examples/stepped-tracker/Status.tsx, site/src/examples/stepped-tracker/StepProgression.tsx, site/src/examples/stepped-tracker/Vertical.tsx, site/src/examples/stepped-tracker/index.ts
Adds `status` prop that takes `warning` and `error` values.
Renames `state` prop to `stage` (and renames "default" to "pending")
Sets precedence of stage and status: "completed" > "active" > "error|warning" > "pending"
=> Add `status` prop and rename `state` prop to `stage` for steps in SteppedTracker

.github/workflows/chromatic.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml
De-risks #3894. YARN_NPM_AUTH_TOKEN is used by yarn to publish packages. The snapshot is failing on that branch because it's not available. Adding it to main so it can be available and that branch can then be tested.
=> Add YARN_NPM_AUTH_TOKEN to release steps and only try remove the chromatic label on PRs

packages/core/src/form-field/FormField.tsx
Closes #3516
- Updated the `labelPlacement` description to include the `'right'` option.
- Updated the `disabled` and `readOnly` prop descriptions to be consistent with other components.
=> Update FormField prop descriptions

.changeset/pink-bears-refuse.md, packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx, packages/core/src/combo-box/ComboBox.tsx
Closes #3637
Updated ComboBox to hide it's trigger button when no content is available to show. This covers two main scenarios:
- When a filter has been applied, and nothing matches that filter.
- When there is no initial data present, but it will be fetched after typing.
=> Remove ComboBox's button when it has nothing to show

packages/core/src/salt-provider/SaltProvider.tsx, site/docs/components/salt-provider/index.mdx, site/docs/getting-started/developing.mdx, site/src/examples/salt-provider/Density.tsx, site/src/examples/salt-provider/Modes.tsx
Closes #3119
- Updated the provider `mode` and `density` site examples by wrapping them in a nested provider to show how to apply each prop.
- Added a link to the provider in the getting started docs.
=> Update Provider `mode` and `density` site examples

site/docs/components/card/index.mdx, site/docs/components/dialog/index.mdx, site/docs/components/list-box/index.mdx, site/docs/components/pagination/index.mdx, site/docs/components/panel/index.mdx, site/docs/components/switch/index.mdx, site/docs/components/tooltip/index.mdx
Removed "similar to" links for nonexistent components: tile, content status, vertical navigation item, carousel, toggle button group and content status
=> Update relatedComponents in component docs

.changeset/twelve-glasses-obey.md, packages/core/src/combo-box/ComboBox.css, packages/core/src/combo-box/ComboBox.tsx, packages/core/src/pill-input/PillInput.css, packages/core/src/pill-input/PillInput.tsx, site/src/examples/combo-box/Disabled.tsx
Closes #3921, Closes #3940, Closes #3612
- Fixed ComboBox breaking when `inputRef` is used.
- Fixed ComboBox having an incorrect focus ring color when validation is applied.
- Fixed ComboBox having incorrect active styling.
=> ComboBox fixes

site/docs/components/drawer/index.mdx, site/docs/components/drawer/usage.mdx
=> Update drawer site docs

.changeset/plenty-pans-film.md, packages/core/src/panel/Panel.css
closes #3013
also adds font-family to Panel, as in Safari this isn't picked up within plain text in a Panel (unless Text component directly used)
=> Fix text inside Panel having the incorrect color when color-scheme is not set or doesn't change the default text color e.g. in Safari

site/docs/components/accordion/examples.mdx, site/src/examples/accordion/Controlled.tsx, site/src/examples/accordion/ExpandAll.tsx, site/src/examples/accordion/index.ts
Closes #3965
- Added a controlled Accordion example which includes the expand all and collapse all buttons.
=> Add controlled Accordion example

.changeset/good-fishes-shout.md, packages/core/src/__tests__/__e2e__/checkbox/Checkbox.cy.tsx, packages/core/src/__tests__/__e2e__/input/Input.cy.tsx, packages/core/src/__tests__/__e2e__/multiline-input/MultilineInput.cy.tsx, packages/core/src/__tests__/__e2e__/radio-button/RadioButton.cy.tsx, packages/core/src/__tests__/__e2e__/switch/Switch.cy.tsx, packages/core/src/checkbox/Checkbox.tsx, packages/core/src/index.ts, packages/core/src/input/Input.tsx, packages/core/src/multiline-input/MultilineInput.tsx, packages/core/src/pill-input/PillInput.tsx, packages/core/src/radio-button/RadioButton.tsx, packages/core/src/switch/Switch.tsx, packages/core/src/types.ts
Specifically chose to accept only data-* attributes (not any string like MUI), so that we're achieving the same level of acceptance when passing to an `input`. e.g. `<input random>` is not valid.
Ref - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*
#3797
=> Fix data attributes error on pass through props

.changeset/cold-carrots-hide.md, .changeset/hip-trainers-wash.md, packages/core/src/dropdown/Dropdown.css, packages/core/src/input/Input.css, packages/core/src/multiline-input/MultilineInput.css, packages/core/src/pill-input/PillInput.css, packages/lab/src/date-input/DateInput.css
Closes #3861
Closes #3596 
Fixed bordered form controls' activation indicator and border combining to 3px instead of 2px in:
- Dropdown
- ComboBox
- Input
- MultilineInput
Fixed form controls' activation indicator changing color when an active field is hovered in:
- Input
- MultilineInput
Updated the token applied to form controls' activation indicator to use `--salt-size-border-strong` instead of `  --salt-editable-borderWidth-active`.
Updated DatePicker to show validation status when set to read-only.
=> Align form control styling

.changeset/ag-theme-selection-highlight.md, .changeset/theme-background-highlight.md, packages/ag-grid-theme/css/salt-ag-grid-theme.css, packages/theme/css/characteristics/overlayable-next.css, packages/theme/css/characteristics/overlayable.css, packages/theme/css/foundations/fade.css, packages/theme/css/palette/neutral.css
Copy cells to see highlight color
Before release, double check `peerDependencies` is bumped in `@salt-ds/ag-grid-theme`
#3922
=> Add ag grid copy highlight color

.changeset/unlucky-lobsters-arrive.md, packages/core/src/dialog/DialogContent.css
Closes #4066
Due to a bug in safari with flex, the fix is to add "auto"
=> Fix Dialog's content being collapsed on Safari

.changeset/config.json, .yarn/patches/@changesets-assemble-release-plan-npm-6.0.3-29726de363.patch, yarn.lock
https://github.com/jpmorganchase/salt-ds/pull/4055#discussion_r1761422010
This gets us to below result when running `changeset version` locally
```
{
"name": "@salt-ds/ag-grid-theme",
"version": "2.1.0",
...
"peerDependencies": {
"@salt-ds/theme": "^1.22.0"
}
```
and
```
"name": "@salt-ds/theme",
"version": "1.22.0",
```
=> Patch changeset to make theme & ag-grid-theme peerDep version bump work

.changeset/popular-forks-doubt.md, packages/theme/css/palette/foreground-next.css
Code and Figma got out of sync during early salt next design phase.
To fully prevent this, #4041 is needed.
=> Fix foreground secondary color token in Salt theme next

site/src/components/components/LivePreview.module.css, site/src/components/components/LivePreview.tsx, site/src/css/global/code.css
Changes:
- padding added to the container
- source code is trimmed
- code preview no longer adds space below the switch
- Added a gap between the switch and example content
Before:
https://github.com/user-attachments/assets/e41638e6-9f40-4300-b463-b661310307e9
After:
https://github.com/user-attachments/assets/9c035c8b-f11c-484b-a6f6-163e3403f41f
=> Improve example styling

.github/workflows/test.yml
=> fix: usage of `a deprecated Node.js version`

.changeset/thirty-knives-learn.md, packages/countries/src/__tests__/__e2e__/LazyCountrySymbol.cy.tsx, packages/countries/src/lazy-country-symbol/LazyCountrySymbol.tsx, packages/countries/stories/LazyCountrySymbol.qa.stories.tsx, packages/countries/stories/LazyCountrySymbol.stories.tsx, site/src/examples/country-symbol/LazyLoading.tsx
Received community report, this is useful when receiving `code` from API.
Also fix `sharp` was not working for `LazyCountrySymbol`
#4161
=> Fix LazyCountrySymbol crash with invalid code

.changeset/ninety-bottles-deny.md, packages/ag-grid-theme/css/salt-ag-grid-theme.css, packages/ag-grid-theme/src/dependencies/dataGridExampleColumns.ts, packages/ag-grid-theme/src/dependencies/dataGridExampleColumnsHdCompact.ts, site/src/examples/ag-grid-theme/data/defaultColumns.ts
`.edtiable-cell` should only be setting the border / corner flag styling. `.numeric-cell` is the one for right alignment (for both header and body cells)
#4141
=> Fix `.editable-cell` incorrectly set right text align

site/src/layouts/DetailBase/DetailBase.module.css, site/src/layouts/DetailBase/DetailBase.tsx, site/src/layouts/LayoutColumns/LayoutColumns.module.css, site/src/pages/_app.tsx
- Mobile drawer menu should be better now with global density change + [mosaic#663](https://github.com/jpmorganchase/mosaic/pull/663)
- Component page body & TOC spacing should be improved for viewport just above tablet
- Fixed component nav bar, so scrolling down would see last entry "Tooltip", before scrolling the whole page down
App header is constrained by Mosaic `LayoutBase`, with existing content, we'll need 5 specific breakpoints
- 1478+, full logo + menu items + search + buttons
- 1380+, mobile logo
- 1280+, remove buttons
- remaining, replace menu items with drawer
=> Site quick responsiveness improvement

.changeset/actionable-accented-border.md, .changeset/eleven-plums-shop.md, .changeset/famous-oranges-bake.md, biome.jsonc, packages/core/src/card/Card.css, packages/core/src/interactable-card/InteractableCard.css, packages/core/src/link-card/LinkCard.css, packages/core/stories/link-card/link-card.stories.tsx, packages/theme/css/characteristics/accent-next.css, packages/theme/css/characteristics/accent.css, packages/theme/css/characteristics/actionable.css, packages/theme/css/palette/accent.css, packages/theme/css/palette/interact.css
Kept `--card-accent-color` in case anyone using it. 
Moved hover block before active, to make border/shadow styles correct.
#3875
=> Card design consolidation

.changeset/polite-bags-act.md, docs/components/ResponsiveContainer.tsx, packages/lab/src/__tests__/__e2e__/stepper-input/StepperInput.accessibility.cy.tsx, packages/lab/src/__tests__/__e2e__/stepper-input/StepperInput.cy.tsx, packages/lab/src/stepper-input/StepperInput.css, packages/lab/src/stepper-input/StepperInput.tsx, packages/lab/src/stepper-input/internal/useActivateWhileMouseDown.ts, packages/lab/src/stepper-input/internal/useSpinner.ts, packages/lab/src/stepper-input/internal/utils.ts, packages/lab/src/stepper-input/useStepperInput.ts, packages/lab/stories/stepper-input/stepper-input.qa.stories.tsx, packages/lab/stories/stepper-input/stepper-input.stories.tsx
No site doc in this PR, will be in #3586
---
- Refactored stepper input to not use `Input` component, which causes the props to be inconsistent (e.g. needing `InputProps.inputProps`)
- Added full border examples, supports theme next rounded corner styling options
- Updated increment / decrement button gap to be `border-strong` (suggested in #3878)
- Added more keyboard interactions, suggested by [APG spinbutton](https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/), i.e., home/end, page up/down
---
to do ..
#1855, #3878
=> Refactor stepper input

.github/workflows/chromatic.yml
Due to workflow_run being run on main, you have to it from chromatic.yml first. A later PR can remove it from build-storybook.yml
=> Remove restriction that draft PRs can't run Chromatic

packages/ag-grid-theme/src/examples/Default.tsx, packages/core/src/dialog/Dialog.tsx, packages/core/stories/dialog/dialog.qa.stories.tsx, packages/core/stories/form-field/form-field.qa.stories.tsx, packages/core/stories/link/link.qa.stories.tsx, packages/core/stories/list-box/list-box.qa.stories.tsx, packages/core/stories/pagination/pagination.qa.stories.tsx
addresses theme next in qas from https://github.com/jpmorganchase/salt-ds/issues/4134; adds status bar to ag grid example.
dialog refactor not in this PR
=> enable missing next theme in qas

.changeset/tiny-fishes-guess.md, packages/core/src/__tests__/__e2e__/combo-box/ComboBox.cy.tsx, packages/core/src/list-control/ListControlState.ts, packages/core/stories/combo-box/combo-box.stories.tsx
Before:
16
17
18
After
16
17
18
=> Improve list based control's performance when lots of items are displayed

.changeset/orange-tips-itch.md, packages/core/src/multiline-input/MultilineInput.css, site/docs/components/multiline-input/examples.mdx, site/src/examples/multiline-input/MaxHeight.tsx, site/src/examples/multiline-input/index.ts
Closes #3964
- Added a max-height multiline input example to site docs.
=> Add max-height multiline input example

site/docs/foundations/fragments/feedback.mdx, site/docs/foundations/typography.mdx
**In relation to Galao GH issue #4228** 
- Changed some content descriptions
- Removed the Do’s + Don’ts 
- Removed Type alignment section. (can be in a blog post) 
- Removed section on Color + Type on a background. (can be in a blog post) 
- Added section on Notation
=> Update typography doc.mdx

.changeset/slow-bags-give.md, packages/core/src/__tests__/__e2e__/tooltip/Tooltip.cy.tsx, packages/core/src/tooltip/Tooltip.tsx
Closes #3868
Tooltip now prioritizes it's `status` prop over the status inherited from a parent FormField.
=> Fix Tooltip status override

packages/ag-grid-theme/package.json, packages/ag-grid-theme/scripts/build.mjs, scripts/build.mjs, scripts/transformWorkspaceDeps.mjs, yarn.lock
Using a workspace protocol is better since it will get transformed during build and means that the version will be up-to-date and not out of sync to the next released version.
Also since it is transformed during the build it's ignored by changesets and doesn't break the Version Packages PR. It also aligns peer dependencies with how we handle workspace dependencies already.
=> Use workspace protocol for theme peer dependency

packages/core/stories/dialog/dialog.qa.stories.tsx, packages/core/stories/file-drop-zone/file-drop-zone.qa.stories.tsx, packages/core/stories/overlay/overlay.qa.stories.tsx
add no injection qas for dialog, dropzone and overlay qa stories
closes https://github.com/jpmorganchase/salt-ds/issues/3713
=> QA updates 

packages/ag-grid-theme/css/parts/ag-header.css
Changset not needed, will go with #4418
The column menu icon, hover over icon, in **theme next**
https://storybook.saltdesignsystem.com/?path=/story/ag-grid-ag-grid-theme--context-menu&globals=themeNext:enable;accent:teal
=> Fix ag grid menu icon hover color in theme next

site/docs/foundations/color.mdx
Info status do not point to accent, it's a planned future change
https://github.com/jpmorganchase/salt-ds/blob/5c8d47b934db5aee0c46c03b5461e60307e32150/packages/theme/css/characteristics/status-next.css#L6
=> Fix Site Doc Info status color description

.changeset/modern-zebras-pretend.md, packages/lab/src/system-status/SystemStatus.css, packages/lab/stories/system-status/system-status.qa.stories.tsx
avoid icons that are in the content of a system status from inheriting the component override in color.
=> fix system status icon styles

.changeset/modern-chefs-knock.md, packages/core/src/utils/useFloatingUI/useFloatingUI.tsx
This should solve the problem where users using mixed density and portal launch mess up the whole UI
=> Scope floating ui portal

packages/core/package.json, packages/lab/package.json, yarn.lock
Replaces #4478, 0.27.0 contains a breaking change that drops react 16 support.
=> Update dependency @floating-ui/react to ^0.26.28

site/docs/components/combo-box/accessibility.mdx, site/docs/components/dropdown/accessibility.mdx, site/docs/components/tabs/accessibility.mdx
preview page: https://saltdesignsystem-git-3490-dropdown-safari-known-75de3d-fed-team.vercel.app/salt/components/dropdown/accessibility
#3490
=> Add known dropdown a11y issue

.changeset/silent-pigs-love.md, .changeset/sixty-seals-roll.md, packages/theme/css/characteristics/content-next.css, packages/theme/css/deprecated/palette-next.css, packages/theme/css/palette/foreground-next.css, packages/theme/css/theme-next.css
=> Fix link colors in the Next theme

.changeset/poor-scissors-chew.md, packages/core/src/dialog/DialogHeader.css, packages/lab/src/dialog/DialogHeader.css, packages/lab/src/dialog/DialogHeader.tsx, packages/lab/src/overlay/OverlayHeader.css, packages/lab/src/overlay/OverlayHeader.tsx, packages/lab/stories/dialog/dialog.qa.stories.tsx, packages/lab/stories/dialog/dialog.stories.tsx, packages/lab/stories/overlay/overlay.qa.stories.tsx, packages/lab/stories/overlay/overlay.stories.tsx, site/src/examples/dialog/WithHeader.tsx, site/src/examples/overlay/WithHeader.tsx
fix alignment for titles spanning into multiple lines, wrap dialog header in H2 to avoid breaking change
=> Updates to headers alignment

.changeset/wet-swans-wave.md, packages/core/src/toast/Toast.css
Closes #3524
In the Figma spec, the high density icon has a `padding-top` value of `1px`. The other densities have a value of `2px`.
In the code, the `padding-top` value is combined with the `margin-top` value, however all densities have a value of `2px`.
I've updated the CSS to use `1px` instead of `2px` when high density is selected.
=> Fix HD Toast icon alignment

.changeset/heavy-mice-repeat.md, packages/core/src/toggle-button-group/ToggleButtonGroup.css, packages/core/src/toggle-button/ToggleButton.css
When standalone toggle button is used, it should have same corner radius as button. Only when it is used within toggle button group, it should change to match "nested" corner.
[#4140](https://github.com/jpmorganchase/salt-ds/issues/4140)
=> Fix standalone ToggleButton corner radius

.changeset/little-countries-boil.md, packages/core/src/flex-item/FlexItem.css, packages/core/src/flex-item/FlexItem.tsx, packages/core/src/flex-layout/FlexLayout.css, packages/core/src/flex-layout/FlexLayout.tsx, packages/core/src/flow-layout/FlowLayout.tsx, packages/core/src/split-layout/SplitLayout.tsx, packages/core/src/stack-layout/StackLayout.tsx, packages/core/stories/flex-layout/flex-layout.stories.tsx, packages/core/stories/layout/layout.stories.css, site/docs/components/flex-layout/examples.mdx, site/docs/components/flow-layout/examples.mdx, site/docs/components/split-layout/examples.mdx, site/docs/components/stack-layout/examples.mdx, site/src/examples/flex-layout/Spacing.module.css, site/src/examples/flex-layout/Spacing.tsx, site/src/examples/flex-layout/index.ts, site/src/examples/flow-layout/Spacing.module.css, site/src/examples/flow-layout/Spacing.tsx, site/src/examples/flow-layout/index.ts, site/src/examples/split-layout/Spacing.module.css, site/src/examples/split-layout/Spacing.tsx, site/src/examples/split-layout/index.ts, site/src/examples/stack-layout/Spacing.module.css, site/src/examples/stack-layout/Spacing.tsx, site/src/examples/stack-layout/index.ts
add margin and paddings to flex layout as a multiplier of salt-spacing
=> Flex layout and items margin and paddings

.changeset/hungry-schools-hope.md, packages/core/src/form-field/FormField.css
Closes #3794 
This is aligning our form fields in the middle of our layouts and to my knowledge is unnecessary for form field styling itself(?)
we have been applying
:global(.saltFormField-labelLeft),
:global(.saltFormField-labelRight) {
align-self: unset;
}
=> Remove align self center from form field

.changeset/soft-ways-flash.md, packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.range.cy.tsx, packages/lab/src/__tests__/__e2e__/date-picker/DatePicker.single.cy.tsx, packages/lab/src/date-picker/DatePickerRangeInput.tsx, packages/lab/src/date-picker/DatePickerSingleInput.tsx, packages/lab/stories/date-picker/date-picker-range.qa.stories.tsx, packages/lab/stories/date-picker/date-picker-single.qa.stories.tsx
=> Disable DateInput when DatePicker is disabled

.changeset/three-years-visit.md, packages/core/src/__tests__/__e2e__/utils/useFloatingUI.cy.tsx, packages/core/src/dialog/Dialog.tsx, packages/core/src/utils/useFloatingUI/useFloatingUI.tsx, packages/core/src/utils/usePreventScroll.ts
Closes #3906
Added `disableScroll` prop to FloatingComponent, which sets the document body overflow to `hidden` to prevent background scrolling.
=> Fix Dialog background scroll

site/docs/components/accordion/accessibility.mdx
Adding Known Issue with Safari/VoiceOver - does not report state changes dynamically. (e.g. expanded/collapsed) Not a Salt Bug
Is a Safari/Mac/VoiceOver bug.
Add A11y best practices
Closes issue: https://github.com/jpmorganchase/salt-ds/issues/4814
=> Update accordion accessibility docs

packages/core/stories/patterns/indication/indication.stories.tsx, site/docs/patterns/indication.mdx, site/src/components/components/LivePreview.tsx, site/src/components/components/ThemeControls.module.css, site/src/components/components/ThemeControls.tsx, site/src/components/patterns/ColorIndicator.tsx, site/src/components/patterns/index.ts, site/src/examples/pattern-indication/PatternIndication.module.css, site/src/examples/pattern-indication/Progression.tsx, site/src/examples/pattern-indication/Sentiment.tsx, site/src/examples/pattern-indication/Status.tsx, site/src/examples/pattern-indication/StatusTable.tsx, site/src/examples/pattern-indication/Urgency.tsx, site/src/examples/pattern-indication/ValueCells.tsx, site/src/examples/pattern-indication/index.ts, site/src/layouts/DetailComponent/ComponentPageHeading.tsx, site/src/layouts/DetailComponent/DetailComponent.module.css, site/src/layouts/DetailPattern/DetailPattern.module.css, site/src/layouts/DetailPattern/DetailPattern.tsx
Made some changes to [Figma](https://www.figma.com/design/p6aJv3hER4wRSQrU2poDtj/Indication-Pattern-(DS)?node-id=1-1591&m=dev). Preview [link to page](https://saltdesignsystem-git-3852-indication-pattern-fed-team.vercel.app/salt/patterns/indication).
- Table with very long text doesn't work out nicely on site layout. Breakout usage guidance on top of table
- Does not support 2 colored dots in the table
- Added inline code example as well as storybook (can be removed when general layout be updated)
- Added same theme switch panel from component pages, so icon examples can be toggled between 2 themes
#3852
=> Indication pattern

.changeset/rude-pugs-perform.md, packages/core/src/border-layout/BorderLayout.tsx
border layout type is not allowing for a single children to be used
closes: https://github.com/jpmorganchase/salt-ds/issues/4917
=> fix border type

.github/workflows/snapshot.yml
Try to fix snapshot release not adding success comment back to PR
Output [example here](https://productionresultssa8.blob.core.windows.net/actions-results/0a6385f7-2d0d-4f35-99a7-fa2bf2657026/workflow-job-run-b1f201b7-a245-58a5-e067-7696c2487ba9/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-04-02T07%3A41%3A13Z&sig=vlW64uHFucuB7gnuQkhqrmuR%2Fsxds9C9Gg8TQwLIxbw%3D&ske=2025-04-02T16%3A52%3A15Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-04-02T04%3A52%3A15Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-01-05&sp=r&spr=https&sr=b&st=2025-04-02T07%3A31%3A08Z&sv=2025-01-05) shows: `[32msuccess[39m packages published successfully:`
=> Fix snapshot success comment

packages/lab/src/__tests__/__e2e__/tabs-next/TabsNext.cy.tsx
Move checks around the unstable test on React 17.  Remove 2nd check given 1st set should be enough.
=> Update unstable TabsNext test

site/src/css/base.css, site/src/layouts/Base/Base.module.css, site/src/layouts/Base/PageHeading.module.css, site/src/layouts/DetailComponent/ComponentPageHeading.module.css, site/src/layouts/DetailComponent/DetailComponent.module.css
Test on [`/salt/components/ag-grid-theme/accessibility`](https://saltdesignsystem-git-4908-fix-tabs-shrinking-fed-team.vercel.app/salt/components/ag-grid-theme/accessibility), which shouldn't have narrow tabs.
Extract content max width to a global variable to prepare for update in the future. Not including max-width update to 85ch, before font size can be updated to 16px (#4977)
Closes #4908
=> Fix component page tabs shrink

site/src/Body/Body.tsx, site/src/layouts/Base/Base.module.css
[`/salt/themes`](https://saltdesignsystem-git-content-width-fix-fed-team.vercel.app/salt/themes) content width is broken on smaller viewport
=> Fix site theme page content width

site/docs/themes/characteristics/index.mdx, site/docs/themes/characteristics/legacy.mdx
Missing 2 groups from the doc
Category and content was missing on [`/salt/themes/characteristics/index`](https://saltdesignsystem-git-4769-add-content-category-243389-fed-team.vercel.app/salt/themes/characteristics/index)
=> doc: Add Category and Content group to characteristics page

site/src/components/components/LivePreview.tsx, site/src/components/mdx/pre/Pre.tsx
Try any code block, e.g., `/salt/getting-started/developing`, was not copying...
=> Fix site code block copy button not working

site/src/components/country-symbol-preview/CountrySymbolPreview.tsx, site/src/components/icon-preview/IconPreview.module.css, site/src/components/icon-preview/IconPreview.tsx
- fix icon search doesn't support 2 words, e.g. "man woman" wasn't result anything
- move total / filter count to the bottom, to be more aligned with [ag grid status bar](https://www.saltdesignsystem.com/salt/components/ag-grid-theme/examples#status-bar)
- use visible form field label to be more accessible on the search field
- use top aligned form field on the checkbox group, given left aligned has problem due to 16px font-size override.
=> Update icon and country symbol site search

site/src/examples/toggle-button/ToggleButtonGroupDisabled.tsx
The disabled toggle button group example has an incorrect toggle button selected. Small update to set the "Selected disabled" toggle button as selected in the group.
=> Update toggle button disabled docs

site/src/components/diagrams/Diagrams.module.css
Try to align with component preview.
See [`/salt/patterns/search`](https://saltdesignsystem-git-site-diagram-image-radius-fed-team.vercel.app/salt/patterns/search)
=> Add corner radius to Site Diagram

packages/ag-grid-theme/src/examples/CustomFilter.tsx, packages/ag-grid-theme/src/examples/ProvidedCellEditors.tsx, site/src/examples/ag-grid-theme/data/cellEditorsDataTypes.ts
=> refactor: remove `Unexpected any` in 2 locations

packages/ag-grid-theme/scripts/build.mjs, packages/date-adapters/scripts/build.mjs, packages/react-resizable-panels-theme/scripts/build.mjs, packages/theme/scripts/build.mjs, scripts/build.mjs
Node 22 breaks the old scripts. Node changed the way path functions work, which means they don't work with URLs e.g. file://. Apparently this was never supported
=> Fix build scripts

.changeset/dirty-deers-hope.md, packages/ag-grid-theme/css/parts/ag-buttons.css, packages/ag-grid-theme/css/parts/ag-root-var.css, packages/ag-grid-theme/css/salt-ag-grid-theme.css, site/src/examples/ag-grid-theme/HDCompact.tsx
Extract fixes out from #5054. Test ag grid site example ([Preview](https://saltdesignsystem-git-5056-ag-theme-zebra-border-color-fed-team.vercel.app/salt/components/ag-grid-theme/examples)):
- Variants example: zebra variant selection border color
- HD compact example, row selection color
#5056
=> Fix AG theme zebra variant selection border colors

.changeset/rich-walls-chew.md, packages/core/src/checkbox/CheckboxIcon.css, packages/core/src/checkbox/CheckboxIcon.tsx
When a checkbox has checked/defaultChecked set to true but is indeterminate, blue color styles are overriding the what should be gray (according to Figma spec) styles for an indeterminate checkbox as noticed here by @origami-z  https://storybook.saltdesignsystem.com/?path=/story/core-salt-provider--toggle-theme&globals=density:low 
Before
After
=> Fix checked indeterminate Checkbox styling 

.changeset/forty-dingos-reply.md, .changeset/young-flies-wonder.md, packages/core/src/menu/MenuItem.css, packages/lab/src/cascading-menu/CascadingMenuItem.css, packages/lab/src/list-deprecated/List.tsx, packages/lab/src/list-deprecated/internal/DescendantContext.tsx, packages/theme/css/characteristics/selectable-next.css, packages/theme/css/characteristics/selectable.css, packages/theme/css/deprecated/characteristics-next.css, packages/theme/css/deprecated/characteristics.css, packages/theme/css/deprecated/palette.css, packages/theme/css/palette/interact.css, packages/theme/css/theme-next.css
This includes a change to CascadingMenu (a legacy component).
After:
=> Deprecate selectable blur selected tokens

site/docs/about/glossary.mdx
Based on the read-only blurb in the glossary, we needed to adjust the language to exclude radio and checkbox as we don't support this in our components.
=> Update glossary to clarify read-only validation support

.changeset/quiet-hairs-try.md, .changeset/tasty-snakes-clean.md, packages/highcharts-theme/src/examples/DonutChart.tsx, packages/highcharts-theme/src/examples/PieChart.tsx, packages/highcharts-theme/src/examples/index.ts, packages/highcharts-theme/src/highcharts-options-salt.ts, packages/highcharts-theme/stories/highcharts-theme.stories.tsx, site/docs/components/highcharts-theme/examples.mdx, site/src/examples/highcharts-theme/PieChart.tsx, site/src/examples/highcharts-theme/index.ts
- DonutChart is a variant of PieChart, so the `plotOptions.pie.innerSize` setting is moved out of the global options; otherwise, a default PieChart would automatically become a DonutChart. Consumers are instructed to supply the `innerSize` setting themselves in documentation.
- Documentation reordered to show PieChart first due to the above.
=> Highcharts | Add PieChart

packages/highcharts-theme/src/examples/dependencies/bulletOptions.ts, site/src/examples/highcharts-theme/BulletChart.tsx
In Highcharts, using the bullet() module sets the chart to be a "bullet" which means you can put anything into the type field and it'll still look like a bullet chart (which is why this was missed...)
inverted: true inverts the axes so that the x axis is vertical and y axis is horizontal (giving the left to right bar effect).
=> Fix: Use bullet chart type
